/* WH.pwa - installable app + offline use (SPEC 6.3).
 *
 * Active ONLY when the page is served over http(s) (GitHub Pages, a local server). On file:// nothing happens at all:
 * no <link rel="manifest">, no service worker, no request - the double-clicked file keeps working exactly as before.
 *
 *   - adds <link rel="manifest" href="manifest.webmanifest"> and <link rel="apple-touch-icon">
 *   - registers ./sw.js after the page has loaded (see src/pwa/sw.js; the root copy is generated by build.mjs)
 *   - a new version waiting in the background -> toast "A new version is available - Reload"; Reload tells the waiting
 *     worker to take over and reloads the page once it did (never on its own: work in progress is not interrupted)
 *   - looks for a new version again when the app comes back to the foreground (at most every 30 minutes, online only)
 *   - remembers the browser's install offer (beforeinstallprompt) so File menu can show "Install as an app"
 *   - keeps <meta name="theme-color"> in line with a manually chosen theme (this part also runs on file://)
 *
 *   WH.pwa = { enabled, supported, registration, updateReady, canInstall(), install(), applyUpdate(), checkForUpdate() } */
(function () {
  'use strict';
  const g = globalThis;
  g.WH = g.WH || {};
  const WH = g.WH;

  const MANIFEST = 'manifest.webmanifest';
  const SW_URL = './sw.js';
  const TOUCH_ICON = 'assets/apple-touch-icon.png';
  const THEME_COLOR = { light: '#ffffff', dark: '#142038' };   // = header surface (--glass on --bg) per theme
  const RECHECK_MS = 30 * 60 * 1000;

  const hasDom = typeof document !== 'undefined' && typeof location !== 'undefined';
  const web = hasDom && (location.protocol === 'http:' || location.protocol === 'https:');
  // service workers need a secure context (https or localhost); plain http on a LAN address just skips them
  const swOk = web && typeof navigator !== 'undefined' && 'serviceWorker' in navigator && g.isSecureContext !== false;

  const state = {
    registration: null,
    waiting: null,
    toast: null,
    reloading: false,
    lastCheck: 0,
    installEvent: null,
  };

  function addLink(rel, href) {
    if (document.querySelector(`link[rel="${rel}"]`)) return;
    const l = document.createElement('link');
    l.rel = rel;
    l.href = href;
    document.head.append(l);
  }

  // -------------------------------------------------------------------------------------------------------------------
  // theme-color follows a forced theme (auto = the two media-specific metas from the template do the work)
  // -------------------------------------------------------------------------------------------------------------------
  function syncThemeColor() {
    if (!hasDom) return;
    const forced = document.documentElement.getAttribute('data-theme');
    for (const m of Array.from(document.querySelectorAll('meta[name="theme-color"][data-scheme]'))) {
      const scheme = forced === 'light' || forced === 'dark' ? forced : m.getAttribute('data-scheme');
      const want = THEME_COLOR[scheme] || THEME_COLOR.light;
      if (m.getAttribute('content') !== want) m.setAttribute('content', want);
    }
  }

  // -------------------------------------------------------------------------------------------------------------------
  // updates
  // -------------------------------------------------------------------------------------------------------------------
  function offerUpdate(worker) {
    state.waiting = worker;
    if (state.toast || !WH.ui || typeof WH.ui.toast !== 'function') return;
    state.toast = WH.ui.toast({ i18n: 'pwa.update', action: { i18n: 'pwa.reload', fn: applyUpdate } }, { kind: 'info', ms: 0 });
    if (WH.bus) WH.bus.emit('pwa:update', { version: 'waiting' });
  }

  /** Activate the waiting version and reload into it. */
  function applyUpdate() {
    const reg = state.registration;
    const w = state.waiting || (reg && reg.waiting);
    state.reloading = true;
    if (!w) { location.reload(); return; }
    w.postMessage({ type: 'SKIP_WAITING' });
    // 'controllerchange' reloads; if it never comes (the update became redundant), reload anyway
    setTimeout(() => { if (state.reloading) location.reload(); }, 4000);
  }

  function watch(reg) {
    state.registration = reg;
    if (reg.waiting && navigator.serviceWorker.controller) offerUpdate(reg.waiting);
    reg.addEventListener('updatefound', () => {
      const nw = reg.installing;
      if (!nw) return;
      nw.addEventListener('statechange', () => {
        // 'installed' while a controller exists = an update is waiting (the very first install has no controller)
        if (nw.state === 'installed' && navigator.serviceWorker.controller) offerUpdate(nw);
      });
    });
  }

  /** Ask the browser to look for a newer sw.js now (quietly; offline or failing checks are ignored). */
  function checkForUpdate() {
    const reg = state.registration;
    if (!reg || (typeof navigator !== 'undefined' && navigator.onLine === false)) return Promise.resolve(false);
    state.lastCheck = Date.now();
    return reg.update().then(() => true, () => false);
  }

  function register() {
    let p;
    try { p = navigator.serviceWorker.register(SW_URL); } catch (e) { return; }
    p.then(watch, () => { /* blocked (private mode, storage off, policy): the app simply works online */ });
    navigator.serviceWorker.addEventListener('controllerchange', () => {
      // only reload when the user asked for the new version (the first install also changes the controller)
      if (!state.reloading) return;
      state.reloading = false;
      location.reload();
    });
    document.addEventListener('visibilitychange', () => {
      if (document.visibilityState === 'visible' && Date.now() - state.lastCheck > RECHECK_MS) checkForUpdate();
    });
    state.lastCheck = Date.now();
  }

  // -------------------------------------------------------------------------------------------------------------------
  // install offer (Chrome / Edge / Android): kept for File menu -> "Install as an app"; iOS has no such event
  // (Help -> "On your phone" explains Share -> Add to Home Screen)
  // -------------------------------------------------------------------------------------------------------------------
  function canInstall() { return !!state.installEvent; }

  async function install() {
    const ev = state.installEvent;
    if (!ev) return false;
    state.installEvent = null;
    try {
      await ev.prompt();
      const choice = await ev.userChoice;
      return !!(choice && choice.outcome === 'accepted');
    } catch (e) {
      return false;
    }
  }

  // -------------------------------------------------------------------------------------------------------------------
  // start
  // -------------------------------------------------------------------------------------------------------------------
  function start() {
    syncThemeColor();
    if (WH.bus) WH.bus.on('theme:changed', syncThemeColor);
    if (!web) return;
    addLink('manifest', MANIFEST);
    addLink('apple-touch-icon', TOUCH_ICON);
    if (!swOk) return;
    if (document.readyState === 'complete') register();
    else window.addEventListener('load', register, { once: true });
  }

  if (web) {
    window.addEventListener('beforeinstallprompt', (e) => { state.installEvent = e; });
    window.addEventListener('appinstalled', () => { state.installEvent = null; });
  }

  WH.pwa = {
    /** true over http(s): manifest + service worker are in play; false on file:// */
    enabled: web,
    /** service worker available (secure context) */
    supported: swOk,
    get registration() { return state.registration; },
    get updateReady() { return !!(state.waiting || (state.registration && state.registration.waiting)); },
    canInstall, install, applyUpdate, checkForUpdate, syncThemeColor,
  };

  if (hasDom) {
    if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', start, { once: true });
    else start();
  }
})();
