/* Shell strings: header, welcome, file menu, help panel, shortcuts, tour, import/export messages. (cs + en) */
(function () {
  'use strict';
  const I = globalThis.WH.i18n;

  I.add('cs', {
    'app.description': 'Plánovač pokrytí Wi-Fi: nakresli půdorys, přesuň router a hned uvidíš, kde je signál dobrý. Výpočty běží ve tvém prohlížeči.',

    // --- common ---------------------------------------------------------------------------------------------------
    'ui.ok': 'OK',
    'ui.cancel': 'Zrušit',
    'ui.close': 'Zavřít',
    'ui.undo': 'Zpět',
    'ui.delete': 'Smazat',
    'ui.loading': 'Načítám…',
    'ui.copy': 'Kopírovat',

    // --- header ---------------------------------------------------------------------------------------------------
    'shell.skip': 'Přeskočit na obsah',
    'shell.subtitle': 'Plánování Wi-Fi',
    'shell.brand.aria': 'WiFi Heatmap Architect',
    'shell.mode.aria': 'Režim aplikace',
    'shell.mode.plan': 'Půdorys',
    'shell.mode.plan.short': 'Půdorys',
    'shell.mode.wifi': 'Wi-Fi',
    'shell.mode.plan.tip': 'Kreslení a úprava půdorysu',
    'shell.mode.wifi.tip': 'Mapa signálu a hledání nejlepšího místa pro router',
    'shell.estimate': 'Orientační odhad',
    'shell.file': 'Soubor',
    'shell.file.tip': 'Otevřít, uložit, exportovat',
    'shell.keys.tip': 'Klávesové zkratky',
    'shell.theme.auto': 'Vzhled: automatický (podle systému) – kliknutím změníš',
    'shell.theme.light': 'Vzhled: světlý – kliknutím změníš',
    'shell.theme.dark': 'Vzhled: tmavý – kliknutím změníš',
    'shell.lang.aria': 'Jazyk',
    'shell.help': 'Nápověda',
    'shell.help.tip': 'Návod, jak změřit signál, a slovníček',
    'shell.loading': 'Načítám aplikaci…',
    'shell.toasts': 'Oznámení',
    'shell.view.error': 'Tuto část se nepodařilo načíst. Zkus stránku obnovit (F5). Tvoje data zůstala uložená.',

    // --- welcome --------------------------------------------------------------------------------------------------
    'welcome.title': 'Kde je tvůj Wi-Fi signál dobrý a kam dát router?',
    'welcome.lead': 'Nakresli svůj byt (nebo si vyzkoušej ukázkový) a hned uvidíš mapu signálu. Router pak jednoduše přetáhneš tam, kde bude signál nejlepší. Bez registrace, výpočty běží přímo v tomto prohlížeči.',
    'welcome.demo.t': 'Vyzkoušet ukázkový byt',
    'welcome.demo.b': 'Hotový byt s nastaveným routerem. Za pár vteřin uvidíš mapu signálu a můžeš si hrát.',
    'welcome.demo.go': 'Otevřít ukázku',
    'welcome.upload.t': 'Nahrát můj půdorys',
    'welcome.upload.b': 'Soubor SVG uložený z této aplikace, nebo obrázek (PNG, JPG, WebP), který si obkreslíš.',
    'welcome.upload.go': 'Vybrat soubor',
    'welcome.blank.t': 'Nakreslit od nuly',
    'welcome.blank.b': 'Prázdný plán a kreslicí nástroje. Hodí se, když máš byt v hlavě nebo na papíře.',
    'welcome.blank.go': 'Začít kreslit',
    'welcome.drop': 'Nebo sem přetáhni soubor',
    'welcome.dropHint': 'SVG uložené z této aplikace · PNG · JPG · WebP · do 8 MB',
    'welcome.open': 'Otevřít uložený projekt',
    'welcome.openHint': 'soubor .svg uložený dříve z této aplikace',
    'welcome.privacy': 'Výpočty běží v tomto prohlížeči a půdorys ani měření se nikam neodesílají. Síť se použije jen při testu rychlosti, který spustíš sám.',
    'welcome.tourOffer': 'Chceš krátkou prohlídku aplikace? Zabere půl minuty.',
    'welcome.tourStart': 'Spustit prohlídku',

    // --- file menu ------------------------------------------------------------------------------------------------
    'file.open': 'Otevřít soubor…',
    'file.saveSvg': 'Uložit projekt jako SVG',
    'file.savePlanPng': 'Uložit půdorys jako PNG',
    'file.saveMapPng': 'Uložit mapu signálu jako PNG',
    'file.demo': 'Ukázkový byt',
    'file.new': 'Nový prázdný plán',
    'file.theme': 'Změnit vzhled (světlý, tmavý, automatický)',
    'file.install': 'Nainstalovat jako aplikaci',
    'file.installed': 'Hotovo, aplikaci teď najdeš mezi ostatními aplikacemi.',
    'file.clear': 'Smazat uložená data v tomto prohlížeči',
    'file.autosave': 'Změny se průběžně ukládají v tomto prohlížeči. Pro zálohu nebo přenos jinam ulož projekt jako SVG.',
    'file.replace.t': 'Nahradit současný plán?',
    'file.replace.b': 'Současný půdorys bude nahrazen. Změnu půjde vrátit tlačítkem Zpět (Ctrl+Z).',
    'file.replace.ok': 'Nahradit',
    'file.clear.t': 'Smazat uložená data?',
    'file.clear.b': 'Z tohoto prohlížeče se smaže uložený projekt, podklad i měření. Stažené soubory zůstanou. Nejdřív si můžeš projekt uložit jako SVG.',
    'file.clear.ok': 'Smazat vše',
    'file.cleared': 'Uložená data jsou smazána.',
    'file.demoLoaded': 'Načten ukázkový byt.',
    'file.newCreated': 'Vytvořen prázdný plán. Začni kreslit místnosti.',
    'file.noViewPng': 'Tuto mapu zatím nejde exportovat.',

    // --- drag & drop ----------------------------------------------------------------------------------------------
    'drop.title': 'Pusť soubor sem',
    'drop.body': 'Půdorys uložený z této aplikace (SVG), nebo obrázek PNG, JPG či WebP.',

    // --- import / export / storage messages ----------------------------------------------------------------------
    'io.err.multiple': 'Nahraj prosím jen jeden soubor.',
    'io.err.empty': 'Soubor je prázdný.',
    'io.err.size': 'Soubor je příliš velký (nejvýš 8 MB).',
    'io.err.type': 'Tento typ souboru neumím otevřít. Použij SVG uložené z této aplikace, nebo obrázek PNG, JPG či WebP.',
    'io.err.corrupt': 'Soubor je poškozený nebo nemá správný formát půdorysu.',
    'io.err.svg': 'Soubor SVG se nepodařilo přečíst. Zkus ho znovu uložit, nebo ho nahraj jako obrázek PNG.',
    'io.err.svgComplex': 'SVG je příliš složité. Zjednoduš ho, nebo ho exportuj jako PNG.',
    'io.err.image': 'Obrázek se nepodařilo načíst. Zkus jiný soubor (PNG, JPG nebo WebP).',
    'io.err.imageDims': 'Obrázek má nepodporované rozměry.',
    'io.err.imageBig': 'Obrázek je příliš velký i po zmenšení. Zmenši ho a zkus to znovu.',
    'io.err.noEngine': 'Výpočetní část aplikace se nenačetla. Obnov stránku (F5).',
    'io.err.generic': 'Soubor se nepodařilo otevřít.',
    'io.err.export': 'Soubor se nepodařilo vytvořit.',
    'io.err.nothing': 'Není co ukládat, projekt je prázdný.',
    'io.err.local': 'Uložená data se nepodařilo načíst. Ponechal jsem jejich kopii a začínám s čistým plánem.',
    'io.warn.quota': 'Podklad je pro úložiště prohlížeče příliš velký a neuloží se. Zbytek projektu se ukládá. Ulož si projekt jako SVG, aby podklad nezmizel.',
    'io.err.quota': 'Projekt se nepodařilo uložit do prohlížeče (plné nebo zablokované úložiště). Ulož ho ručně jako SVG.',
    'io.ok.project': 'Půdorys „{name}“ načten: {rooms}, {walls}, {furniture}.',
    'io.ok.tracing': 'Obrázek je načten jako podklad. Obkresli místnosti a zdi.',
    'io.ok.background': 'Podklad nahrán.',
    'io.ok.saved': 'Projekt uložen jako {name} (najdeš ho ve složce Stažené soubory).',
    'io.ok.png': 'Obrázek uložen jako {name} (najdeš ho ve složce Stažené soubory).',
    'io.ok.migrated': 'Převzal jsem tvůj projekt ze starší verze aplikace.',
    'io.rooms.one': '{n} místnost',
    'io.rooms.few': '{n} místnosti',
    'io.rooms.other': '{n} místností',
    'io.walls.one': '{n} zeď',
    'io.walls.few': '{n} zdi',
    'io.walls.other': '{n} zdí',
    'io.furniture.one': '{n} kus nábytku',
    'io.furniture.few': '{n} kusy nábytku',
    'io.furniture.other': '{n} kusů nábytku',
    'io.defaultName': 'Můj byt',

    // --- help panel -----------------------------------------------------------------------------------------------
    'helpPanel.title': 'Nápověda',
    'helpPanel.how.t': 'Jak to funguje',
    'helpPanel.how.1.t': 'Nakresli nebo nahraj půdorys',
    'helpPanel.how.1.b': 'V režimu Půdorys nakresli místnosti, zdi a dveře, nebo nahraj obrázek a obkresli ho. Můžeš začít i ukázkovým bytem.',
    'helpPanel.how.2.t': 'Řekni, kde router stojí dnes',
    'helpPanel.how.2.b': 'V režimu Wi-Fi nastav dnešní polohu routeru a internetové přípojky. Se stavem „dnes“ se pak porovnává všechno ostatní.',
    'helpPanel.how.3.t': 'Zkoušej a hledej lepší místo',
    'helpPanel.how.3.b': 'Přetahuj router po bytě a sleduj, jak se mění mapa a pokrytí, nebo nech aplikaci najít nejlepší místo. Pro přesnější odhad přidej pár měření telefonem.',
    'helpPanel.tour.t': 'Prohlídka aplikace',
    'helpPanel.tour.b': 'Krátká prohlídka ukáže hlavní ovládací prvky.',
    'helpPanel.tour.btn': 'Spustit prohlídku',
    'helpPanel.shortcuts': 'Klávesové zkratky',
    'helpPanel.measure.t': 'Jak změřit signál',
    'helpPanel.measure.lead': 'Měření je volitelné, ale výrazně zpřesní odhad. Stačí 3 až 5 míst.',
    'helpPanel.glossary.t': 'Slovníček',
    'helpPanel.glossary.search': 'Hledat pojem…',
    'helpPanel.glossary.empty': 'Nic jsem nenašel.',
    'helpPanel.model.t': 'O modelu',
    'helpPanel.model.b': 'Mapa je ilustrativní model šíření signálu: síla klesá s logaritmem vzdálenosti a každá zeď nebo kus nábytku ubere několik dB, podobně jako v doporučení ITU-R P.1238 pro vnitřní prostory. Útlum záleží na pásmu: cihlová zeď ubere asi 7 dB na 2,4 GHz, 11 dB na 5 GHz a 13 dB na 6 GHz (podle měření NIST), proto 2,4 GHz doletí přes zdi nejdál. Model nepočítá odrazy ani rušení od sousedů, takže je to jen odhad. Po zadání měření se model pro dané pásmo posune tak, aby s nimi seděl.',
    'helpPanel.model.links': '<a href="https://www.itu.int/rec/R-REC-P.1238/en" target="_blank" rel="noopener noreferrer">ITU-R P.1238</a> · <a href="https://www.cisco.com/c/en/us/support/docs/wireless/catalyst-9800-series-wireless-controllers/221766-validate-wi-fi-throughput-testing-and.html" target="_blank" rel="noopener noreferrer">Cisco: ověření propustnosti Wi-Fi</a>',
    'helpPanel.footer': 'Výpočty běží v tomto prohlížeči. Půdorys, měření ani nastavení se nikam neodesílají, ukládají se jen do úložiště tvého prohlížeče. Síť se použije jen k načtení a aktualizaci aplikace a při testu rychlosti, který spustíš sám (servery Cloudflare).',
    'helpPanel.credits': '© 2026 Zizlik · MIT · <a href="https://github.com/Zizlik/WiFi-Heatmap-Architect" target="_blank" rel="noopener noreferrer">zdrojový kód na GitHubu</a>. Test rychlosti vychází z open-source měřáku Cloudflare (@cloudflare/speedtest), model šíření signálu z ITU-R P.1238.',
    'helpPanel.phone.t': 'Na telefonu',
    'helpPanel.phone.1': 'Otevři v telefonu <a href="https://zizlik.github.io/WiFi-Heatmap-Architect/" target="_blank" rel="noopener noreferrer">zizlik.github.io/WiFi-Heatmap-Architect</a>. Svůj projekt z počítače přeneseš jako soubor: na počítači Soubor → Uložit projekt jako SVG, v telefonu Soubor → Otevřít soubor.',
    'helpPanel.phone.2': 'Přidej si aplikaci na plochu: na Androidu v menu prohlížeče „Přidat na plochu“ (nebo „Nainstalovat aplikaci“), na iPhonu v Safari tlačítko Sdílet → „Přidat na plochu“. Pak se otevírá jako běžná aplikace.',
    'helpPanel.phone.3': 'Projdi se po bytě: v režimu Wi-Fi klepni do mapy tam, kde zrovna stojíš, a spusť test rychlosti. Po pár místech uvidíš, kde je internet nejrychlejší.',
    'helpPanel.phone.offline': 'Po prvním otevření funguje aplikace i bez internetu, jen test rychlosti potřebuje připojení. Novou verzi ti aplikace nabídne sama.',
    'helpPanel.speed.t': 'Test rychlosti a soukromí',
    'helpPanel.speed.1': 'Test se spustí jen tehdy, když klepneš na „Změřit rychlost teď“. Jinak aplikace nic neodesílá.',
    'helpPanel.speed.2': 'Stahuje a odesílá jen testovací data přes servery Cloudflare: rychlý test trvá asi 6 s a spotřebuje do 30 MB, důkladný asi 15 s a do 60 MB. Na mobilních datech pozor na limit.',
    'helpPanel.speed.3': 'Cloudflare uvidí tvou IP adresu, jako u každé webové stránky. Aplikace si z odpovědí nebere polohu ani jiné údaje a nic neposílá zpátky – zapamatuje si jen naměřené hodnoty (stahování, odesílání, odezvu) u bodu v mapě, a to v tvém prohlížeči.',
    'helpPanel.speed.4': 'Půdorys, měření ani nastavení nikdy neopustí tvoje zařízení. Bez internetu aplikace funguje dál, jen test rychlosti nepůjde spustit.',
    'helpPanel.speed.note': 'Test ukazuje rychlost internetu z daného místa, ne čistou rychlost Wi-Fi. Na porovnání míst mezi sebou to ale stačí.',
    'pwa.update': 'Je k dispozici nová verze aplikace.',
    'pwa.reload': 'Načíst',

    'measure.android.t': 'Android',
    'measure.android.b': 'Nainstaluj zdarma WiFiman (od firmy Ubiquiti) nebo Wi-Fi Analyzer. V seznamu sítí najdeš tu svou a u ní sílu signálu v dBm, například −58 dBm.',
    'measure.iphone.t': 'iPhone',
    'measure.iphone.b': 'iPhone v Nastavení hodnotu v dBm neukazuje. Nainstaluj zdarma aplikaci WiFiman (od firmy Ubiquiti), která signál tvé sítě v dBm zobrazí.',
    'measure.windows.t': 'Windows',
    'measure.windows.b': 'V příkazovém řádku zadej netsh wlan show interfaces a najdi řádek „Signal“. Je v procentech; přibližný převod je dBm ≈ % ÷ 2 − 100 (70 % je asi −65 dBm). V okně měření přepni jednotku na % (Windows) a převod proběhne sám.',
    'measure.mac.t': 'macOS',
    'measure.mac.b': 'Podrž klávesu Option a klikni na ikonu Wi-Fi v horní liště. U své sítě uvidíš hodnotu RSSI, například −55 dBm.',
    'measure.linux.t': 'Linux',
    'measure.linux.b': 'V terminálu spusť nmcli dev wifi. Sloupec SIGNAL je v procentech (převod jako u Windows). Přesné dBm ukáže příkaz iw dev wlan0 link.',
    'measure.speed.t': 'Rychlost internetu',
    'measure.speed.b': 'Rychlost změříš přímo v aplikaci: při přidávání měření spusť vestavěný test rychlosti (běží přes servery Cloudflare). Jde to i přes fast.com nebo speedtest.net. Měř stejným zařízením a na stejném pásmu jako signál a zapiš si stahování i odesílání.',
    'measure.rules.t': 'Zlatá pravidla měření',
    'measure.rules.b': 'Měř vždy se zařízením připojeným k hlavnímu routeru a s vypnutým druhým uzlem. Stůj tam, kde zařízení opravdu používáš (na půl metru přesně). Udělej 2 až 3 měření po sobě a zapiš prostřední hodnotu.',

    // --- shortcuts ------------------------------------------------------------------------------------------------
    'keys.title': 'Klávesové zkratky',
    'keys.or': 'nebo',
    'keys.here': 'tady jsi teď',
    'keys.notYet': 'Zkratky tohoto režimu se ukážou, jakmile ho poprvé otevřeš.',
    'keys.group.global': 'Všude',
    'keys.group.planner': 'Režim Wi-Fi',
    'keys.group.editor': 'Režim Půdorys',
    'keys.group.mouse': 'Myš a dotyk',
    'keys.note': 'Zkratky se vypínají, když píšeš do políčka. Na české klávesnici se číslice píší se Shiftem nebo na numerické klávesnici.',
    'keys.mouse.pan': 'Posun mapy: táhni prázdné místo (nebo prostřední tlačítko myši)',
    'keys.mouse.zoom': 'Přiblížení a oddálení: kolečko myši',
    'keys.mouse.pinch': 'Dotyková obrazovka: dva prsty přiblíží a posunou mapu',
    'keys.mouse.space': 'Mezerník + tažení: posun mapy, i když je zrovna vybraný nástroj',
    'keys.mouse.fit': 'Dvojklik na prázdné místo: zobrazit celý plán',
    'keys.modeEditor': 'Přepnout na Půdorys',
    'keys.modePlanner': 'Přepnout na Wi-Fi',
    'keys.sheet': 'Zobrazit tuto nápovědu ke zkratkám',
    'keys.helpPanel': 'Otevřít nápovědu',
    'keys.save': 'Uložit projekt jako SVG',
    'keys.open': 'Otevřít soubor…',
    'keys.undo': 'Zpět',
    'keys.redo': 'Znovu',
    'keys.esc': 'Zrušit / zavřít',
    'keys.zoomIn': 'Přiblížit',
    'keys.zoomOut': 'Oddálit',
    'keys.zoomFit': 'Zobrazit celý plán',
    'keys.nothingToUndo': 'Není co vracet.',
    'keys.nothingToRedo': 'Není co opakovat.',
    'keys.undone': 'Zpět: {label}',
    'keys.redone': 'Znovu: {label}',

    // --- tour -----------------------------------------------------------------------------------------------------
    'tour.step': 'Krok {n} z {total}',
    'tour.back': 'Zpět',
    'tour.next': 'Další',
    'tour.skip': 'Přeskočit',
    'tour.done': 'Hotovo',
    'tour.intro.t': 'Vítej!',
    'tour.intro.b': 'Za pár vteřin ti ukážu hlavní ovládání. Prohlídku můžeš kdykoli přerušit klávesou Esc a později ji znovu spustit v Nápovědě.',
    'tour.mode.t': 'Dva režimy',
    'tour.mode.b': 'Půdorys je na kreslení bytu, Wi-Fi na mapu signálu a hledání nejlepšího místa pro router. Přepínat můžeš i klávesami 1 a 2.',
    'tour.badge.t': 'Jen odhad',
    'tour.badge.b': 'Mapa je model, ne měření. Čím víc míst změříš telefonem, tím přesnější je. Otazníčky vysvětlují, co které číslo znamená.',
    'tour.file.t': 'Soubor',
    'tour.file.b': 'Tady otevřeš nebo uložíš projekt (SVG), uložíš obrázek mapy, nebo začneš znovu. Změny se ukládají do prohlížeče automaticky.',
    'tour.keys.t': 'Klávesové zkratky',
    'tour.keys.b': 'Většinu věcí zvládneš z klávesnice. Stiskni ? a uvidíš všechny zkratky, u ikon je najdeš i v bublině po najetí myší.',
    'tour.help.t': 'Nápověda',
    'tour.help.b': 'Najdeš tu návod, jak změřit signál, slovníček pojmů a můžeš prohlídku spustit znovu.',
    'tour.end.t': 'To je vše',
    'tour.end.b': 'Zkus přetáhnout router a sleduj mapu. Kdykoli si nebudeš vědět rady, klikni na malý otazník.',
  });

  I.add('en', {
    'app.description': 'Wi-Fi coverage planner: draw your floor plan, move the router and instantly see where the signal is good. Calculations run in your browser.',

    // --- common ---------------------------------------------------------------------------------------------------
    'ui.ok': 'OK',
    'ui.cancel': 'Cancel',
    'ui.close': 'Close',
    'ui.undo': 'Undo',
    'ui.delete': 'Delete',
    'ui.loading': 'Loading…',
    'ui.copy': 'Copy',

    // --- header ---------------------------------------------------------------------------------------------------
    'shell.skip': 'Skip to content',
    'shell.subtitle': 'Wi-Fi planner',
    'shell.brand.aria': 'WiFi Heatmap Architect',
    'shell.mode.aria': 'App mode',
    'shell.mode.plan': 'Floor plan',
    'shell.mode.plan.short': 'Plan',
    'shell.mode.wifi': 'Wi-Fi',
    'shell.mode.plan.tip': 'Draw and edit the floor plan',
    'shell.mode.wifi.tip': 'Signal map and finding the best router spot',
    'shell.estimate': 'Approximate estimate',
    'shell.file': 'File',
    'shell.file.tip': 'Open, save, export',
    'shell.keys.tip': 'Keyboard shortcuts',
    'shell.theme.auto': 'Theme: automatic (follows your system) – click to change',
    'shell.theme.light': 'Theme: light – click to change',
    'shell.theme.dark': 'Theme: dark – click to change',
    'shell.lang.aria': 'Language',
    'shell.help': 'Help',
    'shell.help.tip': 'Guide, how to measure signal, glossary',
    'shell.loading': 'Loading the app…',
    'shell.toasts': 'Notifications',
    'shell.view.error': 'This part could not be loaded. Try reloading the page (F5). Your data is still saved.',

    // --- welcome --------------------------------------------------------------------------------------------------
    'welcome.title': 'Where is your Wi-Fi signal good, and where should the router go?',
    'welcome.lead': 'Draw your home (or try the demo flat) and you instantly get a signal map. Then simply drag the router to where the signal is best. No sign-up, calculations run right in this browser.',
    'welcome.demo.t': 'Try the demo flat',
    'welcome.demo.b': 'A ready-made flat with a router in place. In a few seconds you see the signal map and can play with it.',
    'welcome.demo.go': 'Open the demo',
    'welcome.upload.t': 'Load my floor plan',
    'welcome.upload.b': 'An SVG saved from this app, or an image (PNG, JPG, WebP) that you trace over.',
    'welcome.upload.go': 'Choose a file',
    'welcome.blank.t': 'Draw from scratch',
    'welcome.blank.b': 'An empty plan and the drawing tools. Handy when you have your home in your head or on paper.',
    'welcome.blank.go': 'Start drawing',
    'welcome.drop': 'Or drop a file here',
    'welcome.dropHint': 'SVG saved from this app · PNG · JPG · WebP · up to 8 MB',
    'welcome.open': 'Open a saved project',
    'welcome.openHint': 'an .svg file you saved from this app earlier',
    'welcome.privacy': 'Calculations run in this browser and your floor plan and measurements are never sent anywhere. The network is used only for the speed test you start yourself.',
    'welcome.tourOffer': 'Would you like a short tour of the app? It takes half a minute.',
    'welcome.tourStart': 'Start the tour',

    // --- file menu ------------------------------------------------------------------------------------------------
    'file.open': 'Open file…',
    'file.saveSvg': 'Save project as SVG',
    'file.savePlanPng': 'Save floor plan as PNG',
    'file.saveMapPng': 'Save signal map as PNG',
    'file.demo': 'Demo flat',
    'file.new': 'New empty plan',
    'file.theme': 'Change appearance (light, dark, automatic)',
    'file.install': 'Install as an app',
    'file.installed': 'Done, you will now find the app with your other apps.',
    'file.clear': 'Delete saved data in this browser',
    'file.autosave': 'Changes are saved in this browser as you go. For a backup or to move to another computer, save the project as SVG.',
    'file.replace.t': 'Replace the current plan?',
    'file.replace.b': 'The current floor plan will be replaced. You can bring it back with Undo (Ctrl+Z).',
    'file.replace.ok': 'Replace',
    'file.clear.t': 'Delete saved data?',
    'file.clear.b': 'The saved project, background image and measurements will be deleted from this browser. Files you downloaded stay untouched. You can save the project as SVG first.',
    'file.clear.ok': 'Delete everything',
    'file.cleared': 'Saved data deleted.',
    'file.demoLoaded': 'Demo flat loaded.',
    'file.newCreated': 'Empty plan created. Start drawing rooms.',
    'file.noViewPng': 'This map cannot be exported yet.',

    // --- drag & drop ----------------------------------------------------------------------------------------------
    'drop.title': 'Drop the file here',
    'drop.body': 'A floor plan saved from this app (SVG), or a PNG, JPG or WebP image.',

    // --- import / export / storage messages ----------------------------------------------------------------------
    'io.err.multiple': 'Please drop just one file.',
    'io.err.empty': 'The file is empty.',
    'io.err.size': 'The file is too large (8 MB at most).',
    'io.err.type': 'I cannot open this type of file. Use an SVG saved from this app, or a PNG, JPG or WebP image.',
    'io.err.corrupt': 'The file is damaged or is not in the floor-plan format.',
    'io.err.svg': 'The SVG file could not be read. Try saving it again, or upload it as a PNG image.',
    'io.err.svgComplex': 'The SVG is too complex. Simplify it or export it as PNG.',
    'io.err.image': 'The image could not be loaded. Try another file (PNG, JPG or WebP).',
    'io.err.imageDims': 'The image has unsupported dimensions.',
    'io.err.imageBig': 'The image is too large even after shrinking. Make it smaller and try again.',
    'io.err.noEngine': 'The calculation part of the app did not load. Reload the page (F5).',
    'io.err.generic': 'The file could not be opened.',
    'io.err.export': 'The file could not be created.',
    'io.err.nothing': 'Nothing to save, the project is empty.',
    'io.err.local': 'The saved data could not be loaded. I kept a copy of it and am starting with a clean plan.',
    'io.warn.quota': 'The background image is too large for the browser storage and will not be saved. The rest of the project is saved. Save the project as SVG so the image is not lost.',
    'io.err.quota': 'The project could not be saved in the browser (storage full or blocked). Save it manually as SVG.',
    'io.ok.project': 'Floor plan "{name}" loaded: {rooms}, {walls}, {furniture}.',
    'io.ok.tracing': 'The image is loaded as a background. Trace the rooms and walls over it.',
    'io.ok.background': 'Background uploaded.',
    'io.ok.saved': 'Project saved as {name} (look in your Downloads folder).',
    'io.ok.png': 'Image saved as {name} (look in your Downloads folder).',
    'io.ok.migrated': 'I picked up your project from an older version of the app.',
    'io.rooms.one': '{n} room',
    'io.rooms.other': '{n} rooms',
    'io.walls.one': '{n} wall',
    'io.walls.other': '{n} walls',
    'io.furniture.one': '{n} piece of furniture',
    'io.furniture.other': '{n} pieces of furniture',
    'io.defaultName': 'My home',

    // --- help panel -----------------------------------------------------------------------------------------------
    'helpPanel.title': 'Help',
    'helpPanel.how.t': 'How it works',
    'helpPanel.how.1.t': 'Draw or load a floor plan',
    'helpPanel.how.1.b': 'In Floor plan mode draw rooms, walls and doors, or load an image and trace it. You can also start with the demo flat.',
    'helpPanel.how.2.t': 'Tell it where the router is today',
    'helpPanel.how.2.b': 'In Wi-Fi mode set today\'s position of the router and the internet inlet. Everything else is compared with the "today" situation.',
    'helpPanel.how.3.t': 'Try things and find a better spot',
    'helpPanel.how.3.b': 'Drag the router around your home and watch the map and coverage change, or let the app find the best spot. For a more accurate estimate add a few measurements with a phone.',
    'helpPanel.tour.t': 'App tour',
    'helpPanel.tour.b': 'A short tour shows the main controls.',
    'helpPanel.tour.btn': 'Start the tour',
    'helpPanel.shortcuts': 'Keyboard shortcuts',
    'helpPanel.measure.t': 'How to measure signal',
    'helpPanel.measure.lead': 'Measuring is optional but makes the estimate much more accurate. Three to five places are enough.',
    'helpPanel.glossary.t': 'Glossary',
    'helpPanel.glossary.search': 'Search a term…',
    'helpPanel.glossary.empty': 'Nothing found.',
    'helpPanel.model.t': 'About the model',
    'helpPanel.model.b': 'The map is an illustrative signal-propagation model: strength falls with the logarithm of distance, and every wall or piece of furniture takes off a few dB, similar to the ITU-R P.1238 recommendation for indoor spaces. The loss depends on the band: a brick wall takes off about 7 dB at 2.4 GHz, 11 dB at 5 GHz and 13 dB at 6 GHz (after NIST measurements), which is why 2.4 GHz reaches furthest through walls. The model ignores reflections and interference from neighbours, so it is only an estimate. When you enter measurements, the model for that band shifts to agree with them.',
    'helpPanel.model.links': '<a href="https://www.itu.int/rec/R-REC-P.1238/en" target="_blank" rel="noopener noreferrer">ITU-R P.1238</a> · <a href="https://www.cisco.com/c/en/us/support/docs/wireless/catalyst-9800-series-wireless-controllers/221766-validate-wi-fi-throughput-testing-and.html" target="_blank" rel="noopener noreferrer">Cisco: validating Wi-Fi throughput testing</a>',
    'helpPanel.footer': 'Calculations run in this browser. Your floor plan, measurements and settings are never sent anywhere, they are only stored in your browser\'s storage. The network is used only to load and update the app and for the speed test you start yourself (Cloudflare servers).',
    'helpPanel.credits': '© 2026 Zizlik · MIT · <a href="https://github.com/Zizlik/WiFi-Heatmap-Architect" target="_blank" rel="noopener noreferrer">source code on GitHub</a>. The speed test is modelled on Cloudflare\'s open-source speedtest (@cloudflare/speedtest), the signal model on ITU-R P.1238.',
    'helpPanel.phone.t': 'On your phone',
    'helpPanel.phone.1': 'Open <a href="https://zizlik.github.io/WiFi-Heatmap-Architect/" target="_blank" rel="noopener noreferrer">zizlik.github.io/WiFi-Heatmap-Architect</a> on your phone. To bring your project over, save it on the computer (File → Save project as SVG) and open that file on the phone (File → Open file).',
    'helpPanel.phone.2': 'Add the app to your home screen: on Android choose "Add to Home screen" (or "Install app") in the browser menu, on iPhone tap Share → "Add to Home Screen" in Safari. It then opens like any other app.',
    'helpPanel.phone.3': 'Walk around your home: in Wi-Fi mode tap the map where you are standing and run the speed test. After a few spots you will see where the internet is fastest.',
    'helpPanel.phone.offline': 'After the first visit the app also works without internet, only the speed test needs a connection. It offers new versions by itself.',
    'helpPanel.speed.t': 'Speed test and privacy',
    'helpPanel.speed.1': 'The test only runs when you tap "Measure speed now". Otherwise the app sends nothing.',
    'helpPanel.speed.2': 'It only downloads and uploads test data through Cloudflare\'s servers: the quick test takes about 6 s and up to 30 MB, the thorough one about 15 s and up to 60 MB. Mind your data limit on mobile data.',
    'helpPanel.speed.3': 'Cloudflare sees your IP address, as any website does. The app does not take your location or anything else from the replies and sends nothing back - it only remembers the measured values (download, upload, latency) at the spot on the map, in your browser.',
    'helpPanel.speed.4': 'Your floor plan, measurements and settings never leave your device. Without internet the app keeps working, only the speed test cannot start.',
    'helpPanel.speed.note': 'The test shows the internet speed from that spot, not the pure Wi-Fi speed. That is enough to compare places with each other.',
    'pwa.update': 'A new version of the app is available.',
    'pwa.reload': 'Reload',

    'measure.android.t': 'Android',
    'measure.android.b': 'Install the free WiFiman (by Ubiquiti) or Wi-Fi Analyzer. In the list of networks find yours and read its signal strength in dBm, for example −58 dBm.',
    'measure.iphone.t': 'iPhone',
    'measure.iphone.b': 'iPhone Settings does not show dBm. Install the free WiFiman app (by Ubiquiti), which displays your network\'s signal in dBm.',
    'measure.windows.t': 'Windows',
    'measure.windows.b': 'In a command prompt type netsh wlan show interfaces and find the "Signal" line. It is a percentage; the rough conversion is dBm ≈ % ÷ 2 − 100 (70% is about −65 dBm). In the measurement dialog switch the unit to % (Windows) and the conversion is done for you.',
    'measure.mac.t': 'macOS',
    'measure.mac.b': 'Hold the Option key and click the Wi-Fi icon in the menu bar. Next to your network you will see the RSSI value, for example −55 dBm.',
    'measure.linux.t': 'Linux',
    'measure.linux.b': 'In a terminal run nmcli dev wifi. The SIGNAL column is a percentage (convert as for Windows). For exact dBm use iw dev wlan0 link.',
    'measure.speed.t': 'Internet speed',
    'measure.speed.b': 'Measure speed right in the app: when you add a measurement, run the built-in speed test (it uses Cloudflare servers). fast.com or speedtest.net work too. Use the same device and the same band as for the signal and note both download and upload.',
    'measure.rules.t': 'Golden rules of measuring',
    'measure.rules.b': 'Always measure with the device connected to the main router and the second node switched off. Stand where you actually use the device (within half a metre). Take 2 to 3 measurements in a row and note the middle value.',

    // --- shortcuts ------------------------------------------------------------------------------------------------
    'keys.title': 'Keyboard shortcuts',
    'keys.or': 'or',
    'keys.here': 'you are here',
    'keys.notYet': 'The shortcuts of this mode appear once you open it for the first time.',
    'keys.group.global': 'Everywhere',
    'keys.group.planner': 'Wi-Fi mode',
    'keys.group.editor': 'Floor plan mode',
    'keys.group.mouse': 'Mouse and touch',
    'keys.note': 'Shortcuts are switched off while you type in a field. On some keyboard layouts digits need Shift or the numeric keypad.',
    'keys.mouse.pan': 'Pan the map: drag empty space (or the middle mouse button)',
    'keys.mouse.zoom': 'Zoom in and out: mouse wheel',
    'keys.mouse.pinch': 'Touch screen: two fingers zoom and pan the map',
    'keys.mouse.space': 'Space + drag: pan the map even while a tool is selected',
    'keys.mouse.fit': 'Double-click empty space: show the whole plan',
    'keys.modeEditor': 'Switch to Floor plan',
    'keys.modePlanner': 'Switch to Wi-Fi',
    'keys.sheet': 'Show this shortcut help',
    'keys.helpPanel': 'Open help',
    'keys.save': 'Save project as SVG',
    'keys.open': 'Open file…',
    'keys.undo': 'Undo',
    'keys.redo': 'Redo',
    'keys.esc': 'Cancel / close',
    'keys.zoomIn': 'Zoom in',
    'keys.zoomOut': 'Zoom out',
    'keys.zoomFit': 'Show the whole plan',
    'keys.nothingToUndo': 'Nothing to undo.',
    'keys.nothingToRedo': 'Nothing to redo.',
    'keys.undone': 'Undone: {label}',
    'keys.redone': 'Redone: {label}',

    // --- tour -----------------------------------------------------------------------------------------------------
    'tour.step': 'Step {n} of {total}',
    'tour.back': 'Back',
    'tour.next': 'Next',
    'tour.skip': 'Skip',
    'tour.done': 'Done',
    'tour.intro.t': 'Welcome!',
    'tour.intro.b': 'In a few seconds I will show you the main controls. You can stop the tour any time with the Esc key and start it again later from Help.',
    'tour.mode.t': 'Two modes',
    'tour.mode.b': 'Floor plan is for drawing your home, Wi-Fi is for the signal map and finding the best router spot. You can also switch with the keys 1 and 2.',
    'tour.badge.t': 'Just an estimate',
    'tour.badge.b': 'The map is a model, not a measurement. The more places you measure with a phone, the more accurate it gets. The little question marks explain what each number means.',
    'tour.file.t': 'File',
    'tour.file.b': 'Open or save your project (SVG), save the map as an image or start over here. Changes are saved in the browser automatically.',
    'tour.keys.t': 'Keyboard shortcuts',
    'tour.keys.b': 'You can do most things from the keyboard. Press ? to see all shortcuts, and hover an icon to see its key in the bubble.',
    'tour.help.t': 'Help',
    'tour.help.b': 'Here you find a guide to measuring signal, a glossary and a way to start the tour again.',
    'tour.end.t': 'That is all',
    'tour.end.b': 'Try dragging the router and watch the map. Whenever you are unsure, click a little question mark.',
  });
})();
