/* Strings of the built-in speed test (WH.speedtest) - Czech first (friendly "ty"), English second. */
WH.i18n.add('cs', {
  'speedtest.title': 'Test rychlosti internetu',
  'speedtest.go': 'Změřit rychlost teď',
  'speedtest.again': 'Změřit znovu',
  'speedtest.cancel': 'Zrušit test',
  'speedtest.retry': 'Zkusit znovu',
  'speedtest.mode.aria': 'Délka testu',
  'speedtest.mode.quick': 'Rychlý · 6 s',
  'speedtest.mode.full': 'Důkladný · 15 s',
  'speedtest.mode.quick.tip': 'Asi 6 sekund a do 30 MB dat',
  'speedtest.mode.full.tip': 'Asi 15 sekund a do 60 MB dat, výsledek je spolehlivější',
  'speedtest.phase.ping': 'Měřím odezvu…',
  'speedtest.phase.down': 'Stahování…',
  'speedtest.phase.up': 'Odesílání…',
  'speedtest.phase.done': 'Hotovo',
  'speedtest.gauge.aria': 'Průběh testu rychlosti',
  'speedtest.mbps': 'Mb/s',
  'speedtest.ms': 'ms',
  'speedtest.down': 'Stahování',
  'speedtest.up': 'Odesílání',
  'speedtest.ping': 'Odezva',
  'speedtest.jitter': 'Kolísání',
  'speedtest.meta.quick': 'Rychlý test přes Cloudflare',
  'speedtest.meta.full': 'Důkladný test přes Cloudflare',
  'speedtest.sr.start': 'Test rychlosti běží. Chvíli počkej, ať se telefon nehýbe.',
  'speedtest.sr.result': 'Hotovo: stahování {d} Mb/s, odesílání {u} Mb/s, odezva {p} ms.',
  'speedtest.cancelled': 'Test rychlosti je zrušený.',
  'speedtest.offline': 'Jsi offline. Test rychlosti potřebuje internet, zbytek aplikace funguje i bez něj.',
  'speedtest.cellular': 'Jsi na mobilních datech, ne na Wi-Fi. Test by měřil mobilní síť a spotřeboval data.',
  'speedtest.consent.t': 'Než změříš rychlost',
  'speedtest.consent.b': 'Test stáhne a odešle testovací data (~30–60 MB) přes servery Cloudflare. Tvůj půdorys ani měření se nikam neposílají. Na mobilních datech to může stát data.',
  'speedtest.consent.ok': 'Spustit test',
  'speedtest.consent.cancel': 'Zrušit',
  'speedtest.err.offline': 'Nejsi připojený k internetu. Připoj se k Wi-Fi a zkus to znovu.',
  'speedtest.err.blocked': 'Nepodařilo se spojit se serverem testu (speed.cloudflare.com). Možná ho blokuje síť, firewall nebo blokátor reklam.',
  'speedtest.err.timeout': 'Spojení je moc pomalé nebo se přerušilo, takže test nedoběhl. Zkus to znovu.',
  'speedtest.err.busy': 'Server testu je teď přetížený. Zkus to za chvíli znovu.',
  'speedtest.err.server': 'Server testu odpověděl chybou. Zkus to za chvíli znovu.',
  'help.speedtest.t': 'Test rychlosti internetu',
  'help.speedtest.b': 'Změří, jak rychle se z tohoto místa dostaneš na internet: stáhne a odešle pár megabajtů přes servery Cloudflare. Výsledek nikdy nepřekročí rychlost tvé internetové přípojky, takže čistou rychlost Wi-Fi neukáže – pro mapu ale stačí, protože porovnává místa mezi sebou.',
  'help.speedtest.more': 'Rychlý test trvá asi 6 s (do 30 MB dat), důkladný asi 15 s (do 60 MB) a je spolehlivější. Měř vždycky stejným zařízením a stůj při tom v klidu. Na čistou rychlost Wi-Fi by byl potřeba vlastní testovací server doma v síti (třeba LibreSpeed) – to je možné rozšíření do budoucna.',
});

WH.i18n.add('en', {
  'speedtest.title': 'Internet speed test',
  'speedtest.go': 'Measure speed now',
  'speedtest.again': 'Measure again',
  'speedtest.cancel': 'Cancel test',
  'speedtest.retry': 'Try again',
  'speedtest.mode.aria': 'Test length',
  'speedtest.mode.quick': 'Quick · 6 s',
  'speedtest.mode.full': 'Thorough · 15 s',
  'speedtest.mode.quick.tip': 'About 6 seconds and up to 30 MB of data',
  'speedtest.mode.full.tip': 'About 15 seconds and up to 60 MB of data, a more reliable result',
  'speedtest.phase.ping': 'Measuring latency…',
  'speedtest.phase.down': 'Download…',
  'speedtest.phase.up': 'Upload…',
  'speedtest.phase.done': 'Done',
  'speedtest.gauge.aria': 'Speed test progress',
  'speedtest.mbps': 'Mbps',
  'speedtest.ms': 'ms',
  'speedtest.down': 'Download',
  'speedtest.up': 'Upload',
  'speedtest.ping': 'Ping',
  'speedtest.jitter': 'Jitter',
  'speedtest.meta.quick': 'Quick test via Cloudflare',
  'speedtest.meta.full': 'Thorough test via Cloudflare',
  'speedtest.sr.start': 'Speed test running. Wait a moment and keep the phone still.',
  'speedtest.sr.result': 'Done: download {d} Mbps, upload {u} Mbps, ping {p} ms.',
  'speedtest.cancelled': 'Speed test cancelled.',
  'speedtest.offline': 'You are offline. The speed test needs the internet; the rest of the app works without it.',
  'speedtest.cellular': 'You are on mobile data, not Wi-Fi. The test would measure the mobile network and use up data.',
  'speedtest.consent.t': 'Before you measure',
  'speedtest.consent.b': 'The test downloads and uploads test data (~30–60 MB) through Cloudflare’s servers. Your floor plan and measurements are never sent anywhere. On mobile data this can cost you data.',
  'speedtest.consent.ok': 'Start the test',
  'speedtest.consent.cancel': 'Cancel',
  'speedtest.err.offline': 'You are not connected to the internet. Connect to Wi-Fi and try again.',
  'speedtest.err.blocked': 'Could not reach the test server (speed.cloudflare.com). Your network, a firewall or an ad blocker may be blocking it.',
  'speedtest.err.timeout': 'The connection is too slow or dropped, so the test did not finish. Try again.',
  'speedtest.err.busy': 'The test server is busy right now. Try again in a moment.',
  'speedtest.err.server': 'The test server answered with an error. Try again in a moment.',
  'help.speedtest.t': 'Internet speed test',
  'help.speedtest.b': 'Measures how fast you reach the internet from this spot: it downloads and uploads a few megabytes through Cloudflare’s servers. The result can never exceed your internet plan, so it does not show the pure Wi-Fi speed – but that is fine for the map, which compares places with each other.',
  'help.speedtest.more': 'The quick test takes about 6 s (up to 30 MB of data), the thorough one about 15 s (up to 60 MB) and is more reliable. Always measure with the same device and stand still. The pure Wi-Fi speed would need your own test server at home (such as LibreSpeed) – a possible future option.',
});
