/* Planner strings for measuring with the phone (SPEC 6.2): speed-only points, the bottom sheet, the measuring mode. */
(function () {
  'use strict';
  const I = globalThis.WH.i18n;

  I.add('cs', {
    'planner.m.signalOpt': 'Síla signálu (nepovinné)',
    'planner.m.wifiman': 'Sílu signálu zjistíš v aplikaci WiFiman (Ubiquiti) — nebo ji vynech a změř jen rychlost.',
    'planner.m.speedNow': 'Rychlost internetu',
    'planner.m.speedManual': 'Rychlost zadaná ručně',
    'planner.m.speedOr': 'Nebo zadej rychlost ručně',
    'planner.m.place': 'Místo',
    'planner.m.errNeedOne': 'Zadej sílu signálu, nebo změř rychlost (stahování i odesílání).',
    'planner.m.errNeedBoth': 'Bez síly signálu je potřeba stahování i odesílání.',
    'planner.m.savedSpeed': 'Měření uloženo: ↓ {d} / ↑ {u} Mb/s.',
    'planner.m.sigEstimated': 'signál odhadnut',
    'planner.m.sigEstimatedV': 'signál odhadnut (≈ {v})',
    'planner.m.ping': 'ping {v} ms',
    'planner.m.pingJitter': 'ping {p} ms, kolísání {j} ms',
    'planner.mk.measAriaSpeed': 'Měření {name}: stahování {d}, odesílání {u} Mb/s, {band}, signál odhadnut. Enter upraví, Delete smaže.',
    'planner.mk.speedLabel': '↓ {d} / ↑ {u}',
    'planner.tip.modelOnly': 'model tu čeká {v}',
    'planner.mm.enter': 'Měřicí režim',
    'planner.mm.enter.tip': 'Měření telefonem: velká mapa, klepneš, kde stojíš, a změříš rychlost',
    'planner.mm.tap': 'Klepni do mapy, kde stojíš',
    'planner.mm.count.one': '{n} měření',
    'planner.mm.count.few': '{n} měření',
    'planner.mm.count.other': '{n} měření',
    'planner.mm.done': 'Hotovo',
    'planner.mm.on': 'Měřicí režim: klepni do mapy na místo, kde stojíš. Obrazovka zůstane rozsvícená.',
    'planner.mm.off': 'Měřicí režim skončil.',
    'planner.mm.saved': 'Uloženo. Přejdi na další místo a klepni znovu.',
    'help.whereSignal.t': 'Kde zjistím sílu signálu?',
    'help.whereSignal.b': 'Prohlížeč v telefonu sílu Wi-Fi signálu (dBm) zjistit neumí. Ukáže ti ji zdarma aplikace WiFiman od Ubiquiti (Android i iPhone), na Windows příkaz netsh wlan show interfaces (v procentech).',
    'help.whereSignal.more': 'Signál klidně vynech: stačí změřit rychlost a aplikace si sílu signálu v tom místě odhadne z modelu. Kalibraci mapy ale zpřesní jen měření se signálem.',
  });

  I.add('en', {
    'planner.m.signalOpt': 'Signal strength (optional)',
    'planner.m.wifiman': 'You can read the signal strength in the WiFiman app (Ubiquiti) — or leave it out and measure just the speed.',
    'planner.m.speedNow': 'Internet speed',
    'planner.m.speedManual': 'Speed entered by hand',
    'planner.m.speedOr': 'Or enter the speed by hand',
    'planner.m.place': 'Place',
    'planner.m.errNeedOne': 'Enter the signal strength, or measure the speed (download and upload).',
    'planner.m.errNeedBoth': 'Without a signal strength both download and upload are needed.',
    'planner.m.savedSpeed': 'Measurement saved: ↓ {d} / ↑ {u} Mbps.',
    'planner.m.sigEstimated': 'signal estimated',
    'planner.m.sigEstimatedV': 'signal estimated (≈ {v})',
    'planner.m.ping': 'ping {v} ms',
    'planner.m.pingJitter': 'ping {p} ms, jitter {j} ms',
    'planner.mk.measAriaSpeed': 'Measurement {name}: download {d}, upload {u} Mbps, {band}, signal estimated. Enter edits, Delete removes.',
    'planner.mk.speedLabel': '↓ {d} / ↑ {u}',
    'planner.tip.modelOnly': 'the model expects {v} here',
    'planner.mm.enter': 'Measuring mode',
    'planner.mm.enter.tip': 'Measure with your phone: big map, tap where you stand and test the speed',
    'planner.mm.tap': 'Tap the map where you are standing',
    'planner.mm.count.one': '{n} measurement',
    'planner.mm.count.other': '{n} measurements',
    'planner.mm.done': 'Done',
    'planner.mm.on': 'Measuring mode: tap the map where you are standing. The screen stays on.',
    'planner.mm.off': 'Measuring mode ended.',
    'planner.mm.saved': 'Saved. Walk to the next spot and tap again.',
    'help.whereSignal.t': 'Where do I find the signal strength?',
    'help.whereSignal.b': 'A phone browser cannot read the Wi-Fi signal strength (dBm). The free WiFiman app by Ubiquiti shows it (Android and iPhone); on Windows the command netsh wlan show interfaces shows it in percent.',
    'help.whereSignal.more': 'Feel free to leave the signal out: measuring the speed is enough and the app estimates the signal at that spot from the model. Only measurements with a signal make the map’s calibration more accurate, though.',
  });
})();
