/* Planner strings: "Prvotní měření" calibration wizard, the fitted model in plain words and the whole-home throughput
 * (SPEC 9). Czech is informal ("ty"), friendly and plain. */
WH.i18n.add('cs', {
  'planner.cw.title': 'Prvotní měření',
  'planner.cw.open': 'Prvotní měření',
  'planner.cw.resume': 'Pokračovat ({d} / {n})',
  'planner.cw.startGuide': 'Spustit průvodce',
  'planner.cw.close': 'Zavřít průvodce (postup zůstane uložený)',
  'planner.cw.step': 'Krok {i} ze 3',
  'planner.cw.back': 'Zpět',
  'planner.cw.opened': 'Průvodce prvotním měřením je otevřený.',
  'planner.cw.closed': 'Průvodce je zavřený, postup zůstal uložený.',
  'planner.cw.cta': 'Nevíš, kde měřit? Průvodce ti ukáže pár míst a podle nich doladí sílu routeru i útlum zdí.',

  // step 1: where the router stands
  'planner.cw.r.t': 'Kde stojí router?',
  'planner.cw.r.b': 'Měření patří k místu, kde router doopravdy stojí. Sedí červené R na mapě?',
  'planner.cw.r.yes': 'Ano, stojí tam',
  'planner.cw.r.no': 'Když ne: přetáhni R na správné místo (nebo klikni na podlahu) a pak zvol Router stojí tady.',
  'planner.cw.r.moved': 'Červené R je teď na zkušebním místě, {d} od dnešního.',
  'planner.cw.r.back': 'Vrátit R na dnešní místo',
  'planner.cw.r.here': 'Router stojí tady',
  'planner.cw.r.node': 'Další přístupové body během měření vypni – model teď počítá jen s hlavním routerem.',

  // step 2: band
  'planner.cw.b.t': 'Pro které pásmo ti mám ukázat místa?',
  'planner.cw.b.b': 'Místa k měření se liší podle pásma. K pásmu se ale nemusíš připojovat natvrdo: když router přepne sám (band steering, Wi-Fi 7), každé měření se započítá pro pásmo, na kterém opravdu vzniklo – na PC ho zjistí pomocník, na telefonu ho vybereš.',
  'planner.cw.b.fromWifi': 'Podle údajů o Wi-Fi z měření „{name}“ je to {b} GHz.',
  'planner.cw.b.unknown': 'Nevíš? Nech 5 GHz – na tom je doma většina zařízení.',
  'planner.cw.m.otherBand': 'Router tě přepnul na {b} GHz – měření se započítá pro to pásmo.',
  'planner.cw.b.go': 'Ukázat místa k měření',

  // step 3: measuring the spots
  'planner.cw.m.progress': 'Změřeno {d} z {n}',
  'planner.cw.m.walk': 'Dojdi k bodu {i} na mapě, klepni na něj (nebo kamkoli poblíž) a zmáčkni Změřit vše.',
  'planner.cw.m.walkHere': 'Stojíš u bodu {i}? Zmáčkni Změřit vše.',
  'planner.cw.m.all': 'Změřit vše',
  'planner.cw.m.running': 'Měřím bod {i}… průběh vidíš hned pod tímhle.',
  'planner.cw.m.skip': 'Přeskočit',
  'planner.cw.m.own': 'Vlastní místo',
  'planner.cw.m.pick': 'Klepni do mapy tam, kde stojíš.',
  'planner.cw.m.pickKey': 'Bez myši: zmáčkni Enter na mapě a místo se přidá doprostřed mapy.',
  'planner.cw.m.cancel': 'Zrušit',
  'planner.cw.m.finish': 'Vyhodnotit',
  'planner.cw.m.list': 'Všechna místa',
  'planner.cw.m.notSpot': 'Tohle místo není mezi navrženými.',
  'planner.cw.m.addHere': 'Přidat jako vlastní místo',
  'planner.cw.m.speedOnly': 'Bod {i} má jen rychlost. Sílu routeru doladím jen podle signálu – doplň ho v dBm (třeba z aplikace WiFiman).',
  'planner.cw.m.addSig': 'Doplnit signál',
  'planner.cw.m.tipPhone': 'Tip: na telefonu ukáže sílu signálu aplikace WiFiman od Ubiquiti. Číslo v dBm zapiš do okénka měření.',
  'planner.cw.m.tipPc': 'Tip: na počítači zjistí signál Pomocník pro Wi-Fi, nebo ho vložíš z příkazu v Info o zařízení.',
  'planner.cw.m.saved': 'Bod {i} je změřený. Další je bod {j}.',
  'planner.cw.m.savedLast': 'Bod {i} je změřený. To byl poslední.',
  'planner.cw.m.selected': 'Vybraný bod {i}: {label}.',
  'planner.cw.m.added': 'Přidal jsem bod {i} tam, kde stojíš.',
  'planner.cw.m.noSpots': 'Na tomhle půdorysu jsem nenašel vhodná místa. Přidej vlastní.',
  'planner.cw.m.allDone': 'Všechna místa jsou změřená. Zmáčkni Vyhodnotit, nebo přidej vlastní místo.',
  'planner.cw.m.sig': 'Signál (nepovinné)',
  'planner.cw.m.savedToast': 'Bod {i} uložený: {s}',

  // spot kinds
  'planner.cw.k.near': 'kousek od routeru',
  'planner.cw.k.sameRoom': 'na druhé straně místnosti s routerem',
  'planner.cw.k.open': 'dál od routeru, bez zdi v cestě',
  'planner.cw.k.oneWall': 'za jednou zdí',
  'planner.cw.k.twoWalls': 'za dvěma a více zdmi',
  'planner.cw.k.far': 'nejvzdálenější místo',
  'planner.cw.k.own': 'tvoje místo',
  'planner.cw.k.spot': 'místo k měření',
  'planner.cw.st.done': 'změřeno',
  'planner.cw.st.skipped': 'přeskočeno',
  'planner.cw.st.next': 'na řadě',
  'planner.cw.st.speedOnly': 'jen rychlost',
  'planner.cw.pin': 'Bod {i}: {room}, {kind}',
  'planner.cw.pinState': '{label} ({state})',

  // step 4: done
  'planner.cw.d.t': 'Hotovo!',
  'planner.cw.d.b': 'Tohle jsem z tvých měření zjistil:',
  'planner.cw.d.more': 'Změřit další místo',
  'planner.cw.d.close': 'Zavřít',

  // the fitted model in plain words (Result card + the wizard's last step)
  'planner.cw.sec': 'Model podle tvých měření',
  'planner.cw.band': '{b} GHz',
  'planner.cw.str.up': 'Tvůj router je o {d} silnější, než model předpokládal.',
  'planner.cw.str.down': 'Tvůj router je o {d} slabší, než model předpokládal.',
  'planner.cw.str.same': 'Tvůj router je zhruba tak silný, jak model předpokládal.',
  'planner.cw.walls.more': 'Zdi u tebe tlumí asi o {p} víc, než model čekal.',
  'planner.cw.walls.less': 'Zdi u tebe tlumí asi o {p} míň, než model čekal.',
  'planner.cw.walls.same': 'Zdi tlumí zhruba tolik, kolik model čekal.',
  'planner.cw.decay.faster': 'Se vzdáleností signál slábne o něco rychleji, než model čekal.',
  'planner.cw.decay.slower': 'Se vzdáleností signál slábne o něco pomaleji, než model čekal.',
  'planner.cw.acc': 'Model teď sedí na ±{a} dB (dřív ±{b} dB).',
  'planner.cw.accOnly': 'Model teď sedí na ±{a} dB.',
  'planner.cw.method.full.one': 'Doladil jsem sílu routeru, útlum zdí i úbytek se vzdáleností ({n} měření).',
  'planner.cw.method.full.few': 'Doladil jsem sílu routeru, útlum zdí i úbytek se vzdáleností ({n} měření).',
  'planner.cw.method.full.other': 'Doladil jsem sílu routeru, útlum zdí i úbytek se vzdáleností ({n} měření).',
  'planner.cw.method.offset.one': 'Zatím jsem doladil jen sílu routeru ({n} měření). Se 4 a více měřeními v různých místnostech doladím i zdi.',
  'planner.cw.method.offset.few': 'Zatím jsem doladil jen sílu routeru ({n} měření). Se 4 a více měřeními v různých místnostech doladím i zdi.',
  'planner.cw.method.offset.other': 'Zatím jsem doladil jen sílu routeru ({n} měření). Se 4 a více měřeními v různých místnostech doladím i zdi.',
  'planner.cw.nextT': 'Co dál',
  'planner.cw.next.outlier': 'Měření „{name}“ se od modelu liší o {d} – zkus ho zopakovat.',
  'planner.cw.next.rough': 'Některá měření moc nesedí. Zkontroluj polohu routeru, měřítko a zdi v půdorysu.',
  'planner.cw.next.more.one': 'Změř ještě {n} místo za zdí a doladím i útlum zdí.',
  'planner.cw.next.more.few': 'Změř ještě {n} místa za zdmi a doladím i útlum zdí.',
  'planner.cw.next.more.other': 'Změř ještě {n} míst za zdmi a doladím i útlum zdí.',
  'planner.cw.next.good': 'Model sedí. Teď zkus Najít nejlepší místo (F).',
  'planner.cw.next.off': 'Mapa teď ukazuje výchozí model. Přepni na Podle měření.',
  'planner.cw.cmp': 'Mapa',
  'planner.cw.cmp.fit': 'Podle měření',
  'planner.cw.cmp.def': 'Výchozí model',
  'planner.cw.cmp.aria': 'Který model mapa ukazuje',
  'planner.cw.reset': 'Vrátit výchozí model',
  'planner.cw.resetDone': 'Model je zase výchozí.',
  'planner.cw.apply': 'Upravit model podle měření',
  'planner.cw.applyDone': 'Model je upravený podle tvých měření.',
  'planner.cw.needSig': 'K úpravě modelu potřebuju aspoň 2 měření se silou signálu (dBm) na stejném pásmu.',
  'planner.undo.fit': 'úprava modelu podle měření',
  'planner.undo.fitReset': 'vrácení výchozího modelu',

  // whole-home throughput (SPEC 9)
  'planner.tp.title': 'Propustnost bytu',
  'planner.tp.lead': 'Cíl {d}/{u} Mb/s splníš na {v} plochy.',
  'planner.tp.today': 'S routerem na dnešním místě je to {v}.',
  'planner.tp.rooms': 'Typická rychlost v místnostech',
  'planner.tp.weak': 'Nejslabší místo',
  'planner.tp.weakAria': 'Ukázat nejslabší místo na mapě: {room}, stahování {d}, odesílání {u} Mb/s',
  'planner.tp.weakShown': 'Nejslabší místo: {room}, stahování {d}, odesílání {u} Mb/s.',
  'planner.tp.planLimit': 'Na {v} plochy tě brzdí internetový tarif, ne Wi-Fi.',
  'planner.tp.upBlocks': 'Stahování by stačilo, cíl nesplníš kvůli odesílání: typicky ↑ {v} Mb/s místo {t}. Je cíl pro odesílání reálný? Upravíš ho v kartě Rychlost.',
  'planner.tp.downBlocks': 'Odesílání by stačilo, cíl nesplníš kvůli stahování: typicky ↓ {v} Mb/s místo {t}.',
  'planner.tp.planBelow': 'Tvůj tarif ({d}/{u} Mb/s) je pomalejší než cíl, takže ho nesplníš nikde – ať je Wi-Fi jakákoli. Cíl můžeš snížit v kartě Rychlost.',
  'planner.tp.planUnknown': 'Zadej rychlost tarifu v kartě Rychlost – poznám pak, kde brzdí internet a kde Wi-Fi.',
  'planner.tp.basis.one': 'Odhad z {n} testu rychlosti na {b}.',
  'planner.tp.basis.few': 'Odhad ze {n} testů rychlosti na {b}.',
  'planner.tp.basis.other': 'Odhad z {n} testů rychlosti na {b}.',
  'planner.tp.fitted': 'Signál podle upraveného modelu.',
  'planner.tp.chip': '{v} plochy splní cíl',
  'planner.tp.chipAria': 'Propustnost bytu: cíl {d}/{u} Mb/s splněn na {v} plochy',
  'planner.tp.unknownRoom': 'neznámá',
  'planner.tp.weakUnknown': 'pod tvým nejslabším testem',

  // getting started + measurements card
  'planner.start.calib': 'Prvotní měření (doporučeno)',
  'planner.start.calib.b': 'Změř signál na pár místech, průvodce ti je ukáže. Mapa se podle toho doladí.',
  'planner.start.calib.go': 'Začít',

  // hints
  'planner.adv.fitNote': 'Sílu routeru, útlum zdí a úbytek signálu se vzdáleností teď ladí tvá měření. Posuvníky níž jsou jen výchozí odhad, ze kterého ladění vychází.',
  'planner.adv.fitNoteOffset': 'Sílu routeru teď ladí tvá měření (posun mapy o pár dB). Posuvníky níž platí dál.',
  'help.calibWizard.t': 'Prvotní měření',
  'help.calibWizard.b': 'Průvodce ti na mapě ukáže 4 až 6 míst: kousek od routeru, za jednou zdí, za více zdmi a to nejvzdálenější. Na každém zmáčkneš Změřit vše a aplikace podle výsledků doladí sílu tvého routeru a útlum zdí.',
  'help.calibWizard.more': 'Router musí stát na svém dnešním místě. Pásmo hlídat nemusíš: každé měření se uloží s pásmem, na kterém vzniklo (na PC ho zjistí pomocník, na telefonu ho vybereš), a model se zpřesní pro každé pásmo zvlášť. Průvodce můžeš kdykoli zavřít, postup zůstane uložený.',
  'help.homeSpeed.t': 'Propustnost bytu',
  'help.homeSpeed.b': 'Odhad, jakou rychlost internetu dostaneš v různých částech bytu: z tvých testů rychlosti a mapy signálu. „Splníš na 82 % plochy“ znamená, že na 82 % podlahy dosáhneš cílové rychlosti z karty Rychlost.',
  'help.homeSpeed.more': 'Když tě všude brzdí tarif, rychlejší Wi-Fi nepomůže. Nejslabší místo si můžeš ukázat na mapě.',
});

WH.i18n.add('en', {
  'planner.cw.title': 'First measurement',
  'planner.cw.open': 'First measurement',
  'planner.cw.resume': 'Continue ({d} / {n})',
  'planner.cw.startGuide': 'Start the guide',
  'planner.cw.close': 'Close the guide (your progress is kept)',
  'planner.cw.step': 'Step {i} of 3',
  'planner.cw.back': 'Back',
  'planner.cw.opened': 'The first-measurement guide is open.',
  'planner.cw.closed': 'The guide is closed, your progress is kept.',
  'planner.cw.cta': 'Not sure where to measure? The guide shows you a few spots and uses them to tune your router’s strength and the wall losses.',

  'planner.cw.r.t': 'Where is the router?',
  'planner.cw.r.b': 'Measurements belong to the place where the router really stands. Is the red R on the map right?',
  'planner.cw.r.yes': 'Yes, it is there',
  'planner.cw.r.no': 'If not: drag the R to the right place (or click the floor) and choose The router is here.',
  'planner.cw.r.moved': 'The red R is on a trial position now, {d} from today’s.',
  'planner.cw.r.back': 'Put the R back to today’s place',
  'planner.cw.r.here': 'The router is here',
  'planner.cw.r.node': 'Switch the extra access points off while measuring – the model only counts the main router now.',

  'planner.cw.b.t': 'Which band should I show the spots for?',
  'planner.cw.b.b': 'The spots to measure depend on the band. You do not have to pin your device to it, though: when the router switches bands by itself (band steering, Wi-Fi 7), every measurement counts for the band it was really taken on – on a PC the helper finds it out, on a phone you pick it.',
  'planner.cw.b.fromWifi': 'The Wi-Fi details of the measurement “{name}” say {b} GHz.',
  'planner.cw.b.unknown': 'Not sure? Keep 5 GHz – most devices at home use it.',
  'planner.cw.m.otherBand': 'The router switched you to {b} GHz – the measurement counts for that band.',
  'planner.cw.b.go': 'Show the spots to measure',

  'planner.cw.m.progress': 'Measured {d} of {n}',
  'planner.cw.m.walk': 'Walk to spot {i} on the map, tap it (or anywhere nearby) and press Measure everything.',
  'planner.cw.m.walkHere': 'Standing at spot {i}? Press Measure everything.',
  'planner.cw.m.all': 'Measure everything',
  'planner.cw.m.running': 'Measuring spot {i}… the progress is right below.',
  'planner.cw.m.skip': 'Skip',
  'planner.cw.m.own': 'My own spot',
  'planner.cw.m.pick': 'Tap the map where you are standing.',
  'planner.cw.m.pickKey': 'Without a mouse: press Enter on the map and the spot goes to the middle of the map.',
  'planner.cw.m.cancel': 'Cancel',
  'planner.cw.m.finish': 'Show the result',
  'planner.cw.m.list': 'All spots',
  'planner.cw.m.notSpot': 'This place is not one of the suggested spots.',
  'planner.cw.m.addHere': 'Add it as my own spot',
  'planner.cw.m.speedOnly': 'Spot {i} only has a speed. Your router’s strength is tuned from the signal only – add it in dBm (e.g. from the WiFiman app).',
  'planner.cw.m.addSig': 'Add the signal',
  'planner.cw.m.tipPhone': 'Tip: on a phone the free WiFiman app by Ubiquiti shows the signal. Type the dBm number into the measurement panel.',
  'planner.cw.m.tipPc': 'Tip: on a computer the Wi-Fi helper reads the signal, or paste it from the command in Device info.',
  'planner.cw.m.saved': 'Spot {i} is measured. Next is spot {j}.',
  'planner.cw.m.savedLast': 'Spot {i} is measured. That was the last one.',
  'planner.cw.m.selected': 'Selected spot {i}: {label}.',
  'planner.cw.m.added': 'Added spot {i} where you are standing.',
  'planner.cw.m.noSpots': 'No suitable spots were found on this floor plan. Add your own.',
  'planner.cw.m.allDone': 'Every spot is measured. Press Show the result, or add your own spot.',
  'planner.cw.m.sig': 'Signal (optional)',
  'planner.cw.m.savedToast': 'Spot {i} saved: {s}',

  'planner.cw.k.near': 'close to the router',
  'planner.cw.k.sameRoom': 'across the router’s room',
  'planner.cw.k.open': 'farther from the router, no wall in between',
  'planner.cw.k.oneWall': 'behind one wall',
  'planner.cw.k.twoWalls': 'behind two or more walls',
  'planner.cw.k.far': 'the farthest spot',
  'planner.cw.k.own': 'your own spot',
  'planner.cw.k.spot': 'spot to measure',
  'planner.cw.st.done': 'measured',
  'planner.cw.st.skipped': 'skipped',
  'planner.cw.st.next': 'next',
  'planner.cw.st.speedOnly': 'speed only',
  'planner.cw.pin': 'Spot {i}: {room}, {kind}',
  'planner.cw.pinState': '{label} ({state})',

  'planner.cw.d.t': 'Done!',
  'planner.cw.d.b': 'Here is what your measurements told me:',
  'planner.cw.d.more': 'Measure another spot',
  'planner.cw.d.close': 'Close',

  'planner.cw.sec': 'The model from your measurements',
  'planner.cw.band': '{b} GHz',
  'planner.cw.str.up': 'Your router is {d} stronger than the model assumed.',
  'planner.cw.str.down': 'Your router is {d} weaker than the model assumed.',
  'planner.cw.str.same': 'Your router is about as strong as the model assumed.',
  'planner.cw.walls.more': 'Your walls block about {p} more than the model expected.',
  'planner.cw.walls.less': 'Your walls block about {p} less than the model expected.',
  'planner.cw.walls.same': 'Your walls block about as much as the model expected.',
  'planner.cw.decay.faster': 'The signal fades a bit faster with distance than the model expected.',
  'planner.cw.decay.slower': 'The signal fades a bit slower with distance than the model expected.',
  'planner.cw.acc': 'The model now fits within ±{a} dB (before ±{b} dB).',
  'planner.cw.accOnly': 'The model now fits within ±{a} dB.',
  'planner.cw.method.full.one': 'I tuned the router’s strength, the wall losses and the fading with distance ({n} measurement).',
  'planner.cw.method.full.other': 'I tuned the router’s strength, the wall losses and the fading with distance ({n} measurements).',
  'planner.cw.method.offset.one': 'So far I only tuned the router’s strength ({n} measurement). With 4 or more measurements in different rooms I can tune the walls too.',
  'planner.cw.method.offset.other': 'So far I only tuned the router’s strength ({n} measurements). With 4 or more measurements in different rooms I can tune the walls too.',
  'planner.cw.nextT': 'What next',
  'planner.cw.next.outlier': 'The measurement “{name}” differs from the model by {d} – try measuring it again.',
  'planner.cw.next.rough': 'Some measurements do not fit well. Check the router position, the scale and the walls of the floor plan.',
  'planner.cw.next.more.one': 'Measure {n} more spot behind a wall and I can tune the wall losses too.',
  'planner.cw.next.more.other': 'Measure {n} more spots behind walls and I can tune the wall losses too.',
  'planner.cw.next.good': 'The model fits. Now try Find the best spot (F).',
  'planner.cw.next.off': 'The map shows the default model now. Switch to From measurements.',
  'planner.cw.cmp': 'Map',
  'planner.cw.cmp.fit': 'From measurements',
  'planner.cw.cmp.def': 'Default model',
  'planner.cw.cmp.aria': 'Which model the map shows',
  'planner.cw.reset': 'Back to the default model',
  'planner.cw.resetDone': 'The model is the default one again.',
  'planner.cw.apply': 'Tune the model from my measurements',
  'planner.cw.applyDone': 'The model is tuned to your measurements.',
  'planner.cw.needSig': 'To tune the model I need at least 2 measurements with a signal strength (dBm) on the same band.',
  'planner.undo.fit': 'tuning the model from measurements',
  'planner.undo.fitReset': 'back to the default model',

  'planner.tp.title': 'Whole-home throughput',
  'planner.tp.lead': 'The {d}/{u} Mbps target is met on {v} of the area.',
  'planner.tp.today': 'With the router at today’s place it is {v}.',
  'planner.tp.rooms': 'Typical speed in the rooms',
  'planner.tp.weak': 'Weakest spot',
  'planner.tp.weakAria': 'Show the weakest spot on the map: {room}, download {d}, upload {u} Mbps',
  'planner.tp.weakShown': 'Weakest spot: {room}, download {d}, upload {u} Mbps.',
  'planner.tp.planLimit': 'On {v} of the area your internet plan is the limit, not the Wi-Fi.',
  'planner.tp.upBlocks': 'Download would be fine – the upload misses the target: typically ↑ {v} Mbps instead of {t}. Is the upload target realistic? You can change it in the Speed card.',
  'planner.tp.downBlocks': 'Upload would be fine – the download misses the target: typically ↓ {v} Mbps instead of {t}.',
  'planner.tp.planBelow': 'Your internet plan ({d}/{u} Mbps) is slower than the target, so no spot can meet it – however good the Wi-Fi. You can lower the target in the Speed card.',
  'planner.tp.planUnknown': 'Enter your plan’s speed in the Speed card – then I can tell where the internet and where the Wi-Fi is the limit.',
  'planner.tp.basis.one': 'Estimated from {n} speed test on {b}.',
  'planner.tp.basis.other': 'Estimated from {n} speed tests on {b}.',
  'planner.tp.fitted': 'Signal from the tuned model.',
  'planner.tp.chip': '{v} of the area meets the target',
  'planner.tp.chipAria': 'Whole-home throughput: the {d}/{u} Mbps target is met on {v} of the area',
  'planner.tp.unknownRoom': 'unknown',
  'planner.tp.weakUnknown': 'below your weakest test',

  'planner.start.calib': 'First measurement (recommended)',
  'planner.start.calib.b': 'Measure the signal at a few spots, the guide shows you where. The map is tuned to match.',
  'planner.start.calib.go': 'Start',

  'planner.adv.fitNote': 'Your measurements now tune the router strength, the wall loss and how fast the signal fades with distance. The sliders below are only the starting point the tuning begins from.',
  'planner.adv.fitNoteOffset': 'Your measurements now tune the router strength (the map moves by a few dB). The sliders below still apply.',
  'help.calibWizard.t': 'First measurement',
  'help.calibWizard.b': 'The guide shows you 4 to 6 spots on the map: close to the router, behind one wall, behind more walls and the farthest one. At each one you press Measure everything and the app uses the results to tune your router’s strength and the wall losses.',
  'help.calibWizard.more': 'The router must stand at its usual place. You do not need to watch the band: every measurement is saved with the band it was taken on (on a PC the helper finds it out, on a phone you pick it) and the model is tuned for each band separately. You can close the guide at any time; your progress is kept.',
  'help.homeSpeed.t': 'Whole-home throughput',
  'help.homeSpeed.b': 'An estimate of the internet speed you get in different parts of your home, from your speed tests and the signal map. “Met on 82 % of the area” means that on 82 % of the floor you reach the target speed from the Speed card.',
  'help.homeSpeed.more': 'If your internet plan is the limit everywhere, faster Wi-Fi will not help. You can show the weakest spot on the map.',
});
