/* Planner (Wi-Fi view) strings, cs + en. */
(function () {
  'use strict';
  const I = globalThis.WH.i18n;

  I.add('cs', {
    'planner.q.excellent': 'Výborný',
    'planner.q.veryGood': 'Velmi dobrý',
    'planner.q.good': 'Dobrý',
    'planner.q.weak': 'Slabý',
    'planner.q.veryWeak': 'Velmi slabý',
    'planner.q.unusable': 'Nepoužitelný',
    'planner.band.b24': '2,4',
    'planner.band.b5': '5',
    'planner.band.b6': '6',
    'planner.band.aria': 'Pásmo Wi-Fi',
    'planner.band.tip24': 'Pásmo 2,4 GHz: největší dosah, zdmi projde nejlépe, ale je pomalejší',
    'planner.band.tip5': 'Pásmo 5 GHz: rychlé, zdi ho tlumí víc',
    'planner.band.tip6': 'Pásmo 6 GHz: nejrychlejší, zdi ho tlumí nejvíc',
    'planner.ghz': 'GHz',
    'planner.mbps': 'Mb/s',
    'planner.gbps': 'Gb/s',
    'planner.unit.m': 'm',
    'planner.err.range': 'Zadej číslo od {min} do {max}.',

    'planner.view.aria': 'Co mapa ukazuje',
    'planner.view.signal': 'Signál',
    'planner.view.signal.tip': 'Signál: síla Wi-Fi v každém místě',
    'planner.view.speed': 'Rychlost',
    'planner.view.speed.tip': 'Rychlost: odhad Mb/s podle tvých měření',
    'planner.view.diff': 'Změna proti dnešku',
    'planner.view.diffShort': 'Změna',
    'planner.view.diff.tip': 'Změna proti dnešku: kde se signál zlepší a kde zhorší',
    'planner.tool.router': 'Router',
    'planner.tool.router.tip': 'Router: klik na podlahu ho přesune, značky jdou táhnout',
    'planner.tool.measure': 'Měřit',
    'planner.tool.measure.tip': 'Klikni na mapě, kde měříš: zapíšeš signál nebo změříš rychlost',
    'planner.tool.layers': 'Vrstvy',
    'planner.tool.layers.tip': 'Co je na mapě vidět',
    'planner.tool.measureOn': 'Měření: klikni na mapě na místo, kde měříš.',
    'planner.tool.routerOn': 'Nástroj router.',
    'planner.layers.title': 'Vrstvy mapy',
    'planner.tools.aria': 'Nástroje mapy',
    'planner.layers.ranges': 'Čáry dosahu',
    'planner.layers.walls': 'Zdi a dveře',
    'planner.layers.furniture': 'Nábytek',
    'planner.layers.labels': 'Názvy místností',
    'planner.layers.values': 'Průměr v dBm',
    'planner.layers.rangesOn': 'Čáry dosahu zapnuté.',
    'planner.layers.rangesOff': 'Čáry dosahu vypnuté.',
    'planner.map.aria': 'Mapa signálu. Šipkami posuneš router, se Shiftem o metr.',
    'planner.side.aria': 'Výsledky a nastavení Wi-Fi',

    'planner.mk.routerLetter': 'R',
    'planner.mk.router': 'Router (zkušební poloha)',
    'planner.mk.routerTip': 'Přetáhni ho jinam a mapa se hned přepočítá.',
    'planner.mk.today': 'Dnešní poloha routeru',
    'planner.mk.todayShort': 'Dnes',
    'planner.mk.todayTip': 'Tady router stojí dnes. Všechno se porovnává s tímto místem.',
    'planner.mk.inlet': 'Přípojka internetu',
    'planner.mk.inletTip': 'Kudy do bytu vchází internet. Přetáhni ji na správné místo.',
    'planner.mk.routerAria': 'Router, zkušební poloha: {room}, {v}. Posuň šipkami.',
    'planner.mk.todayAria': 'Dnešní poloha routeru: {room}. Enter nabídne návrat.',
    'planner.mk.inletAria': 'Přípojka internetu. Posuň šipkami.',
    'planner.mk.measAria': 'Měření {name}: {v}, {band}. Enter upraví, Delete smaže.',
    'planner.today.confirmT': 'Změnit dnešní polohu?',
    'planner.today.confirmB': 'Uložená měření ({n}) patří k původní poloze routeru, proto se smažou.',
    'planner.today.confirmOk': 'Změnit a smazat měření',
    'planner.sr.router': 'Router: {room}, pokrytí {cov}.',
    'planner.snapped': 'Některé značky po úpravě půdorysu stály mimo místnosti, posunul jsem je dovnitř.',

    'planner.tip.outside': 'mimo místnosti',
    'planner.tip.delta': 'oproti dnešku {d}',
    'planner.tip.weakBackhaul': 'Přístupový bod, který tu vysílá, má slabé spojení.',
    'planner.tip.speedNone': 'Na odhad rychlosti chybí měření.',
    'planner.tip.speedWeak': 'Tak slabý signál jsi neměřil, rychlost nevím.',
    'planner.tip.model': 'model {v} (rozdíl {d})',

    'planner.noplan.t': 'Ještě tu není půdorys',
    'planner.noplan.b': 'Nakresli byt v režimu Půdorys, nebo otevři ukázkový byt v nabídce Soubor.',
    'planner.noplan.go': 'Nakreslit půdorys',

    'planner.opt.running': 'Hledám nejlepší místo…',
    'planner.opt.cancelled': 'Hledání zrušeno.',
    'planner.opt.failed': 'Hledání se nepovedlo.',
    'planner.opt.stale': 'Během hledání se plán změnil. Zkus to znovu.',
    'planner.opt.already': 'Router už stojí na nejlepším místě, které jsem našel.',
    'planner.opt.found': 'Nejlepší místo: {room}, pokrytí {a} → {b}.',
    'planner.opt.bySpeed': 'Hledal jsem podle cílové rychlosti.',

    'planner.legend.signal': 'Síla signálu · {b}',
    'planner.legend.bad': 'Špatný',
    'planner.legend.thr': 'dobrý od {v}',
    'planner.legend.diff': 'Změna proti dnešku',
    'planner.legend.worse': 'Horší',
    'planner.legend.same': 'Beze změny',
    'planner.legend.better': 'Lepší',
    'planner.legend.speed': 'Rychlost vůči cíli {d}/{u} Mb/s',
    'planner.legend.below': 'Pod cílem',
    'planner.legend.meets': 'Splní cíl',
    'planner.legend.unknown': 'šedá = slabší signál než při tvém nejslabším měření, rychlost tu nevím',
    'planner.legend.rangeAt': 'čáry při {v}',
    'planner.export.title': 'Pokrytí {b} · {target} {v}',
    'planner.export.diff': 'Změna proti dnešku {b} · {target} {a} → {v}',
    'planner.export.speed': 'Rychlost {b} · {target}: cíl splněn na {v}',

    'planner.m.title': 'Zpřesnit měřením',
    'planner.m.intro': 'Na pár místech změř telefonem rychlost (test je přímo tady) nebo sílu signálu. Mapa se podle toho doladí.',
    'planner.m.add': 'Přidat měření',
    'planner.m.calibrate': 'Použít měření ke kalibraci',
    'planner.m.deviceGoal': 'Zařízení',
    'planner.m.edit': 'Upravit měření',
    'planner.m.empty': 'Zatím žádné měření.',
    'planner.m.residual': 'rozdíl {d}',
    'planner.m.outlier': 'nesedí s modelem ({d}), nepoužito – zkus změřit znovu',
    'planner.m.remind': 'Měř s routerem na dnešním místě a s vypnutými dalšími přístupovými body. Pak klikni na mapě na místo měření.',
    'planner.m.deleted': 'Měření „{name}“ je smazané.',
    'planner.m.tooMany': 'Víc než 500 měření uložit nejde.',
    'planner.m.ph': 'např. −63',
    'planner.m.dbm': 'dBm',
    'planner.m.pct': '% (Windows)',
    'planner.m.unit': 'Jednotka',
    'planner.m.down': 'Stahování (Mb/s)',
    'planner.m.up': 'Odesílání (Mb/s)',
    'planner.m.notToday': 'Mapa teď ukazuje zkušební polohu routeru. Měř tam, kde router doma opravdu stojí – měření se uloží k dnešní poloze.',
    'planner.m.showToday': 'Ukázat dnešní polohu',
    'planner.m.odd': 'Výsledek se hodně liší od předchozích měření (nebo je odesílání mnohem rychlejší než stahování). Zkus test zopakovat, ideálně Důkladný.',
    'planner.m.nodeOn': 'Při měření vypni další přístupové body – měření se porovnává s dneškem bez nich.',
    'planner.m.errValue': 'Zadej sílu signálu, třeba −63 (dBm) nebo 70 (%).',
    'planner.m.errPct': 'Procenta musí být od 0 do 100.',
    'planner.m.errRange': 'Signál musí být mezi −100 a −20 dBm.',
    'planner.m.errSpeed': 'Rychlost musí být od 0 do 10 000 Mb/s.',
    'planner.m.defName': 'Měření {n}',
    'planner.m.saved': 'Měření uloženo: {v}.',
    'planner.m.band': 'Pásmo (GHz)',
    'planner.m.name': 'Název',
    'planner.m.device': 'Zařízení',
    'planner.m.save': 'Uložit',
    'planner.m.newTitle': 'Nové měření',
    'planner.m.editTitle': 'Upravit měření',
    'planner.cal.title': 'Jak model sedí',
    'planner.cal.suspicious': '{b}: měření se od modelu liší o {d}. Zkontroluj pásmo, měřítko a zdi.',
    'planner.cal.ok.one': '{b}: model upraven o {d}, sedí na ±{rms} dB ({n} měření).',
    'planner.cal.ok.few': '{b}: model upraven o {d}, sedí na ±{rms} dB ({n} měření).',
    'planner.cal.ok.other': '{b}: model upraven o {d}, sedí na ±{rms} dB ({n} měření).',
    'planner.cal.single': '{b}: model upraven o {d} (zatím 1 měření, přidej další).',
    'planner.cal.fallback': 'Počítám se všemi zařízeními.',
    'planner.cal.off': 'Kalibrace je vypnutá.',

    'planner.start.title': 'Začínáme',
    'planner.start.hide': 'Skrýt průvodce',
    'planner.start.plan': 'Půdorys',
    'planner.start.plan.b': 'Nakresli nebo nahraj svůj byt.',
    'planner.start.plan.go': 'Kreslit',
    'planner.start.today': 'Kde je dnes router',
    'planner.start.today.b': 'Sedí červené R s tím, kde router doma stojí? Když ne, přetáhni ho a zvol Označit jako dnešní polohu.',
    'planner.start.today.go': 'Ano, sedí',
    'planner.start.move': 'Zkus přesunout router',
    'planner.start.move.b': 'Přetáhni červené R nebo klikni na podlahu a sleduj výsledek.',
    'planner.start.bands': 'Která pásma router vysílá',
    'planner.start.bands.b': 'Většina routerů vysílá 2,4 a 5 GHz. Máš Wi-Fi 6E nebo Wi-Fi 7? Zaškrtni i 6 GHz.',
    'planner.start.bands.go': 'Zkontrolovat',
    'planner.start.measure': '(Volitelně) Změř signál nebo rychlost',
    'planner.start.measure.b': 'Pár měření telefonem mapu zpřesní. Stačí i jen test rychlosti.',
    'planner.start.measure.go': 'Měřit',

    'planner.res.title': 'Výsledek',
    'planner.res.target': 'Cíl',
    'planner.res.all': 'Celý byt',
    'planner.res.allFloor': 'Celé patro',
    'planner.res.coverage': 'Pokrytí dobrým signálem',
    'planner.res.avg': 'Průměrný signál',
    'planner.res.p10': 'Nejslabších 10 %',
    'planner.res.rooms': 'Místnosti',
    'planner.res.roomsHint': 'kliknutím vybereš cíl',
    'planner.res.noplan': 'Nejdřív nakresli půdorys.',
    'planner.res.today': 'Dnes',
    'planner.res.now': 'Teď',
    'planner.res.pts': '{n} p. b.',
    'planner.res.same': 'beze změny',
    'planner.res.s.great': 'Téměř všude je dobrý signál.',
    'planner.res.s.good': 'Většina plochy má dobrý signál.',
    'planner.res.s.half': 'Dobrý signál má jen asi polovina plochy.',
    'planner.res.s.poor': 'Většina plochy má slabý signál.',
    'planner.res.s.tryMove': 'Zkus router posunout.',
    'planner.res.s.tryFind': 'Zkus Najít nejlepší místo (F).',
    'planner.res.s.atBest': 'Tohle je nejlepší místo, které aplikace našla.',
    'planner.res.s.addAp': 'Pro víc pokrytí zvaž další přístupový bod.',
    'planner.res.s.better': 'Zkušební poloha je lepší než dnešní.',
    'planner.res.s.worse': 'Zkušební poloha je horší než dnešní.',
    'planner.res.speed': 'Cíl {d}/{u} Mb/s splníš na {v} plochy.',
    'planner.res.speedKnown': 'Rychlost znám pro {v} plochy.',
    'planner.res.speedNone': 'Na odhad rychlosti chybí měření.',
    'planner.res.roomAria': '{name}: pokrytí {cov}, průměr {v}. Nastavit jako cíl.',
    'planner.res.excluded': '(nepočítá se do celého bytu)',
    'planner.res.live': 'Pokrytí {cov}, průměrný signál {v}.',

    'planner.router.title': 'Router',
    'planner.router.find': 'Najít nejlepší místo',
    'planner.router.back': 'Vrátit na dnešní místo',
    'planner.router.backHere': 'Vrátit router sem',
    'planner.router.mark': 'Označit jako dnešní polohu',
    'planner.router.allowed': 'Kam ho můžu dát?',
    'planner.router.anywhere': 'Kamkoli',
    'planner.router.inletT': 'Přípojka internetu',
    'planner.router.inlet': 'vzdušnou čarou {d} · kabel zhruba {lo}–{hi} m',
    'planner.router.trial': 'Zkušební poloha: {room}, {d} od dnešního místa.',
    'planner.router.atToday': 'Router stojí na dnešním místě ({room}). Přetáhni ho a porovnej.',
    'planner.router.alreadyToday': 'Router už je na dnešním místě.',
    'planner.router.markedSame': 'Díky, dnešní poloha je potvrzená.',
    'planner.router.marked': 'Hotovo, tohle je teď dnešní poloha routeru.',

    'planner.node.mode': 'Typ',
    'planner.node.ap_cable': 'Přístupový bod po kabelu',
    'planner.node.mesh_cable': 'Mesh po kabelu',
    'planner.node.mesh_wifi': 'Mesh přes Wi-Fi',
    'planner.node.repeater': 'Opakovač',
    'planner.node.bands': 'Vysílá na pásmech',
    'planner.node.power': 'Výkon proti routeru',
    'planner.node.bhBand': 'Spojuje se přes pásmo',
    'planner.node.bhThr': 'Nejslabší dobré spojení',
    'planner.node.oneBand': 'Aspoň jedno pásmo musí zůstat zapnuté.',

    'planner.speed.title': 'Rychlost',
    'planner.speed.intro': 'Pro pohled Rychlost: jakou rychlost chceš a co zvládne tvoje přípojka.',
    'planner.speed.tDown': 'Cíl stahování',
    'planner.speed.tUp': 'Cíl odesílání',
    'planner.speed.reserve': 'Rezerva',
    'planner.speed.wanDown': 'Tarif: stahování',
    'planner.speed.wanUp': 'Tarif: odesílání',
    'planner.speed.link': 'Přípojka a kabel',
    'planner.speed.wanPort': 'Port WAN routeru',
    'planner.speed.ontPort': 'Port optické krabičky',
    'planner.speed.wanLink': 'Sjednaná rychlost linky',
    'planner.speed.cat': 'Kategorie kabelu',
    'planner.speed.len': 'Délka kabelu',
    'planner.speed.unknown': 'Nevím',
    'planner.speed.noLimit': 'Strop přípojky zatím neznám, zadej tarif.',
    'planner.speed.limit': 'Po odečtení rezervy {r} nejvýš: stahování {d}, odesílání {u} Mb/s.',
    'planner.speed.cant': 'S tímto tarifem a rezervou cílovou rychlost nesplníš.',
    'planner.speed.cat5': 'Kabel Cat5 zvládne nejvýš 100 Mb/s.',
    'planner.speed.long': 'Kabel delší než 100 m může zpomalovat.',
    'planner.speed.show': 'Ukázat pohled Rychlost',

    'planner.adv.title': 'Pokročilé',
    'planner.adv.width': 'Skutečná šířka bytu',
    'planner.adv.model': 'Model šíření signálu',
    'planner.adv.near': 'Signál 1 m od routeru (5 GHz)',
    'planner.adv.decay': 'Slábnutí se vzdáleností',
    'planner.adv.wall': 'Výchozí útlum zdi (při 5 GHz)',
    'planner.adv.thr': 'Hranice dobrého signálu',
    'planner.adv.range': 'Hranice čar dosahu',
    'planner.adv.rooms': 'Co počítat do „Celý byt“',
    'planner.adv.palette': 'Paleta pro barvoslepé',
    'planner.adv.reset': 'Obnovit výchozí model',
    'planner.adv.resetDone': 'Model je zpět na výchozích hodnotách.',
    'planner.adv.lastRoom': 'Aspoň jedna místnost se musí počítat.',

    'planner.keys.router': 'Nástroj router',
    'planner.keys.measure': 'Měřit (zapnout / vypnout)',
    'planner.keys.band': 'Další pásmo (2,4 → 5 → 6 GHz → Auto)',
    'planner.keys.view': 'Další pohled (signál → rychlost → změna)',
    'planner.keys.ranges': 'Čáry dosahu',
    'planner.keys.find': 'Najít nejlepší místo',
    'planner.keys.today': 'Router zpět na dnešní místo',
    'planner.keys.arrows': 'Posunout router o 25 cm (Shift = 1 m), když je vybraná mapa',
    'planner.keys.enter': 'Uložit měření (s nástrojem Měřit: nové měření uprostřed mapy)',
    'planner.keys.esc': 'Zrušit tažení, hledání nebo nástroj Měřit',

    'planner.tour.map.t': 'Přetáhni router',
    'planner.tour.map.b': 'Červené R je router. Přetáhni ho, nebo klikni na podlahu, a mapa se hned přepočítá. Z klávesnice ho posuneš šipkami.',
    'planner.tour.result.t': 'Výsledek',
    'planner.tour.result.b': 'Kolik procent bytu má dobrý signál dnes a po přesunu. Kliknutím na místnost z ní uděláš cíl.',
    'planner.tour.find.t': 'Najít nejlepší místo',
    'planner.tour.find.b': 'Aplikace vyzkouší stovky poloh a router přesune na tu nejlepší. Stačí stisknout F.',
    'planner.tour.meas.t': 'Zpřesni odhad měřením',
    'planner.tour.meas.b': 'Změř signál telefonem na pár místech a zapiš ho (M). Mapa se podle toho doladí.',

    'planner.undo.router': 'přesun routeru',
    'planner.undo.ceilFit': 'úprava stropu podle měření',
    'planner.undo.today': 'přesun dnešní polohy',
    'planner.undo.inlet': 'přesun přípojky',
    'planner.undo.node': 'změna přístupového bodu',
    'planner.undo.measMove': 'přesun měření',
    'planner.undo.back': 'návrat routeru na dnešní místo',
    'planner.undo.markToday': 'nová dnešní poloha',
    'planner.undo.measAdd': 'nové měření',
    'planner.undo.measEdit': 'úprava měření',
    'planner.undo.measDel': 'smazání měření',
    'planner.undo.optimize': 'nejlepší místo',
    'planner.undo.target': 'změna cíle',
    'planner.undo.allowed': 'kam může router',
    'planner.undo.device': 'změna zařízení',
    'planner.undo.speed': 'nastavení rychlosti',
    'planner.undo.scale': 'změna měřítka',
    'planner.undo.model': 'úprava modelu',
    'planner.undo.resetModel': 'obnovení modelu',
    'planner.undo.rooms': 'výběr místností',
  });

  I.add('en', {
    'planner.q.excellent': 'Excellent',
    'planner.q.veryGood': 'Very good',
    'planner.q.good': 'Good',
    'planner.q.weak': 'Weak',
    'planner.q.veryWeak': 'Very weak',
    'planner.q.unusable': 'Unusable',
    'planner.band.b24': '2.4',
    'planner.band.b5': '5',
    'planner.band.b6': '6',
    'planner.band.aria': 'Wi-Fi band',
    'planner.band.tip24': '2.4 GHz band: longest range, best through walls, but slower',
    'planner.band.tip5': '5 GHz band: fast, walls weaken it more',
    'planner.band.tip6': '6 GHz band: fastest, walls weaken it the most',
    'planner.ghz': 'GHz',
    'planner.mbps': 'Mbps',
    'planner.gbps': 'Gbps',
    'planner.unit.m': 'm',
    'planner.err.range': 'Enter a number from {min} to {max}.',

    'planner.view.aria': 'What the map shows',
    'planner.view.signal': 'Signal',
    'planner.view.signal.tip': 'Signal: Wi-Fi strength everywhere',
    'planner.view.speed': 'Speed',
    'planner.view.speed.tip': 'Speed: Mbps estimate from your measurements',
    'planner.view.diff': 'Change vs today',
    'planner.view.diffShort': 'Change',
    'planner.view.diff.tip': 'Change vs today: where the signal gets better or worse',
    'planner.tool.router': 'Router',
    'planner.tool.router.tip': 'Router: click the floor to move it, drag any marker',
    'planner.tool.measure': 'Measure',
    'planner.tool.measure.tip': 'Click the map where you measure: enter the signal or run a speed test',
    'planner.tool.layers': 'Layers',
    'planner.tool.layers.tip': 'What the map shows',
    'planner.tool.measureOn': 'Measuring: click the map where you are measuring.',
    'planner.tool.routerOn': 'Router tool.',
    'planner.layers.title': 'Map layers',
    'planner.tools.aria': 'Map tools',
    'planner.layers.ranges': 'Range lines',
    'planner.layers.walls': 'Walls and doors',
    'planner.layers.furniture': 'Furniture',
    'planner.layers.labels': 'Room names',
    'planner.layers.values': 'Average in dBm',
    'planner.layers.rangesOn': 'Range lines on.',
    'planner.layers.rangesOff': 'Range lines off.',
    'planner.map.aria': 'Signal map. Arrow keys move the router, with Shift by one metre.',
    'planner.side.aria': 'Wi-Fi results and settings',

    'planner.mk.routerLetter': 'R',
    'planner.mk.router': 'Router (trial position)',
    'planner.mk.routerTip': 'Drag it somewhere else and the map updates instantly.',
    'planner.mk.today': "Router's position today",
    'planner.mk.todayShort': 'Today',
    'planner.mk.todayTip': 'This is where the router is today. Everything is compared with this spot.',
    'planner.mk.inlet': 'Internet inlet',
    'planner.mk.inletTip': 'Where the internet enters the flat. Drag it to the right spot.',
    'planner.mk.routerAria': 'Router, trial position: {room}, {v}. Move with arrow keys.',
    'planner.mk.todayAria': "Router's position today: {room}. Press Enter to go back there.",
    'planner.mk.inletAria': 'Internet inlet. Move with arrow keys.',
    'planner.mk.measAria': 'Measurement {name}: {v}, {band}. Enter edits, Delete removes.',
    'planner.today.confirmT': "Change today's position?",
    'planner.today.confirmB': 'Your saved measurements ({n}) belong to the old router position, so they will be deleted.',
    'planner.today.confirmOk': 'Change and delete measurements',
    'planner.sr.router': 'Router: {room}, coverage {cov}.',
    'planner.snapped': 'After the floor-plan edit some markers were outside the rooms, so I moved them inside.',

    'planner.tip.outside': 'outside the rooms',
    'planner.tip.delta': '{d} vs today',
    'planner.tip.weakBackhaul': 'The access point serving here has a weak link.',
    'planner.tip.speedNone': 'Measurements are needed for a speed estimate.',
    'planner.tip.speedWeak': 'You have not measured a signal this weak, speed unknown.',
    'planner.tip.model': 'model {v} (difference {d})',

    'planner.noplan.t': 'There is no floor plan yet',
    'planner.noplan.b': 'Draw your flat in Floor plan mode, or open the demo flat from the File menu.',
    'planner.noplan.go': 'Draw the floor plan',

    'planner.opt.running': 'Looking for the best spot…',
    'planner.opt.cancelled': 'Search cancelled.',
    'planner.opt.failed': 'The search failed.',
    'planner.opt.stale': 'The plan changed during the search. Please try again.',
    'planner.opt.already': 'The router already stands on the best spot I found.',
    'planner.opt.found': 'Best spot: {room}, coverage {a} → {b}.',
    'planner.opt.bySpeed': 'Searched by the speed target.',

    'planner.legend.signal': 'Signal strength · {b}',
    'planner.legend.bad': 'Poor',
    'planner.legend.thr': 'good from {v}',
    'planner.legend.diff': 'Change vs today',
    'planner.legend.worse': 'Worse',
    'planner.legend.same': 'Same',
    'planner.legend.better': 'Better',
    'planner.legend.speed': 'Speed vs target {d}/{u} Mbps',
    'planner.legend.below': 'Below target',
    'planner.legend.meets': 'Meets target',
    'planner.legend.unknown': 'grey = weaker signal than your weakest measurement, speed unknown',
    'planner.legend.rangeAt': 'lines at {v}',
    'planner.export.title': 'Coverage {b} · {target} {v}',
    'planner.export.diff': 'Change vs today {b} · {target} {a} → {v}',
    'planner.export.speed': 'Speed {b} · {target}: target met on {v}',

    'planner.m.title': 'Improve with measurements',
    'planner.m.intro': 'Measure the speed (the test is built in) or the signal with your phone in a few places. The map adjusts to match.',
    'planner.m.add': 'Add measurement',
    'planner.m.calibrate': 'Use measurements for calibration',
    'planner.m.deviceGoal': 'Device',
    'planner.m.edit': 'Edit measurement',
    'planner.m.empty': 'No measurements yet.',
    'planner.m.residual': 'difference {d}',
    'planner.m.outlier': 'does not match the model ({d}), not used – try measuring again',
    'planner.m.remind': 'Measure with the router at today’s position and the extra access points switched off. Then click the map where you stood.',
    'planner.m.deleted': 'Measurement “{name}” deleted.',
    'planner.m.tooMany': 'More than 500 measurements cannot be stored.',
    'planner.m.ph': 'e.g. −63',
    'planner.m.dbm': 'dBm',
    'planner.m.pct': '% (Windows)',
    'planner.m.unit': 'Unit',
    'planner.m.down': 'Download (Mbps)',
    'planner.m.up': 'Upload (Mbps)',
    'planner.m.notToday': 'The map shows the router’s trial position. Measure with the router where it really stands at home – measurements are saved for today’s position.',
    'planner.m.showToday': 'Show today’s position',
    'planner.m.odd': 'This result is very different from your earlier tests (or upload is much faster than download). Try the test again, ideally the Thorough one.',
    'planner.m.nodeOn': 'Switch the extra access points off while measuring – measurements are compared with today without them.',
    'planner.m.errValue': 'Enter the signal strength, e.g. −63 (dBm) or 70 (%).',
    'planner.m.errPct': 'Percent must be between 0 and 100.',
    'planner.m.errRange': 'The signal must be between −100 and −20 dBm.',
    'planner.m.errSpeed': 'Speed must be between 0 and 10,000 Mbps.',
    'planner.m.defName': 'Measurement {n}',
    'planner.m.saved': 'Measurement saved: {v}.',
    'planner.m.band': 'Band (GHz)',
    'planner.m.name': 'Name',
    'planner.m.device': 'Device',
    'planner.m.save': 'Save',
    'planner.m.newTitle': 'New measurement',
    'planner.m.editTitle': 'Edit measurement',
    'planner.cal.title': 'How well the model fits',
    'planner.cal.suspicious': '{b}: measurements differ from the model by {d}. Check the band, the scale and the walls.',
    'planner.cal.ok.one': '{b}: model adjusted by {d}, fits within ±{rms} dB ({n} measurement).',
    'planner.cal.ok.other': '{b}: model adjusted by {d}, fits within ±{rms} dB ({n} measurements).',
    'planner.cal.single': '{b}: model adjusted by {d} (only 1 measurement so far, add more).',
    'planner.cal.fallback': 'Using all devices.',
    'planner.cal.off': 'Calibration is off.',

    'planner.start.title': 'Getting started',
    'planner.start.hide': 'Hide the guide',
    'planner.start.plan': 'Floor plan',
    'planner.start.plan.b': 'Draw or load your flat.',
    'planner.start.plan.go': 'Draw',
    'planner.start.today': 'Where the router is today',
    'planner.start.today.b': 'Is the red R where your router really stands? If not, drag it and choose Mark as today’s position.',
    'planner.start.today.go': 'Yes, correct',
    'planner.start.move': 'Try moving the router',
    'planner.start.move.b': 'Drag the red R or click the floor and watch the result.',
    'planner.start.bands': 'Which bands the router broadcasts',
    'planner.start.bands.b': 'Most routers broadcast 2.4 and 5 GHz. Got Wi-Fi 6E or Wi-Fi 7? Tick 6 GHz too.',
    'planner.start.bands.go': 'Check',
    'planner.start.measure': '(Optional) Measure signal or speed',
    'planner.start.measure.b': 'A few phone measurements make the map more accurate. A speed test alone is enough.',
    'planner.start.measure.go': 'Measure',

    'planner.res.title': 'Result',
    'planner.res.target': 'Goal',
    'planner.res.all': 'Whole flat',
    'planner.res.allFloor': 'Whole floor',
    'planner.res.coverage': 'Coverage with good signal',
    'planner.res.avg': 'Average signal',
    'planner.res.p10': 'Weakest 10%',
    'planner.res.rooms': 'Rooms',
    'planner.res.roomsHint': 'click to set the goal',
    'planner.res.noplan': 'Draw a floor plan first.',
    'planner.res.today': 'Today',
    'planner.res.now': 'Now',
    'planner.res.pts': '{n} pts',
    'planner.res.same': 'no change',
    'planner.res.s.great': 'Almost everywhere has a good signal.',
    'planner.res.s.good': 'Most of the area has a good signal.',
    'planner.res.s.half': 'Only about half of the area has a good signal.',
    'planner.res.s.poor': 'Most of the area has a weak signal.',
    'planner.res.s.tryMove': 'Try moving the router.',
    'planner.res.s.tryFind': 'Try Find the best spot (F).',
    'planner.res.s.atBest': 'This is the best spot the app found.',
    'planner.res.s.addAp': 'For more coverage, consider an extra access point.',
    'planner.res.s.better': 'The trial position is better than today.',
    'planner.res.s.worse': 'The trial position is worse than today.',
    'planner.res.speed': 'Target {d}/{u} Mbps met on {v} of the area.',
    'planner.res.speedKnown': 'Speed known for {v} of the area.',
    'planner.res.speedNone': 'Measurements are needed for a speed estimate.',
    'planner.res.roomAria': '{name}: coverage {cov}, average {v}. Set as goal.',
    'planner.res.excluded': '(not counted in the whole flat)',
    'planner.res.live': 'Coverage {cov}, average signal {v}.',

    'planner.router.title': 'Router',
    'planner.router.find': 'Find the best spot',
    'planner.router.back': 'Back to today’s spot',
    'planner.router.backHere': 'Move the router back here',
    'planner.router.mark': 'Mark as today’s position',
    'planner.router.allowed': 'Where can it go?',
    'planner.router.anywhere': 'Anywhere',
    'planner.router.inletT': 'Internet inlet',
    'planner.router.inlet': 'straight line {d} · cable roughly {lo}–{hi} m',
    'planner.router.trial': 'Trial position: {room}, {d} from today’s spot.',
    'planner.router.atToday': 'The router is at today’s spot ({room}). Drag it to compare.',
    'planner.router.alreadyToday': 'The router is already at today’s spot.',
    'planner.router.markedSame': 'Thanks, today’s position is confirmed.',
    'planner.router.marked': 'Done, this is now the router’s position today.',

    'planner.node.mode': 'Type',
    'planner.node.ap_cable': 'Wired access point',
    'planner.node.mesh_cable': 'Wired mesh node',
    'planner.node.mesh_wifi': 'Wireless mesh node',
    'planner.node.repeater': 'Repeater',
    'planner.node.bands': 'Broadcasts on',
    'planner.node.power': 'Power vs the router',
    'planner.node.bhBand': 'Links up over the band',
    'planner.node.bhThr': 'Weakest acceptable link',
    'planner.node.oneBand': 'At least one band must stay on.',

    'planner.speed.title': 'Speed',
    'planner.speed.intro': 'For the Speed view: the speed you want and what your connection can deliver.',
    'planner.speed.tDown': 'Download target',
    'planner.speed.tUp': 'Upload target',
    'planner.speed.reserve': 'Reserve',
    'planner.speed.wanDown': 'Plan: download',
    'planner.speed.wanUp': 'Plan: upload',
    'planner.speed.link': 'Connection and cable',
    'planner.speed.wanPort': 'Router WAN port',
    'planner.speed.ontPort': 'Fibre box (ONT) port',
    'planner.speed.wanLink': 'Negotiated link speed',
    'planner.speed.cat': 'Cable category',
    'planner.speed.len': 'Cable length',
    'planner.speed.unknown': 'Not sure',
    'planner.speed.noLimit': 'Connection limit unknown yet, enter your plan.',
    'planner.speed.limit': 'After the {r} reserve at most: download {d}, upload {u} Mbps.',
    'planner.speed.cant': 'With this plan and reserve you cannot reach the target speed.',
    'planner.speed.cat5': 'A Cat5 cable handles 100 Mbps at most.',
    'planner.speed.long': 'A cable longer than 100 m may slow things down.',
    'planner.speed.show': 'Show the Speed view',

    'planner.adv.title': 'Advanced',
    'planner.adv.width': 'Real width of the flat',
    'planner.adv.model': 'Signal model',
    'planner.adv.near': 'Signal 1 m from the router (5 GHz)',
    'planner.adv.decay': 'Fading with distance',
    'planner.adv.wall': 'Default wall loss (at 5 GHz)',
    'planner.adv.thr': 'Good-signal threshold',
    'planner.adv.range': 'Range-line threshold',
    'planner.adv.rooms': 'What counts as “Whole flat”',
    'planner.adv.palette': 'Colour-blind palette',
    'planner.adv.reset': 'Reset the model',
    'planner.adv.resetDone': 'The model is back to its defaults.',
    'planner.adv.lastRoom': 'At least one room has to count.',

    'planner.keys.router': 'Router tool',
    'planner.keys.measure': 'Measure (on / off)',
    'planner.keys.band': 'Next band (2.4 → 5 → 6 GHz → Auto)',
    'planner.keys.view': 'Next view (signal → speed → change)',
    'planner.keys.ranges': 'Range lines',
    'planner.keys.find': 'Find the best spot',
    'planner.keys.today': 'Router back to today’s spot',
    'planner.keys.arrows': 'Move the router by 25 cm (Shift = 1 m) when the map is focused',
    'planner.keys.enter': 'Save the measurement (Measure tool: new one in the map centre)',
    'planner.keys.esc': 'Cancel dragging, the search or the Measure tool',

    'planner.tour.map.t': 'Drag the router',
    'planner.tour.map.b': 'The red R is the router. Drag it, or click the floor, and the map updates instantly. Arrow keys move it too.',
    'planner.tour.result.t': 'Result',
    'planner.tour.result.b': 'How much of the flat has a good signal today and after the move. Click a room to make it the goal.',
    'planner.tour.find.t': 'Find the best spot',
    'planner.tour.find.b': 'The app tries hundreds of positions and moves the router to the best one. Just press F.',
    'planner.tour.meas.t': 'Improve with measurements',
    'planner.tour.meas.b': 'Measure the signal with your phone in a few places and enter it (M). The map adjusts to match.',

    'planner.undo.router': 'router move',
    'planner.undo.ceilFit': 'ceiling adjusted from measurements',
    'planner.undo.today': 'today’s position move',
    'planner.undo.inlet': 'inlet move',
    'planner.undo.node': 'access point change',
    'planner.undo.measMove': 'measurement move',
    'planner.undo.back': 'router back to today',
    'planner.undo.markToday': 'new position for today',
    'planner.undo.measAdd': 'new measurement',
    'planner.undo.measEdit': 'measurement edit',
    'planner.undo.measDel': 'measurement deletion',
    'planner.undo.optimize': 'best spot',
    'planner.undo.target': 'goal change',
    'planner.undo.allowed': 'router area',
    'planner.undo.device': 'device change',
    'planner.undo.speed': 'speed settings',
    'planner.undo.scale': 'scale change',
    'planner.undo.model': 'model change',
    'planner.undo.resetModel': 'model reset',
    'planner.undo.rooms': 'room selection',
  });
})();
