/* Planner strings for stage 7b (SPEC 13): every measurement knows its Wi-Fi band; band steering / Wi-Fi 7 MLO; Auto. */
(function () {
  'use strict';
  const I = globalThis.WH.i18n;

  I.add('cs', {
    'planner.bd.aria': 'Pásmo, na kterém měříš',
    'planner.bd.formLabel': 'Na jakém pásmu jsi teď?',
    'planner.bd.dontKnow': 'Nevím',
    'planner.bd.dontKnowLong': 'Nevím (automaticky)',
    'planner.bd.where': 'Kde to zjistím?',
    'planner.bd.howPhone': 'Pásmo uvidíš v aplikaci WiFiman (Android i iPhone) u připojené sítě, na Androidu často i v Nastavení › Wi-Fi › tvoje síť. Když to nevíš, vyber Nevím – pásmo odhadnu podle síly signálu v tom místě.',
    'planner.bd.howPc': 'Na počítači pásmo zjistí pomocník sám. Bez něj ho ukáže příkaz z Info o zařízení (řádek Pásmo / Band). Když to nevíš, vyber Nevím – pásmo odhadnu podle síly signálu.',
    'planner.bd.inferred': '≈ {b} GHz (odhad)',
    'planner.bd.unknown': 'pásmo odhadnu',
    'planner.bd.mlo': '{b} GHz (+{o} GHz MLO)',
    'planner.bd.need.phone': 'Na jakém pásmu je telefon připojený?',
    'planner.bd.need.pc': 'Potřebuju vědět pásmo – bez něj měření neuložím.',
    'planner.bd.why.phone': 'Prohlížeč v telefonu pásmo nevidí. Vyber ho – nebo Nevím a odhadnu ho sám.',
    'planner.bd.why.off': 'Pomocník neběží. Spusť ho (dvojklik na „Spustit pomocníka“ ve složce pomocnik) a klikni na Zkusit znovu.',
    'planner.bd.why.ask': 'Prohlížeč potřebuje tvoje svolení, aby se mohl spojit s pomocníkem na tomhle počítači. Klikni na Připojit pomocníka a v okénku prohlížeče na Povolit.',
    'planner.bd.why.slow': 'Pomocník neodpověděl včas (počítač je asi vytížený). Zkus to znovu.',
    'planner.bd.why.noBand': 'Wi-Fi údaje jsem dostal, ale pásmo v nich chybí. Vlož celý výpis příkazu, nebo pásmo zadej ručně.',
    'planner.bd.why.badPaste': 'V tom textu jsem pásmo nenašel. Zkopíruj celý výpis příkazu (všechny řádky) a vlož ho znovu.',
    'planner.bd.why.empty': 'Nejdřív sem vlož výpis příkazu.',
    'planner.bd.paste': 'Vložit výpis',
    'planner.bd.manual': 'Zadat pásmo ručně',
    'planner.bd.manualLead': 'Vyber pásmo, na kterém je počítač teď připojený. Nevíš? Zvol Nevím – odhadnu ho podle síly signálu.',
    'planner.bd.pastePh': 'Sem vlož výpis příkazu (Ctrl+V)',
    'planner.bd.pasteAria': 'Výpis příkazu s Wi-Fi údaji',
    'planner.bd.pasteUse': 'Použít',
    'planner.bd.pasteClip': 'Vložit ze schránky',
    'planner.bd.pasteCtrlV': 'Schránku se přečíst nepovedlo – klikni do pole a stiskni Ctrl+V.',
    'planner.bd.byUser': 'zadáno ručně',
    'planner.bd.byAuto': 'pásmo odhadnu podle síly signálu',
    'planner.bd.saveNoBand': 'Bez pásma měření neuložím.',
    'planner.bd.errNeed': 'Vyber pásmo, na kterém měříš (nebo Nevím).',
    'planner.bd.switched': 'Mapa přepnuta na {b} GHz, na kterém měříš.',
    'planner.bd.steer': 'Tvoje zařízení přeskočilo z {a} na {b} GHz – to je v pořádku, router přepíná pásma sám (band steering, Wi-Fi 7). Každé měření se počítá pro své pásmo a kalibrace taky; jen přidej pár měření na každém pásmu.',
    'planner.bd.setDone': '„{name}“ teď počítám pro {b}.',
    'planner.bd.fixHead': 'Pásmo měření „{name}“',
    'planner.bd.fixHelper': 'Zjistit přes pomocníka teď',
    'planner.bd.unverified': 'pásmo neověřeno',
    'planner.bd.unverifiedTip': 'Tohle měření se uložilo bez zjištění pásma – mohlo se počítat pro špatné. Vyber pásmo, nebo ho zjisti přes pomocníka (stůj přitom na tom místě).',
    'planner.bd.fixBtn': 'Opravit pásmo',
    'planner.bd.unverifiedAll': 'Měření bez ověřeného pásma: {n}. Oprav ho u každého, ať kalibrace sedí.',
    'planner.bd.count': '{b} GHz, měření: {n}',
    'planner.bd.auto': 'Auto',
    'planner.bd.autoLabel': 'Auto ({list} GHz)',
    'planner.bd.autoTip': 'Auto: v každém místě pásmo, na které by se tvoje zařízení nejspíš připojilo',
    'planner.bd.autoNote': 'Auto: na každém místě ukazuju pásmo, které by tvoje zařízení nejspíš použilo ({rule}).',
    'planner.bd.rule': '6 GHz od {six}, 5 GHz od {five}, jinak 2,4 GHz',
    'planner.legend.zones': 'Kde budeš na {list} GHz',
    'planner.undo.measBand': 'Pásmo měření',
    'planner.undo.routerBands': 'Pásma routeru',
    'planner.undo.steer': 'Přepínání pásem',
    'planner.adv.routerBands': 'Která pásma tvůj router vysílá',
    'planner.adv.rbOne': 'Aspoň jedno pásmo musí zůstat zapnuté.',
    'planner.adv.steer': 'Kdy zařízení přejde na jiné pásmo',
    'planner.adv.steer6': 'Na 6 GHz od',
    'planner.adv.steer5': 'Na 5 GHz od',
    'help.bandAuto.t': 'Na jakém pásmu měříš',
    'help.bandAuto.b': 'Každé měření patří k pásmu, na kterém vzniklo (2,4, 5 nebo 6 GHz). Na PC ho zjistí pomocník sám, na telefonu ho vybereš. Když to nevíš, zvol Nevím – pásmo odhadnu podle síly signálu v tom místě.',
    'help.bandAuto.more': 'K jednomu pásmu se připojovat nemusíš. Moderní routery (band steering, Wi-Fi 7 MLO) přepínají pásma samy – nevadí, každé měření se započítá tam, kam patří, a kalibrace se dělá pro každé pásmo zvlášť.',
    'help.routerBands.t': 'Která pásma router vysílá',
    'help.routerBands.b': 'Zaškrtni pásma, na kterých tvůj router vysílá. Většina routerů má 2,4 a 5 GHz; Wi-Fi 6E a Wi-Fi 7 přidávají 6 GHz.',
    'help.routerBands.more': 'Podle toho režim Auto ukazuje, kde budeš na kterém pásmu, a odhaduje pásmo u měření s volbou Nevím.',
    'help.steer.t': 'Kdy zařízení přejde na jiné pásmo',
    'help.steer.b': 'Zařízení s band steeringem (a Wi-Fi 7) zůstane na 6 GHz, dokud je tam signál aspoň takhle silný, pak přejde na 5 GHz a při slabém signálu na 2,4 GHz. Výchozí hodnoty −70 / −72 dBm sedí na většinu routerů.',
    'help.steer.more': 'Podle tohohle pravidla počítá režim Auto mapu, statistiky, rychlost i odhad pásma u měření s volbou Nevím. Když tvůj router přepíná dřív nebo později, posuň hranice.',
  });

  I.add('en', {
    'planner.bd.aria': 'The band you are measuring on',
    'planner.bd.formLabel': 'Which band are you on now?',
    'planner.bd.dontKnow': 'Not sure',
    'planner.bd.dontKnowLong': 'Not sure (automatic)',
    'planner.bd.where': 'Where do I find it?',
    'planner.bd.howPhone': 'The WiFiman app (Android and iPhone) shows the band of the connected network; on Android often also Settings › Wi-Fi › your network. If you do not know, pick Not sure – I will estimate the band from the signal strength at that spot.',
    'planner.bd.howPc': 'On a computer the helper finds out the band by itself. Without it, the command from Device info shows it (the Band line). If you do not know, pick Not sure – I will estimate the band from the signal strength.',
    'planner.bd.inferred': '≈ {b} GHz (estimate)',
    'planner.bd.unknown': 'band estimated',
    'planner.bd.mlo': '{b} GHz (+{o} GHz MLO)',
    'planner.bd.need.phone': 'Which band is the phone connected to?',
    'planner.bd.need.pc': 'I need to know the band – I will not save the measurement without it.',
    'planner.bd.why.phone': 'A phone browser cannot see the band. Pick it – or Not sure and I will estimate it.',
    'planner.bd.why.off': 'The helper is not running. Start it (double-click “Spustit pomocníka” in the pomocnik folder) and click Try again.',
    'planner.bd.why.ask': 'The browser needs your permission to talk to the helper on this computer. Click Connect the helper and then Allow in the browser’s box.',
    'planner.bd.why.slow': 'The helper did not answer in time (the computer is probably busy). Try again.',
    'planner.bd.why.noBand': 'I got the Wi-Fi details, but the band is missing. Paste the whole command output, or enter the band by hand.',
    'planner.bd.why.badPaste': 'I could not find the band in that text. Copy the whole command output (all lines) and paste it again.',
    'planner.bd.why.empty': 'Paste the command output here first.',
    'planner.bd.paste': 'Paste the output',
    'planner.bd.manual': 'Enter the band by hand',
    'planner.bd.manualLead': 'Pick the band the computer is connected to right now. Not sure? Pick Not sure – I will estimate it from the signal strength.',
    'planner.bd.pastePh': 'Paste the command output here (Ctrl+V)',
    'planner.bd.pasteAria': 'Command output with the Wi-Fi details',
    'planner.bd.pasteUse': 'Use',
    'planner.bd.pasteClip': 'Paste from the clipboard',
    'planner.bd.pasteCtrlV': 'Could not read the clipboard – click into the box and press Ctrl+V.',
    'planner.bd.byUser': 'entered by hand',
    'planner.bd.byAuto': 'band estimated from the signal strength',
    'planner.bd.saveNoBand': 'I will not save the measurement without its band.',
    'planner.bd.errNeed': 'Pick the band you are measuring on (or Not sure).',
    'planner.bd.switched': 'Map switched to {b} GHz – the band you are measuring on.',
    'planner.bd.steer': 'Your device jumped from {a} to {b} GHz – that is fine, the router switches bands by itself (band steering, Wi-Fi 7). Every measurement counts for its own band, and so does the calibration; just add a few measurements on each band.',
    'planner.bd.setDone': '“{name}” now counts for {b}.',
    'planner.bd.fixHead': 'Band of “{name}”',
    'planner.bd.fixHelper': 'Read it from the helper now',
    'planner.bd.unverified': 'band not verified',
    'planner.bd.unverifiedTip': 'This measurement was saved without finding out its band – it may count for the wrong one. Pick the band, or read it from the helper (stand at that spot while you do).',
    'planner.bd.fixBtn': 'Fix the band',
    'planner.bd.unverifiedAll': 'Measurements without a verified band: {n}. Fix each of them so the calibration fits.',
    'planner.bd.count': '{b} GHz, measurements: {n}',
    'planner.bd.auto': 'Auto',
    'planner.bd.autoLabel': 'Auto ({list} GHz)',
    'planner.bd.autoTip': 'Auto: at every spot the band your device would most likely use there',
    'planner.bd.autoNote': 'Auto: every spot shows the band your device would most likely use ({rule}).',
    'planner.bd.rule': '6 GHz from {six}, 5 GHz from {five}, else 2.4 GHz',
    'planner.legend.zones': 'Where you will be on {list} GHz',
    'planner.undo.measBand': 'Measurement band',
    'planner.undo.routerBands': 'Router bands',
    'planner.undo.steer': 'Band switching',
    'planner.adv.routerBands': 'Which bands your router broadcasts',
    'planner.adv.rbOne': 'At least one band must stay on.',
    'planner.adv.steer': 'When a device moves to another band',
    'planner.adv.steer6': 'On 6 GHz from',
    'planner.adv.steer5': 'On 5 GHz from',
    'help.bandAuto.t': 'Which band you are measuring on',
    'help.bandAuto.b': 'Every measurement belongs to the band it was taken on (2.4, 5 or 6 GHz). On a PC the helper finds it out by itself, on a phone you pick it. If you do not know, pick Not sure – I will estimate the band from the signal strength at that spot.',
    'help.bandAuto.more': 'You do not have to pin your device to one band. Modern routers (band steering, Wi-Fi 7 MLO) switch bands by themselves – that is fine, every measurement counts where it belongs, and the calibration is done for each band separately.',
    'help.routerBands.t': 'Which bands the router broadcasts',
    'help.routerBands.b': 'Tick the bands your router broadcasts on. Most routers have 2.4 and 5 GHz; Wi-Fi 6E and Wi-Fi 7 add 6 GHz.',
    'help.routerBands.more': 'Auto mode uses it to show where you will be on which band, and to estimate the band of measurements marked Not sure.',
    'help.steer.t': 'When a device moves to another band',
    'help.steer.b': 'A device with band steering (and Wi-Fi 7) stays on 6 GHz while the signal there is at least this strong, then moves to 5 GHz and, with a weak signal, to 2.4 GHz. The defaults −70 / −72 dBm suit most routers.',
    'help.steer.more': 'Auto mode computes the map, the statistics, the speed and the band estimate of Not sure measurements with this rule. If your router switches earlier or later, move the limits.',
  });
})();
