/* Planner strings, stage 9 (SPEC 14): the verified scale, any number of access points / mesh nodes / repeaters, floors.
 * cs + en. */
(function () {
  'use strict';
  const I = globalThis.WH.i18n;

  I.add('cs', {
    // ---- 14.1 scale ----------------------------------------------------------------------------------------------
    'planner.scale.badge': 'Měřítko neověřeno',
    'planner.scale.badgeShort': 'Měřítko',
    'planner.scale.badgeAria': 'Měřítko půdorysu není ověřené. Otevřít nastavení měřítka v Půdorysu',
    'planner.scale.set': 'Nastavit měřítko',
    'planner.scale.note': 'Měřítko zatím nikdo neověřil: byt teď vychází na {a}. Když to nesedí, sedí špatně i celá mapa.',
    'planner.scale.noteNoArea': 'Měřítko zatím nikdo neověřil, takže metry na mapě jsou jen odhad.',
    'planner.scale.area': 'Byt teď vychází na {a}, největší je {room} ({r}).',
    'planner.scale.areaOnly': 'Byt teď vychází na {a}.',
    'planner.scale.ok': 'Měřítko ověřené',
    'planner.start.scale': 'Měřítko půdorysu',
    'planner.start.scale.b': 'Napiš, kolik má byt m², nebo změř jednu zeď. Jinak aplikace jen hádá, jak je byt velký.',
    'planner.start.scale.go': 'Nastavit',
    'help.scaleUnverified.t': 'Měřítko neověřeno',
    'help.scaleUnverified.b': 'Aplikace neví jistě, kolik metrů má tvůj půdorys. Když je měřítko špatně, byt může vyjít třeba na 100 m² místo 58 m² a celá mapa signálu je pak mimo.',
    'help.scaleUnverified.more': 'Klikni na „Měřítko neověřeno“: v Půdorysu stačí napsat plochu bytu v m² (najdeš ji v nájemní smlouvě nebo na katastru), nebo změřit jednu zeď či dveře.',

    // ---- 14.2 nodes ----------------------------------------------------------------------------------------------
    'planner.nodes.title': 'Další přístupové body',
    'planner.nodes.add': 'Přidat AP / mesh / opakovač',
    'planner.nodes.suggest': 'Kolik AP potřebuju a kam?',
    'planner.nodes.suggest.goal': 'Kolik bytu má mít dobrý signál',
    'planner.nodes.suggest.busy': 'Zkouším místa pro další AP…',
    'planner.nodes.suggest.enough': 'Dobrý signál má už teď {c} % bytu (cíl {g} %), další AP není potřeba.',
    'planner.nodes.suggest.none': 'Dobrý signál má {c} % bytu. Další AP by to nezlepšil, zkus místo něj upravit zdi nebo polohu routeru.',
    'planner.nodes.suggest.need': 'Pro {g} % bytu s dobrým signálem stačí přidat {k} AP s kabelem: {where}. Pokrytí vzroste z {a} % na {b} %.',
    'planner.nodes.suggest.short': 'Ani s {k} AP navíc se {g} % nedosáhne ({a} % → {b} %). Navržená místa: {where}.',
    'planner.nodes.suggest.somewhere': 'někde v bytě',
    'planner.nodes.suggest.enoughRoom': 'Dobrý signál má už teď {c} % místnosti {room} (cíl {g} %), další AP není potřeba.',
    'planner.nodes.suggest.noneRoom': 'Dobrý signál má {c} % místnosti {room}. Další AP by to nezlepšil, zkus místo něj upravit zdi nebo polohu routeru.',
    'planner.nodes.suggest.needRoom': 'Pro {g} % místnosti {room} s dobrým signálem stačí přidat {k} AP s kabelem: {where}. Pokrytí vzroste z {a} % na {b} %.',
    'planner.nodes.suggest.shortRoom': 'Ani s {k} AP navíc se v místnosti {room} {g} % nedosáhne ({a} % → {b} %). Navržená místa: {where}.',
    'planner.nodes.suggest.apply': 'Přidat navržené AP ({k})',
    'planner.nodes.suggest.note': 'Počítá se s AP připojeným kabelem. Bezdrátový uzel nebo opakovač bude o něco slabší.',
    'planner.nodes.suggest.fail': 'Navrhnout AP se nepodařilo.',
    'planner.nodes.suggest.added': 'Přidáno navržených AP: {n}.',
    'planner.nodes.empty': 'Zatím žádný. Přidej přístupový bod po kabelu, mesh nebo opakovač a hned uvidíš, kde pomůže.',
    'planner.nodes.max': 'Víc než {n} bodů v jednom domě nepřidáš.',
    'planner.nodes.added': 'Přidáno: {name}. Přetáhni ho na mapě tam, kde má stát.',
    'planner.nodes.deleted': 'Smazáno: {name}',
    'planner.nodes.delete': 'Smazat bod',
    'planner.nodes.delAria': 'Smazat {name}',
    'planner.nodes.onAria': '{name} zapnutý',
    'planner.nodes.rowAria': '{name}: {what}. Otevřít nastavení',
    'planner.nodes.name': 'Název',
    'planner.nodes.floor': 'Patro',
    'planner.undo.nodeFloor': 'přesun bodu do jiného patra',
    'planner.nodes.uplink': 'Připojený k',
    'planner.nodes.upRouter': 'routeru',
    'planner.nodes.withRouter': 'routerem',
    'planner.nodes.upFloor': '{name} ({floor})',
    'planner.nodes.subCableR': 'kabel k routeru',
    'planner.nodes.subCableN': 'kabel k bodu {up}',
    'planner.nodes.subWifiR': 'Wi-Fi k routeru',
    'planner.nodes.subWifiN': 'Wi-Fi k bodu {up}',
    'planner.nodes.subFloor': '{floor}',
    'planner.nodes.off': 'vypnutý',
    'planner.nodes.offAria': '(vypnutý)',
    'planner.nodes.offTip': 'Je vypnutý, mapa s ním nepočítá.',
    'planner.nodes.chainOff': 'nevysílá, bod, ke kterému je připojený, je vypnutý',
    'planner.nodes.bhOk': 'Spojení s {up}: {v} · {q}',
    'planner.nodes.bhWeak': 'Spojení s {up} je slabé: {v} · {q}. Posuň bod blíž.',
    'planner.nodes.bhViaNode': 'Po kabelu k bodu {up}: rychlejší než to, co zvládne {up}, to tudy nebude.',
    'planner.nodes.hops.one': 'K routeru vede přes {n} bezdrátový skok, ten rychlost zhruba půlí.',
    'planner.nodes.hops.few': 'K routeru vede přes {n} bezdrátové skoky, každý rychlost zhruba půlí.',
    'planner.nodes.hops.other': 'K routeru vede přes {n} bezdrátových skoků, každý rychlost zhruba půlí.',
    'planner.wi.bySrc.one': '{name}: {n} bod, průměrně {d}',
    'planner.wi.bySrc.few': '{name}: {n} body, průměrně {d}',
    'planner.wi.bySrc.other': '{name}: {n} bodů, průměrně {d}',
    'planner.nodes.show': 'Ukázat na mapě',
    'planner.nodes.showFloor': 'Ukázat na mapě ({floor})',
    'planner.nodes.drag': 'Značku přetáhni na mapě tam, kde má bod stát. Když ji vybereš, posuneš ji i šipkami.',
    'planner.nodes.pfx.ap_cable': 'AP',
    'planner.nodes.pfx.mesh_cable': 'Mesh',
    'planner.nodes.pfx.mesh_wifi': 'Mesh',
    'planner.nodes.pfx.repeater': 'Opakovač',
    'planner.mk.nodeAriaN': '{lbl} ({type}): {room}. Posuň šipkami, Enter otevře nastavení.',
    'planner.mk.nodeTipN': 'Přetáhni ho, kam patří. Kliknutím otevřeš jeho nastavení.',
    'planner.undo.nodeAdd': 'nový přístupový bod',
    'planner.undo.nodeDel': 'smazání přístupového bodu',
    'planner.undo.nodeMove': 'přesun přístupového bodu',
    'planner.undo.nodeName': 'přejmenování bodu',
    'planner.undo.nodeType': 'změna typu bodu',
    'planner.undo.nodeUplink': 'změna připojení bodu',
    'planner.undo.nodeOn': 'zapnutí bodu',
    'planner.undo.nodeOff': 'vypnutí bodu',
    'planner.legend.sourceMany': 'šrafy: tady má navrch {node}, jinde router',
    'planner.legend.sourceWeakMany': 'šedé šrafy: silnější je tu {node}, ale má slabé spojení',
    'planner.legend.more': '{list} a další {n}',
    'planner.res.or': 'nebo',
    'planner.res.srcPart1': '{who} má navrch v místnosti {list}',
    'planner.res.srcPartN': '{who} má navrch v místnostech {list}',
    'planner.res.srcMulti': '{parts}, jinde je silnější router.',
    'planner.res.srcMultiAll': '{parts}.',
    'planner.res.srcNoneMany': 'Žádný z bodů není nikde silnější než router – zkus je posunout dál od routeru.',
    'planner.res.srcWhoFloor': '{who} ({floor})',
    'planner.res.srcAllFloor': '{who} je silnější než router na celém tomhle patře.',
    'planner.wi.tip.fromNodeN': 'Signál tu dá {name}.',
    'planner.wi.who.nodes': 'Další přístupové body',
    'planner.wi.via': 'přes {name}',
    'help.nodesList.t': 'Další přístupové body',
    'help.nodesList.b': 'Přístupové body po kabelu, mesh a opakovače, kolik jich potřebuješ (až 8). Každý má na mapě svou modrou značku s názvem a čárkovanou čáru k tomu, k čemu je připojený.',
    'help.nodesList.more': 'Vypnutý bod zůstane na mapě bledý a nepočítá se. Bezdrátový bod může viset i na jiném bodu: rychlost se pak s každým bezdrátovým skokem zhruba půlí.',
    'help.uplink.t': 'Připojený k',
    'help.uplink.b': 'Odkud bod bere internet: přímo z routeru, nebo z jiného bodu. Kabel rychlost skoro neubere, Wi-Fi ano, a ještě víc, když jde přes několik bodů za sebou.',

    // ---- 14.3 floors ---------------------------------------------------------------------------------------------
    'planner.fl.aria': 'Patro na mapě',
    'planner.fl.aria1': '{name} (Alt+{n})',
    'planner.fl.short0': 'P',
    'planner.fl.shortDown': '−{n}',
    'planner.fl.switched': 'Patro: {name}',
    'planner.fl.top': 'Výš už žádné patro není.',
    'planner.fl.bottom': 'Níž už žádné patro není.',
    'planner.fl.ghostCap': 'na jiném patře',
    'planner.fl.ghostAria': '{what} je na jiném patře ({floor}). Enter tam přepne.',
    'planner.fl.ghostTip': 'Je na jiném patře ({floor}), sem dosáhne přes strop. Kliknutím tam přepneš.',
    'planner.fl.routerElsewhere': 'Router je na jiném patře ({floor}). Posunout ho můžeš tam.',
    'planner.fl.goThere': 'Přejít tam',
    'planner.fl.goFloor': 'Přepnout na {floor}',
    'planner.fl.pillAria': 'Měříš: {name}. Změnit patro',
    'planner.fl.mmSwitched': 'Teď měříš: {name}.',
    'planner.fl.calibFloor': 'Průvodce měří kolem routeru, proto mapa přepnula na {floor}.',
    'planner.keys.floorUp': 'O patro výš',
    'planner.keys.floorDown': 'O patro níž',
    'planner.keys.floorNum': 'Patro podle pořadí zdola (Alt+1 až Alt+9)',
    'planner.tip.ceiling': 'Router je na jiném patře ({floor}), stropy tu ubírají asi {d} dB',
    'planner.tip.ceilingOpen': 'Router je na jiném patře ({floor}), signál sem vede otvorem ve stropě (schodiště)',
    'planner.router.otherFloor': 'Router je na jiném patře: {floor}, {room}.',
    'planner.router.inletFloor': 'Přípojka je na jiném patře ({floor}), kabel povede i přes strop.',
    'planner.opt.roomFloor': '{room} ({floor})',
    'planner.opt.foundHouse': 'Nejlepší místo pro celý dům: {room}, pokrytí {a} → {b}.',
    'planner.res.titleFloor': 'Výsledek · {floor}',
    'planner.res.speedFloor': '{floor}: cíl {d}/{u} Mb/s splníš na {v} plochy.',
    'planner.res.house': 'Celý dům',
    'planner.res.houseCov': 'Dobrý signál',
    'planner.res.houseFloorAria': '{name}: pokrytí {v}. Přepnout na toto patro',
    'planner.ceil.title': 'Patra a stropy',
    'planner.ceil.between': 'Strop nad patrem: {a}',
    'planner.ceil.material': 'Strop je',
    'planner.ceil.matDb': '{m} (asi {d} dB)',
    'planner.ceil.mat.concrete': 'Betonový',
    'planner.ceil.mat.reinforced_concrete': 'Železobetonový',
    'planner.ceil.mat.wood': 'Dřevěný (trámový)',
    'planner.ceil.mat.custom': 'Vlastní hodnota',
    'planner.ceil.loss': 'Kolik signálu strop ubere (5 GHz)',
    'planner.ceil.height': 'Výška patra (podlaha k podlaze)',
    'planner.ceil.note': 'Schodiště nakresli v editoru jako „Otvor (schodiště)“ do horního patra, tam se útlum stropu nepočítá.',
    'planner.undo.ceiling': 'změna stropu',
    'help.floorSwitch.t': 'Patra',
    'help.floorSwitch.b': 'Přepíná, které patro je na mapě. Router a body z jiných pater vidíš jako bledé značky „na jiném patře“ a jejich signál sem prochází stropem.',
    'help.floorSwitch.more': 'Z klávesnice: Ctrl+↑ a Ctrl+↓ o patro výš a níž, Alt+1 až Alt+9 patro podle pořadí zdola. Patra přidáš v Půdorysu.',
    'help.house.t': 'Celý dům',
    'help.house.b': 'Kolik procent plochy všech pater má dobrý signál, každé patro váží podle své plochy. Pod tím vidíš každé patro zvlášť, kliknutím na něj přepneš.',
    'help.ceilingLoss.t': 'Útlum stropu',
    'help.ceilingLoss.b': 'Kolik signálu ubere strop mezi patry. Betonový strop asi 15 dB, železobetonový asi 20 dB, dřevěný trámový asi 8 dB (při 5 GHz; 2,4 GHz projde snáz, 6 GHz hůř).',
    'help.ceilingLoss.more': 'Nevíš, jaký strop máš? Panelák a novostavba mají většinou železobeton, starší rodinný dům často dřevěné trámy. Když máš měření z obou pater, nastav hodnotu tak, aby mapa seděla.',
    'help.ceilingHeight.t': 'Výška patra',
    'help.ceilingHeight.b': 'Vzdálenost od podlahy tohoto patra k podlaze patra nad ním, obvykle kolem 2,7 až 3 m. Signál z jiného patra musí urazit i tuhle výšku.',

    // ---- agent tools (90-app/agent-tools.js) ------------------------------------------------------------------
    'planner.agent.err.node': 'Takový přístupový bod tu není. Zadej jeho číslo ze seznamu (1 až {n}) nebo jeho název.',
    'planner.agent.speedNodes': 'Místa, která obslouží přístupový bod, počítají i s rychlostí jeho propojení s routerem. Je to jen orientační odhad.',
  });

  I.add('en', {
    // ---- 14.1 scale ----------------------------------------------------------------------------------------------
    'planner.scale.badge': 'Scale not verified',
    'planner.scale.badgeShort': 'Scale',
    'planner.scale.badgeAria': 'The floor plan’s scale is not verified. Open the scale settings in Floor plan',
    'planner.scale.set': 'Set the scale',
    'planner.scale.note': 'Nobody has checked the scale yet: your home now comes out at {a}. If that is wrong, the whole map is wrong too.',
    'planner.scale.noteNoArea': 'Nobody has checked the scale yet, so the metres on the map are only a guess.',
    'planner.scale.area': 'Your home now comes out at {a}, the largest room is {room} ({r}).',
    'planner.scale.areaOnly': 'Your home now comes out at {a}.',
    'planner.scale.ok': 'Scale verified',
    'planner.start.scale': 'Floor plan scale',
    'planner.start.scale.b': 'Type the area of your home in m² or measure one wall. Otherwise the app only guesses how big your home is.',
    'planner.start.scale.go': 'Set it',
    'help.scaleUnverified.t': 'Scale not verified',
    'help.scaleUnverified.b': 'The app does not know for sure how many metres your floor plan has. With a wrong scale your home may come out at 100 m² instead of 58 m², and then the whole signal map is off.',
    'help.scaleUnverified.more': 'Click “Scale not verified”: in Floor plan just type the area of your home in m² (it is in your lease or the land register), or measure one wall or door.',

    // ---- 14.2 nodes ----------------------------------------------------------------------------------------------
    'planner.nodes.title': 'More access points',
    'planner.nodes.add': 'Add AP / mesh / repeater',
    'planner.nodes.suggest': 'How many APs do I need, and where?',
    'planner.nodes.suggest.goal': 'Share of the home with good signal',
    'planner.nodes.suggest.busy': 'Trying places for another AP…',
    'planner.nodes.suggest.enough': '{c} % of the home already has good signal (goal {g} %), no extra AP is needed.',
    'planner.nodes.suggest.none': '{c} % of the home has good signal. Another AP would not improve it, try changing the walls or the router position instead.',
    'planner.nodes.suggest.need': 'For {g} % of the home with good signal, add {k} wired AP(s): {where}. Coverage rises from {a} % to {b} %.',
    'planner.nodes.suggest.short': 'Even with {k} more AP(s) {g} % is not reached ({a} % → {b} %). Suggested places: {where}.',
    'planner.nodes.suggest.somewhere': 'somewhere in the home',
    'planner.nodes.suggest.enoughRoom': '{c} % of {room} already has good signal (goal {g} %), no extra AP is needed.',
    'planner.nodes.suggest.noneRoom': '{c} % of {room} has good signal. Another AP would not improve it, try changing the walls or the router position instead.',
    'planner.nodes.suggest.needRoom': 'For {g} % of {room} with good signal, add {k} wired AP(s): {where}. Coverage rises from {a} % to {b} %.',
    'planner.nodes.suggest.shortRoom': 'Even with {k} more AP(s) {g} % of {room} is not reached ({a} % → {b} %). Suggested places: {where}.',
    'planner.nodes.suggest.apply': 'Add the suggested AP(s) ({k})',
    'planner.nodes.suggest.note': 'This assumes an AP connected by cable. A wireless node or repeater will be a little weaker.',
    'planner.nodes.suggest.fail': 'Could not suggest an AP.',
    'planner.nodes.suggest.added': 'Suggested APs added: {n}.',
    'planner.nodes.empty': 'None yet. Add a wired access point, a mesh node or a repeater and see right away where it helps.',
    'planner.nodes.max': 'You cannot add more than {n} points to one home.',
    'planner.nodes.added': 'Added: {name}. Drag it on the map to where it should stand.',
    'planner.nodes.deleted': 'Deleted: {name}',
    'planner.nodes.delete': 'Delete the point',
    'planner.nodes.delAria': 'Delete {name}',
    'planner.nodes.onAria': '{name} on',
    'planner.nodes.rowAria': '{name}: {what}. Open its settings',
    'planner.nodes.name': 'Name',
    'planner.nodes.floor': 'Floor',
    'planner.undo.nodeFloor': 'moving a point to another floor',
    'planner.nodes.uplink': 'Connected to',
    'planner.nodes.upRouter': 'the router',
    'planner.nodes.withRouter': 'the router',
    'planner.nodes.upFloor': '{name} ({floor})',
    'planner.nodes.subCableR': 'cable to the router',
    'planner.nodes.subCableN': 'cable to {up}',
    'planner.nodes.subWifiR': 'Wi-Fi to the router',
    'planner.nodes.subWifiN': 'Wi-Fi to {up}',
    'planner.nodes.subFloor': '{floor}',
    'planner.nodes.off': 'off',
    'planner.nodes.offAria': '(off)',
    'planner.nodes.offTip': 'It is switched off, the map leaves it out.',
    'planner.nodes.chainOff': 'not sending, the point it connects to is off',
    'planner.nodes.bhOk': 'Link to {up}: {v} · {q}',
    'planner.nodes.bhWeak': 'The link to {up} is weak: {v} · {q}. Move the point closer.',
    'planner.nodes.bhViaNode': 'By cable to {up}: nothing gets faster through here than what {up} can do.',
    'planner.nodes.hops.one': 'It reaches the router over {n} wireless hop, which roughly halves the speed.',
    'planner.nodes.hops.other': 'It reaches the router over {n} wireless hops, each one roughly halves the speed.',
    'planner.wi.bySrc.one': '{name}: {n} point, {d} on average',
    'planner.wi.bySrc.other': '{name}: {n} points, {d} on average',
    'planner.nodes.show': 'Show on the map',
    'planner.nodes.showFloor': 'Show on the map ({floor})',
    'planner.nodes.drag': 'Drag the marker on the map to where the point should stand. Once selected, the arrow keys move it too.',
    'planner.nodes.pfx.ap_cable': 'AP',
    'planner.nodes.pfx.mesh_cable': 'Mesh',
    'planner.nodes.pfx.mesh_wifi': 'Mesh',
    'planner.nodes.pfx.repeater': 'Repeater',
    'planner.mk.nodeAriaN': '{lbl} ({type}): {room}. Move with the arrow keys, Enter opens its settings.',
    'planner.mk.nodeTipN': 'Drag it to where it belongs. Click it to open its settings.',
    'planner.undo.nodeAdd': 'new access point',
    'planner.undo.nodeDel': 'deleting an access point',
    'planner.undo.nodeMove': 'moving an access point',
    'planner.undo.nodeName': 'renaming a point',
    'planner.undo.nodeType': 'changing a point’s type',
    'planner.undo.nodeUplink': 'changing a point’s connection',
    'planner.undo.nodeOn': 'switching a point on',
    'planner.undo.nodeOff': 'switching a point off',
    'planner.legend.sourceMany': 'hatching: {node} is stronger here, the router elsewhere',
    'planner.legend.sourceWeakMany': 'grey hatching: {node} is stronger here, but its link is weak',
    'planner.legend.more': '{list} and {n} more',
    'planner.res.or': 'or',
    'planner.res.srcPart1': '{who} wins in {list}',
    'planner.res.srcPartN': '{who} wins in {list}',
    'planner.res.srcMulti': '{parts}, the router is stronger elsewhere.',
    'planner.res.srcMultiAll': '{parts}.',
    'planner.res.srcNoneMany': 'None of the points is stronger than the router anywhere – try moving them further from the router.',
    'planner.res.srcWhoFloor': '{who} ({floor})',
    'planner.res.srcAllFloor': '{who} is stronger than the router all over this floor.',
    'planner.wi.tip.fromNodeN': '{name} serves this spot.',
    'planner.wi.who.nodes': 'The extra access points',
    'planner.wi.via': 'via {name}',
    'help.nodesList.t': 'More access points',
    'help.nodesList.b': 'Wired access points, mesh nodes and repeaters, as many as you need (up to 8). Each has its own blue marker with its name on the map and a dashed line to what it is connected to.',
    'help.nodesList.more': 'A point that is switched off stays faded on the map and does not count. A wireless point can hang on another point too: the speed then roughly halves with every wireless hop.',
    'help.uplink.t': 'Connected to',
    'help.uplink.b': 'Where the point gets the internet from: straight from the router, or from another point. A cable takes almost no speed, Wi-Fi does, and even more over several points in a row.',

    // ---- 14.3 floors ---------------------------------------------------------------------------------------------
    'planner.fl.aria': 'Floor on the map',
    'planner.fl.aria1': '{name} (Alt+{n})',
    'planner.fl.short0': 'G',
    'planner.fl.shortDown': '−{n}',
    'planner.fl.switched': 'Floor: {name}',
    'planner.fl.top': 'There is no floor above.',
    'planner.fl.bottom': 'There is no floor below.',
    'planner.fl.ghostCap': 'other floor',
    'planner.fl.ghostAria': '{what} is on another floor ({floor}). Press Enter to go there.',
    'planner.fl.ghostTip': 'It is on another floor ({floor}) and reaches here through the ceiling. Click to go there.',
    'planner.fl.routerElsewhere': 'The router is on another floor ({floor}). You can move it there.',
    'planner.fl.goThere': 'Go there',
    'planner.fl.goFloor': 'Switch to {floor}',
    'planner.fl.pillAria': 'Measuring on: {name}. Change the floor',
    'planner.fl.mmSwitched': 'Now measuring on: {name}.',
    'planner.fl.calibFloor': 'The guide measures around the router, so the map switched to {floor}.',
    'planner.keys.floorUp': 'One floor up',
    'planner.keys.floorDown': 'One floor down',
    'planner.keys.floorNum': 'Floor by its order from the bottom (Alt+1 to Alt+9)',
    'planner.tip.ceiling': 'The router is on another floor ({floor}), the ceilings take about {d} dB here',
    'planner.tip.ceilingOpen': 'The router is on another floor ({floor}), the signal reaches here through an opening in the ceiling (stairwell)',
    'planner.router.otherFloor': 'The router is on another floor: {floor}, {room}.',
    'planner.router.inletFloor': 'The inlet is on another floor ({floor}), the cable also goes through the ceiling.',
    'planner.opt.roomFloor': '{room} ({floor})',
    'planner.opt.foundHouse': 'Best spot for the whole house: {room}, coverage {a} → {b}.',
    'planner.res.titleFloor': 'Result · {floor}',
    'planner.res.speedFloor': '{floor}: you meet the {d}/{u} Mbps target on {v} of the area.',
    'planner.res.house': 'Whole house',
    'planner.res.houseCov': 'Good signal',
    'planner.res.houseFloorAria': '{name}: coverage {v}. Switch to this floor',
    'planner.ceil.title': 'Floors and ceilings',
    'planner.ceil.between': 'Ceiling above: {a}',
    'planner.ceil.material': 'The ceiling is',
    'planner.ceil.matDb': '{m} (about {d} dB)',
    'planner.ceil.mat.concrete': 'Concrete',
    'planner.ceil.mat.reinforced_concrete': 'Reinforced concrete',
    'planner.ceil.mat.wood': 'Wooden (joists)',
    'planner.ceil.mat.custom': 'My own value',
    'planner.ceil.loss': 'How much signal the ceiling takes (5 GHz)',
    'planner.ceil.height': 'Storey height (floor to floor)',
    'planner.ceil.note': 'Draw the stairwell in the editor as "Opening (stairwell)" on the upper floor; the ceiling loss is skipped there.',
    'planner.undo.ceiling': 'changing a ceiling',
    'help.floorSwitch.t': 'Floors',
    'help.floorSwitch.b': 'Chooses which floor is on the map. The router and points of other floors show as faded “other floor” markers, and their signal comes through the ceiling.',
    'help.floorSwitch.more': 'Keyboard: Ctrl+↑ and Ctrl+↓ go one floor up and down, Alt+1 to Alt+9 pick a floor by its order from the bottom. Add floors in Floor plan.',
    'help.house.t': 'Whole house',
    'help.house.b': 'How much of the area of all floors has a good signal, each floor weighted by its area. Below it every floor on its own; click one to switch to it.',
    'help.ceilingLoss.t': 'Ceiling loss',
    'help.ceilingLoss.b': 'How much signal the ceiling between floors takes. A concrete ceiling about 15 dB, reinforced concrete about 20 dB, wooden joists about 8 dB (at 5 GHz; 2.4 GHz gets through more easily, 6 GHz less).',
    'help.ceilingLoss.more': 'Not sure what ceiling you have? Blocks of flats and new houses mostly have reinforced concrete, older family houses often wooden joists. With measurements on both floors, set the value so the map agrees with them.',
    'help.ceilingHeight.t': 'Storey height',
    'help.ceilingHeight.b': 'The distance from this floor to the floor above, usually around 2.7 to 3 m. A signal from another floor has to cover that height as well.',

    // ---- agent tools (90-app/agent-tools.js) ------------------------------------------------------------------
    'planner.agent.err.node': 'There is no such access point. Give its number from the list (1 to {n}) or its name.',
    'planner.agent.speedNodes': 'Places an access point serves also count with the speed of its link to the router. It is only an approximate estimate.',
  });
})();
