/* Planner strings of stage 5 (SPEC 7): the speed-view banner, the device picker, band power / band-dependent wall loss. */
(function () {
  'use strict';
  const I = globalThis.WH.i18n;

  I.add('cs', {
    'planner.sb.title': 'Měření s rychlostí',
    'planner.sb.why': 'Stačí 2 místa s různě silným signálem – třeba u routeru a ve vzdáleném pokoji ({device}, {band}).',
    'planner.sb.otherDev': 'Počítám jen s měřeními ze zařízení „{device}“ na {band}. Jiné zařízení vybereš v kartě Zpřesnit měřením.',
    'planner.sb.whyShort': 'Stačí 2 místa s různě silným signálem.',
    'planner.sb.otherDevShort': 'Počítám jen s měřeními ze zařízení „{device}“.',
    'planner.sb.spreadShort': 'Přidej místo, kde je signál aspoň o 5 dB jiný.',
    'planner.sb.spread': 'Měření jsou si moc podobná. Přidej místo, kde je signál aspoň o 5 dB jiný – třeba vzdálený pokoj.',
    'planner.sb.clickMap': 'Teď klikni na mapě na místo, kde měříš.',
    'planner.sb.back': 'Zpět na Signál',
    'planner.sb.hide': 'Skrýt lištu',

    'planner.dev.phone': 'Telefon',
    'planner.dev.phone.alias': 'Mobil|Mobilní telefon|Chytrý telefon|Smartphone',
    'planner.dev.laptop': 'Notebook',
    'planner.dev.laptop.alias': 'Laptop',
    'planner.dev.pc': 'Počítač (PC)',
    'planner.dev.pc.alias': 'PC|Počítač|Stolní počítač',
    'planner.dev.tablet': 'Tablet',
    'planner.dev.tablet.alias': 'Tablet',
    'planner.dev.rpi': 'Raspberry Pi',
    'planner.dev.rpi.alias': 'Raspberry|RPi',
    'planner.dev.tv': 'Televize / TV box',
    'planner.dev.tv.alias': 'TV|Televize|Televizor|TV box|Chytrá televize',
    'planner.dev.console': 'Herní konzole',
    'planner.dev.console.alias': 'Konzole|Herní konzol',
    'planner.dev.custom': 'Vlastní název…',
    'planner.dev.customPh': 'Třeba Pracovní notebook',
    'planner.dev.customAria': 'Vlastní název zařízení',
    'planner.dev.ok': 'Použít název',
    'planner.dev.used': 'Tvoje názvy',
    'planner.dev.aria': 'Zařízení pro kalibraci a rychlost: {name}. Změnit',
    'planner.dev.ariaMeas': 'Zařízení tohoto měření: {name}. Změnit',

    'planner.m.morePop': 'Více údajů',
    'planner.tip.walls': 'Zdi a nábytek cestou ubírají {d} dB',

    'planner.adv.wallBands': 'Na 2,4 GHz zhruba {a}, na 6 GHz {c} – nižší frekvence projde zdí snáz.',
    'planner.adv.bandPower': 'Rozdíl výkonu pásem',
    'planner.adv.bp24': '2,4 GHz proti 5 GHz',
    'planner.adv.bp6': '6 GHz proti 5 GHz',
    'help.bandPower.t': 'Rozdíl výkonu pásem',
    'help.bandPower.b': 'O kolik decibelů router vysílá na 2,4 nebo 6 GHz jinak než na 5 GHz. Routery často vysílají na 2,4 GHz o 3 dB slaběji než na 5 GHz; když to nevíš, nech 0.',
    'help.bandPower.more': 'Kladné číslo = pásmo vysílá silněji, záporné = slaběji. V Evropě smí router vysílat na 2,4 GHz nejvýš 20 dBm, na 5 GHz 23 až 30 dBm a na 6 GHz v bytě 23 dBm.',
  });

  I.add('en', {
    'planner.sb.title': 'Speed measurements',
    'planner.sb.why': 'Two places with different signal strength are enough – for example next to the router and in a far room ({device}, {band}).',
    'planner.sb.otherDev': 'Only measurements from “{device}” on {band} count. Pick another device in the Improve with measurements card.',
    'planner.sb.whyShort': 'Two places with different signal strength are enough.',
    'planner.sb.otherDevShort': 'Only measurements from “{device}” count.',
    'planner.sb.spreadShort': 'Add a place where the signal differs by at least 5 dB.',
    'planner.sb.spread': 'Your measurements are too similar. Add a place where the signal differs by at least 5 dB – such as a far room.',
    'planner.sb.clickMap': 'Now click the map where you are measuring.',
    'planner.sb.back': 'Back to Signal',
    'planner.sb.hide': 'Hide this bar',

    'planner.dev.phone': 'Phone',
    'planner.dev.phone.alias': 'Mobile|Mobile phone|Cell phone|Smartphone',
    'planner.dev.laptop': 'Laptop',
    'planner.dev.laptop.alias': 'Notebook',
    'planner.dev.pc': 'Desktop PC',
    'planner.dev.pc.alias': 'PC|Computer|Desktop',
    'planner.dev.tablet': 'Tablet',
    'planner.dev.tablet.alias': 'Tablet',
    'planner.dev.rpi': 'Raspberry Pi',
    'planner.dev.rpi.alias': 'Raspberry|RPi',
    'planner.dev.tv': 'TV / TV box',
    'planner.dev.tv.alias': 'TV|Television|TV box|Smart TV',
    'planner.dev.console': 'Game console',
    'planner.dev.console.alias': 'Console|Games console',
    'planner.dev.custom': 'Custom name…',
    'planner.dev.customPh': 'For example Work laptop',
    'planner.dev.customAria': 'Custom device name',
    'planner.dev.ok': 'Use this name',
    'planner.dev.used': 'Your names',
    'planner.dev.aria': 'Device for calibration and speed: {name}. Change',
    'planner.dev.ariaMeas': 'Device of this measurement: {name}. Change',

    'planner.m.morePop': 'More details',
    'planner.tip.walls': 'Walls and furniture on the way take {d} dB',

    'planner.adv.wallBands': 'About {a} at 2.4 GHz and {c} at 6 GHz – lower frequencies get through walls more easily.',
    'planner.adv.bandPower': 'Band power difference',
    'planner.adv.bp24': '2.4 GHz vs 5 GHz',
    'planner.adv.bp6': '6 GHz vs 5 GHz',
    'help.bandPower.t': 'Band power difference',
    'help.bandPower.b': 'How many decibels stronger or weaker the router transmits on 2.4 or 6 GHz than on 5 GHz. Routers often transmit about 3 dB weaker on 2.4 GHz than on 5 GHz; if you are not sure, leave it at 0.',
    'help.bandPower.more': 'A positive number = that band transmits stronger, negative = weaker. In Europe a router may transmit at most 20 dBm on 2.4 GHz, 23 to 30 dBm on 5 GHz and 23 dBm on 6 GHz indoors.',
  });
})();
