/* Planner strings for stage 7 (SPEC 10): what changes at the measured points, node speed caps, dots on walls. */
(function () {
  'use strict';
  const I = globalThis.WH.i18n;

  I.add('cs', {
    'planner.wi.title': 'Co by se změnilo v tvých bodech',
    'planner.wi.idle': 'Posuň router nebo zapni druhý přístupový bod – tady pak uvidíš, o kolik se zlepší nebo zhorší tvoje naměřené body.',
    'planner.wi.avg': 'Průměrně {d}',
    'planner.wi.up': 'lepší: {n}',
    'planner.wi.down': 'horší: {n}',
    'planner.wi.same': 'beze změny: {n}',
    'planner.wi.rowAria': '{name}: {a} → {b} dBm ({d})',
    'planner.wi.res': 'Tvoje měřené body ({n}): průměrně {d}, lepší {up}, horší {down}.',
    'planner.wi.details': 'Podrobnosti',
    'planner.wi.who.repeater': 'Opakovač',
    'planner.wi.who.mesh_wifi': 'Mesh přes Wi-Fi',
    'planner.wi.who.mesh_cable': 'Mesh po kabelu',
    'planner.wi.who.ap_cable': 'Přístupový bod po kabelu',
    'planner.wi.who.router': 'Nová poloha routeru',
    'planner.wi.who.both': 'Tahle změna',
    'planner.wi.v.help': '{who} pomůže hlavně v místě „{name}“ ({d})',
    'planner.wi.v.cap': ', rychlost tam ale omezí {cap}',
    'planner.wi.v.worse': 'V místě „{name}“ se signál zhorší ({d}).',
    'planner.wi.v.same': 'V místě „{name}“ se nic nezmění.',
    'planner.wi.v.none': '{who} v tvých bodech skoro nic nezmění.',
    'planner.wi.v.hurt': '{who} tvým bodům spíš uškodí – nejvíc v místě „{name}“ ({d}).',
    'planner.wi.v.helpSlow': '{who} zlepší signál hlavně v místě „{name}“ ({d}), rychlost tam ale klesne z {a} na ≈ {b} Mb/s, protože ji omezí {cap}.',
    'planner.wi.v.helpWeak': '{who} zlepší signál hlavně v místě „{name}“ ({d}), rychlost tam ale srazí slabé propojení s routerem.',
    'planner.wi.v.slower': 'V místě „{name}“ ale rychlost klesne z {a} na ≈ {b} Mb/s.',
    'planner.wi.v.closer': 'Zkus druhý bod dát blíž k routeru – tam, kde je signál z routeru ještě dobrý.',
    'planner.wi.tip.slower': 'Přes druhý bod tu bude pomaleji než dnes přímo z routeru.',
    'planner.wi.tip.weak': 'Rychlost po změně neodhadnu – signál tu bude slabší než při tvém nejslabším měření rychlosti.',
    'planner.wi.cap.backhaul': 'omezeno propojením ≈ {v} Mb/s',
    'planner.wi.cap.device': 'omezeno stropem zařízení ≈ {v} Mb/s',
    'planner.wi.cap.plan': 'omezeno tarifem ≈ {v} Mb/s',
    'planner.wi.cap.link': 'omezeno přípojkou ≈ {v} Mb/s',
    'planner.wi.capU': 'omezeno slabým propojením s routerem',
    'planner.wi.capNU': 'slabé propojení s routerem',
    'planner.node.bhTooWeak': 'Spojení s routerem je slabší než tvé nejslabší měření rychlosti – rychlost propojení neodhadnu, bude ale nízká. Posuň bod blíž k routeru.',
    'planner.wi.capN.backhaul': 'propojení s routerem (≈ {v} Mb/s)',
    'planner.wi.capN.device': 'strop zařízení (≈ {v} Mb/s)',
    'planner.wi.capN.plan': 'tvůj tarif (≈ {v} Mb/s)',
    'planner.wi.capN.link': 'přípojka (≈ {v} Mb/s)',
    'planner.wi.tip.measured': 'Naměřeno: {v}',
    'planner.wi.tip.model': 'Model: dnes {a} → po změně {b}',
    'planner.wi.tip.pred': 'Odhad po změně:',
    'planner.wi.tip.fromNode': 'Signál tu dá druhý bod.',
    'planner.wi.tip.fromRouter': 'Signál tu dá router.',
    'planner.wi.tip.bandNew': 'Zařízení tu přejde z {a} na {b} GHz.',
    'planner.wi.nameNo': '{name} ({n})',
    'planner.wi.tip.note': 'Orientační: tvoje měření posunuté o změnu, kterou čeká model.',
    'planner.wi.off': 'Leží na zdi nebo mimo místnost',
    'planner.wi.offBtn': 'Posunout dovnitř',
    'planner.wi.offAll': 'Některé body leží na zdi nebo mimo místnost.',
    'planner.wi.offAllBtn': 'Posunout všechny dovnitř',
    'planner.wi.movedIn.one': 'Bod jsem posunul dovnitř místnosti.',
    'planner.wi.movedIn.few': '{n} body jsem posunul dovnitř místností.',
    'planner.wi.movedIn.other': '{n} bodů jsem posunul dovnitř místností.',
    'planner.undo.measInside': 'Posunout měření dovnitř',
    'planner.node.max': 'Kolik zvládne',
    'planner.node.bhSpeedCap': 'Propojení s routerem ≈ {v} Mb/s – rychlejší to přes tento bod nebude.',
    'planner.node.bhSpeedMax': 'Propojení s routerem ≈ {v} Mb/s, strop zařízení {m} Mb/s je ale níž – rychlejší to přes tento bod nebude.',
    'planner.node.maxOnly': 'Přes tento bod nejvýš {v} Mb/s (strop zařízení).',
    'planner.node.bhCable': 'Po kabelu: propojení rychlost neomezí, jen strop zařízení a tarif.',
    'planner.node.bhNoCurve': 'Rychlost propojení odhadnu, až budou aspoň 2 měření rychlosti.',
    'planner.legend.cap': 'šrafy: rychlost tu omezí {what}',
    'planner.tip.reserve': 'Rychlost je po odečtení rezervy {r}.',
    'planner.tip.speedBh': 'Spojení druhého bodu s routerem je na odhad rychlosti moc slabé.',
    'planner.undo.nodeMax': 'Strop druhého bodu',
    'help.whatIf.t': 'Co by se změnilo v tvých bodech',
    'help.whatIf.b': 'Když posuneš router nebo zapneš druhý bod, aplikace u každého měření ukáže, co by tam bylo: tvoje naměřená hodnota posunutá o změnu, kterou čeká model. Třeba −72 → −58 (+14) znamená o 14 dB silnější signál.',
    'help.whatIf.more': 'U rychlosti počítá i s tím, co ji omezí: propojení opakovače s routerem, strop zařízení nebo tvůj tarif. Je to orientační odhad. Na mapě to vypneš ve Vrstvách (Předpověď u bodů) nebo klávesou P.',
    'help.nodeMax.t': 'Kolik zvládne druhý bod',
    'help.nodeMax.b': 'Nejvyšší rychlost, kterou tvůj opakovač nebo mesh reálně zvládne (Mb/s). Třeba levný opakovač Wi-Fi 5 ≈ 300 Mb/s, mesh Wi-Fi 6 s vyhrazeným propojením ≈ 600–900 Mb/s.',
    'help.nodeMax.more': 'Když to nevíš, nech pole prázdné. Rychlost přes bezdrátový bod stejně omezí jeho spojení s routerem.',
  });

  I.add('en', {
    'planner.wi.title': 'What would change at your points',
    'planner.wi.idle': 'Move the router or switch on a second access point – then you will see here how much each measured point improves or gets worse.',
    'planner.wi.avg': 'Average {d}',
    'planner.wi.up': 'better: {n}',
    'planner.wi.down': 'worse: {n}',
    'planner.wi.same': 'unchanged: {n}',
    'planner.wi.rowAria': '{name}: {a} → {b} dBm ({d})',
    'planner.wi.res': 'Your measured points ({n}): average {d}, better {up}, worse {down}.',
    'planner.wi.details': 'Details',
    'planner.wi.who.repeater': 'The repeater',
    'planner.wi.who.mesh_wifi': 'The wireless mesh node',
    'planner.wi.who.mesh_cable': 'The wired mesh node',
    'planner.wi.who.ap_cable': 'The wired access point',
    'planner.wi.who.router': 'The new router position',
    'planner.wi.who.both': 'This change',
    'planner.wi.v.help': '{who} helps most at “{name}” ({d})',
    'planner.wi.v.cap': ', but {cap} limits the speed there',
    'planner.wi.v.worse': 'At “{name}” the signal gets worse ({d}).',
    'planner.wi.v.same': 'Nothing changes at “{name}”.',
    'planner.wi.v.none': '{who} hardly changes anything at your points.',
    'planner.wi.v.hurt': '{who} rather hurts your points – most at “{name}” ({d}).',
    'planner.wi.v.helpSlow': '{who} improves the signal most at “{name}” ({d}), but the speed there drops from {a} to ≈ {b} Mbps because {cap} limits it.',
    'planner.wi.v.helpWeak': '{who} improves the signal most at “{name}” ({d}), but the weak link to the router drags the speed there down.',
    'planner.wi.v.slower': 'At “{name}”, though, the speed drops from {a} to ≈ {b} Mbps.',
    'planner.wi.v.closer': 'Try the second point closer to the router – where the router’s signal is still good.',
    'planner.wi.tip.slower': 'Through the second point this spot gets slower than today straight from the router.',
    'planner.wi.tip.weak': 'I cannot estimate the speed after the change – the signal here would be weaker than in your weakest speed test.',
    'planner.wi.cap.backhaul': 'limited by the link ≈ {v} Mbps',
    'planner.wi.cap.device': 'limited by the device ceiling ≈ {v} Mbps',
    'planner.wi.cap.plan': 'limited by your plan ≈ {v} Mbps',
    'planner.wi.cap.link': 'limited by the connection ≈ {v} Mbps',
    'planner.wi.capU': 'limited by the weak link to the router',
    'planner.wi.capNU': 'the weak link to the router',
    'planner.node.bhTooWeak': 'The link to the router is weaker than your weakest speed test – I cannot estimate its speed, but it will be low. Move the point closer to the router.',
    'planner.wi.capN.backhaul': 'the link to the router (≈ {v} Mbps)',
    'planner.wi.capN.device': 'the device’s ceiling (≈ {v} Mbps)',
    'planner.wi.capN.plan': 'your internet plan (≈ {v} Mbps)',
    'planner.wi.capN.link': 'the connection (≈ {v} Mbps)',
    'planner.wi.tip.measured': 'Measured: {v}',
    'planner.wi.tip.model': 'Model: today {a} → after the change {b}',
    'planner.wi.tip.pred': 'Estimate after the change:',
    'planner.wi.tip.fromNode': 'The second point serves this spot.',
    'planner.wi.tip.fromRouter': 'The router serves this spot.',
    'planner.wi.tip.bandNew': 'The device moves from {a} to {b} GHz here.',
    'planner.wi.nameNo': '{name} ({n})',
    'planner.wi.tip.note': 'Approximate: your measurement shifted by the change the model expects.',
    'planner.wi.off': 'Sits on a wall or outside the rooms',
    'planner.wi.offBtn': 'Move inside',
    'planner.wi.offAll': 'Some points sit on a wall or outside the rooms.',
    'planner.wi.offAllBtn': 'Move them all inside',
    'planner.wi.movedIn.one': 'Moved the point inside its room.',
    'planner.wi.movedIn.other': 'Moved {n} points inside their rooms.',
    'planner.undo.measInside': 'Move measurements inside',
    'planner.node.max': 'Max speed it handles',
    'planner.node.bhSpeedCap': 'Link to the router ≈ {v} Mbps – nothing gets faster than that through this point.',
    'planner.node.bhSpeedMax': 'Link to the router ≈ {v} Mbps, but the device’s ceiling of {m} Mbps is lower – nothing gets faster than that through this point.',
    'planner.node.maxOnly': 'At most {v} Mbps through this point (the device’s ceiling).',
    'planner.node.bhCable': 'By cable: the link does not limit the speed, only the device’s ceiling and your plan do.',
    'planner.node.bhNoCurve': 'I can estimate the link speed once there are at least 2 speed measurements.',
    'planner.legend.cap': 'hatched: {what} limits the speed here',
    'planner.tip.reserve': 'The speed is shown after your {r} reserve.',
    'planner.tip.speedBh': 'The second point’s link to the router is too weak for a speed estimate.',
    'planner.undo.nodeMax': 'Second point ceiling',
    'help.whatIf.t': 'What would change at your points',
    'help.whatIf.b': 'When you move the router or switch on a second point, every measurement shows what it would be: your measured value shifted by the change the model expects. For example −72 → −58 (+14) means a 14 dB stronger signal.',
    'help.whatIf.more': 'For speed it also counts what limits it: the repeater’s link to the router, the device’s ceiling or your internet plan. It is an approximate estimate. To hide it on the map use Layers (Predicted change at points) or the P key.',
    'help.nodeMax.t': 'Max speed of the second point',
    'help.nodeMax.b': 'The highest speed your repeater or mesh node really manages (Mbps). For example a cheap Wi-Fi 5 repeater ≈ 300 Mbps, a Wi-Fi 6 mesh with a dedicated link ≈ 600–900 Mbps.',
    'help.nodeMax.more': 'Leave it empty if you do not know. The speed through a wireless point is limited by its link to the router anyway.',
  });
})();
