/* Floor-plan editor strings for floors (SPEC 14.3) - cs + en. Only WH.i18n.add() calls here. */
(function () {
  'use strict';
  const WH = globalThis.WH;

  WH.i18n.add('cs', {
    'editor.floor.bar': 'Patra domu',
    'editor.floor.label': 'Patra',
    'editor.floor.add': 'Patro',
    'editor.floor.addShort': 'Přidat patro',
    'editor.floor.addUp': 'Nové prázdné patro nahoru',
    'editor.floor.addDown': 'Nové prázdné patro dolů (suterén)',
    'editor.floor.copy': 'Duplikovat půdorys do nového patra',
    'editor.floor.more': 'Možnosti patra',
    'editor.floor.rename': 'Přejmenovat',
    'editor.floor.renameT': 'Přejmenovat patro',
    'editor.floor.name': 'Název patra',
    'editor.floor.nameEmpty': 'Napiš nějaký název.',
    'editor.floor.save': 'Uložit',
    'editor.floor.up': 'Posunout výš',
    'editor.floor.down': 'Posunout níž',
    'editor.floor.delete': 'Smazat patro',
    'editor.floor.deleteShort': 'Smazat patro',
    'editor.floor.delT': 'Smazat patro „{name}“?',
    'editor.floor.delB.one': 'Smaže se i jeho půdorys ({n} místnost) a měření z tohoto patra. Jde to vrátit přes Zpět.',
    'editor.floor.delB.few': 'Smaže se i jeho půdorys ({n} místnosti) a měření z tohoto patra. Jde to vrátit přes Zpět.',
    'editor.floor.delB.other': 'Smaže se i jeho půdorys ({n} místností) a měření z tohoto patra. Jde to vrátit přes Zpět.',
    'editor.floor.delRouter': 'Router je na tomhle patře, přesunu ho do patra, které zůstane.',
    'editor.floor.delOk': 'Smazat patro',
    'editor.floor.deleted': 'Patro „{name}“ je smazané.',
    'editor.floor.added': 'Přidal jsem patro „{name}“. Nakresli jeho místnosti.',
    'editor.floor.copied': 'Hotovo: patro „{name}“ má stejný půdorys. Uprav, co je jinak.',
    'editor.floor.limit': 'Dům může mít nejvýš {n} pater.',
    'editor.floor.lastOne': 'Poslední patro smazat nejde.',
    'editor.floor.topmost': 'Tohle patro už je nejvýš.',
    'editor.floor.lowest': 'Tohle patro už je nejníž.',
    'editor.floor.noUp': 'Nad tímhle patrem už žádné není.',
    'editor.floor.noDown': 'Pod tímhle patrem už žádné není.',
    'editor.floor.switched': 'Patro: {name}',
    'editor.floor.ghost': 'Obrys patra pod ním',
    'editor.floor.ghostTip': 'Slabě ukáže půdorys patra „{name}“, ať můžeš zdi zarovnat nad sebe.',
    'editor.floor.problems.one': '{n} problém v půdorysu',
    'editor.floor.problems.few': '{n} problémy v půdorysu',
    'editor.floor.problems.other': '{n} problémů v půdorysu',
    'editor.floor.intro': 'Máš dům nebo mezonet? Přidej další patro: buď prázdné, nebo se stejným půdorysem jako tohle.',
    'editor.floor.introMulti': 'Měřítko je pro všechna patra společné. Strop určuje, kolik signálu projde do patra nad ním.',
    'editor.sec.floors': 'Patra',
    'editor.sec.floor': 'Patro: {name}',
    'editor.ceil.material': 'Strop nad tímto patrem',
    'editor.ceil.loss': 'Útlum stropu při 5 GHz',
    'editor.ceil.height': 'Výška patra',
    'editor.ceil.concrete': 'Betonový strop',
    'editor.ceil.reinforced_concrete': 'Železobetonový strop',
    'editor.ceil.wood': 'Dřevěný trámový strop',
    'editor.ceil.custom': 'Vlastní útlum',
    'editor.ceil.note': 'Odděluje tohle patro od patra „{name}“ nad ním.',
    'editor.ceil.topNote': 'Nad tímhle patrem už žádné další není, strop se tu nepočítá.',
    'editor.undo.floorAdd': 'Přidání patra',
    'editor.undo.floorCopy': 'Duplikování patra',
    'editor.undo.floorRename': 'Přejmenování patra',
    'editor.undo.floorMove': 'Přesunutí patra',
    'editor.undo.floorDelete': 'Smazání patra',
    'editor.undo.ceiling': 'Úprava stropu',
    'editor.empty.floorT': 'Prázdné patro',
    'editor.empty.floorB': 'Nakresli místnosti tohohle patra, nebo nahraj obrázek jeho půdorysu.',
    'editor.empty.floorGhost': 'Nakresli místnosti tohohle patra. Slabý obrys pod ním je patro „{name}“, podle něj zarovnáš zdi.',
    'editor.keys.floorUp': 'Patro výš',
    'editor.keys.floorDown': 'Patro níž',

    'help.floors.t': 'Patra',
    'help.floors.b': 'Každé patro má svůj půdorys. Signál z routeru projde stropem do ostatních pater, jen slabší: betonový strop ubere asi 15 dB, železobetonový 20 dB, dřevěný 8 dB.',
    'help.floors.more': '„Duplikovat půdorys do nového patra“ se hodí, když jsou patra nad sebou stejná. Měřítko platí pro všechna patra najednou. Schodiště nakresli nástrojem Nábytek jako „Otvor (schodiště)“ do horního patra: tam signál mezi patry projde bez útlumu stropu.',
    'help.ceiling.t': 'Strop mezi patry',
    'help.ceiling.b': 'Strop tlumí signál, který jde do patra nad ním. Běžný betonový strop asi 15 dB, železobetonový 20 dB, dřevěný trámový jen 8 dB. Každé 3 dB navíc zhruba půlí sílu signálu.',
    'help.ceiling.more': 'Výška patra (obvykle 2,7 m) prodlužuje cestu signálu mezi patry. Útlum zadáváš pro 5 GHz; 2,4 GHz projde líp, 6 GHz hůř.',
  });

  WH.i18n.add('en', {
    'editor.floor.bar': 'Floors of the house',
    'editor.floor.label': 'Floors',
    'editor.floor.add': 'Floor',
    'editor.floor.addShort': 'Add a floor',
    'editor.floor.addUp': 'New empty floor above',
    'editor.floor.addDown': 'New empty floor below (basement)',
    'editor.floor.copy': 'Copy this plan to a new floor',
    'editor.floor.more': 'Floor options',
    'editor.floor.rename': 'Rename',
    'editor.floor.renameT': 'Rename the floor',
    'editor.floor.name': 'Floor name',
    'editor.floor.nameEmpty': 'Please type a name.',
    'editor.floor.save': 'Save',
    'editor.floor.up': 'Move up',
    'editor.floor.down': 'Move down',
    'editor.floor.delete': 'Delete the floor',
    'editor.floor.deleteShort': 'Delete the floor',
    'editor.floor.delT': 'Delete the floor “{name}”?',
    'editor.floor.delB.one': 'Its plan ({n} room) and the measurements taken on it go too. Undo brings it back.',
    'editor.floor.delB.other': 'Its plan ({n} rooms) and the measurements taken on it go too. Undo brings it back.',
    'editor.floor.delRouter': 'The router is on this floor; I will move it to a floor that stays.',
    'editor.floor.delOk': 'Delete the floor',
    'editor.floor.deleted': 'The floor “{name}” is deleted.',
    'editor.floor.added': 'Added the floor “{name}”. Draw its rooms.',
    'editor.floor.copied': 'Done: the floor “{name}” has the same plan. Change what is different.',
    'editor.floor.limit': 'A house can have at most {n} floors.',
    'editor.floor.lastOne': 'The last floor cannot be deleted.',
    'editor.floor.topmost': 'This floor is already the highest.',
    'editor.floor.lowest': 'This floor is already the lowest.',
    'editor.floor.noUp': 'There is no floor above this one.',
    'editor.floor.noDown': 'There is no floor below this one.',
    'editor.floor.switched': 'Floor: {name}',
    'editor.floor.ghost': 'Outline of the floor below',
    'editor.floor.ghostTip': 'Shows the plan of “{name}” faintly, so you can line the walls up.',
    'editor.floor.problems.one': '{n} problem in the plan',
    'editor.floor.problems.other': '{n} problems in the plan',
    'editor.floor.intro': 'A house or a maisonette? Add another floor: an empty one, or one with the same plan as this.',
    'editor.floor.introMulti': 'All floors share one scale. The ceiling sets how much signal gets through to the floor above.',
    'editor.sec.floors': 'Floors',
    'editor.sec.floor': 'Floor: {name}',
    'editor.ceil.material': 'Ceiling above this floor',
    'editor.ceil.loss': 'Ceiling loss at 5 GHz',
    'editor.ceil.height': 'Storey height',
    'editor.ceil.concrete': 'Concrete ceiling',
    'editor.ceil.reinforced_concrete': 'Reinforced concrete ceiling',
    'editor.ceil.wood': 'Wooden beam ceiling',
    'editor.ceil.custom': 'Custom loss',
    'editor.ceil.note': 'It separates this floor from “{name}” above it.',
    'editor.ceil.topNote': 'There is no floor above this one, so its ceiling does not count.',
    'editor.undo.floorAdd': 'Add floor',
    'editor.undo.floorCopy': 'Copy floor',
    'editor.undo.floorRename': 'Rename floor',
    'editor.undo.floorMove': 'Move floor',
    'editor.undo.floorDelete': 'Delete floor',
    'editor.undo.ceiling': 'Edit ceiling',
    'editor.empty.floorT': 'An empty floor',
    'editor.empty.floorB': 'Draw the rooms of this floor, or upload a picture of its plan.',
    'editor.empty.floorGhost': 'Draw the rooms of this floor. The faint outline underneath is “{name}”; use it to line the walls up.',
    'editor.keys.floorUp': 'Floor up',
    'editor.keys.floorDown': 'Floor down',

    'help.floors.t': 'Floors',
    'help.floors.b': 'Every floor has its own plan. The router’s signal gets through the ceiling to the other floors, only weaker: a concrete ceiling takes about 15 dB, reinforced concrete 20 dB, a wooden one 8 dB.',
    'help.floors.more': '“Copy this plan to a new floor” is handy when the floors are the same. The scale applies to all floors at once. Draw the stairwell with the Furniture tool as "Opening (stairwell)" on the upper floor: there the signal between the floors passes without the ceiling loss.',
    'help.ceiling.t': 'Ceiling between floors',
    'help.ceiling.b': 'The ceiling weakens the signal going to the floor above. A typical concrete ceiling about 15 dB, reinforced concrete 20 dB, a wooden beam ceiling only 8 dB. Every extra 3 dB roughly halves the signal power.',
    'help.ceiling.more': 'The storey height (usually 2.7 m) lengthens the signal’s path between floors. The loss is entered for 5 GHz; 2.4 GHz gets through better, 6 GHz worse.',
  });
})();
