/* Floor-plan editor strings for the scale (SPEC 14.1) - cs + en. Only WH.i18n.add() calls here. */
(function () {
  'use strict';
  const WH = globalThis.WH;

  WH.i18n.add('cs', {
    'editor.card.scale': 'Měřítko',
    'editor.scale.verified': 'Ověřeno',
    'editor.scale.unverified': 'Neověřeno',
    'editor.scale.totalFlat': 'plocha bytu podle plánku',
    'editor.scale.totalHouse': 'plocha všech pater podle plánku',
    'editor.scale.biggest': 'Největší: {name} {area}',
    'editor.scale.smallest': 'nejmenší: {name} {area}',
    'editor.scale.without': 'Do plochy nepočítám: {names}.',
    'editor.scale.empty': 'Plochu bytu spočítám, až nakreslíš místnosti. Délky vidíš při kreslení u kurzoru.',
    'editor.scale.emptyImage': 'Označ v obrázku vzdálenost, kterou znáš (třeba šířku dveří), nebo obkresli místnosti a pak zadej plochu bytu.',
    'editor.scale.notYet': 'Měřítko zatím nikdo neověřil.',
    'editor.scale.okPlain': 'Měřítko je ověřené.',
    'editor.scale.warn': 'Měřítko není ověřené, takže plochy můžou být úplně mimo (třeba 100 m² místo 58 m²). Stačí jedna míra, kterou znáš:',
    'editor.scale.by.area': 'Podle plochy bytu {area}.',
    'editor.scale.by.areaPlain': 'Podle plochy bytu.',
    'editor.scale.by.room': 'Podle místnosti {name} ({area}).',
    'editor.scale.by.points': 'Podle vzdálenosti {m} na plánku.',
    'editor.scale.by.pointsPlain': 'Podle vzdálenosti na plánku.',
    'editor.scale.by.width': 'Podle šířky půdorysu {m}.',
    'editor.scale.by.import': 'Z načteného souboru, potvrzené.',
    'editor.scale.change': 'Změnit měřítko',
    'editor.scale.methods': 'Jak nastavit měřítko',
    'editor.scale.m.area': 'Plocha bytu',
    'editor.scale.m.points': 'Dvě místa',
    'editor.scale.m.width': 'Šířka',
    'editor.scale.areaLabel': 'Plocha bytu',
    'editor.scale.areaPh': 'např. 58',
    'editor.scale.apply': 'Použít',
    'editor.scale.preview': 'Místnosti pak budou mít: {rooms}',
    'editor.scale.pointsText': 'Klikni na dvě místa, jejichž skutečnou vzdálenost znáš: délku stěny, šířku dveří (obvykle 80 cm) nebo kótu na plánku.',
    'editor.scale.pointsBtn': 'Změřit na plánku',
    'editor.scale.widthHelp': 'Od levého okraje nejlevější místnosti po pravý okraj nejpravější.',
    'editor.scale.badArea': 'Zadej plochu od {min} do {max} m².',
    'editor.scale.badRoom': 'Zadej plochu od {min} do {max} m².',
    'editor.scale.badLen': 'Zadej délku od {min} do {max} m.',
    'editor.scale.badWidth': 'Zadej šířku od {min} do {max} m.',
    'editor.scale.applied': 'Byt teď má {total} · {rooms}',
    'editor.scale.clamped': 'Tohle je mimo rozsah, použil jsem nejbližší možné měřítko.',
    'editor.scale.suspicious': 'To vypadá podezřele – zkontroluj zadané číslo, případně dej Zpět.',
    'editor.scale.confirmed': 'Díky, měřítko je ověřené.',
    'editor.scale.ask.t': 'Víš, kolik má byt m²?',
    'editor.scale.ask.b': 'Napiš ji a měřítko se dopočítá (najdeš ji ve smlouvě nebo v inzerátu).',
    'editor.scale.ask.points': 'Raději změřím dvě místa',
    'editor.scale.ask.later': 'Teď ne',
    'editor.scale.leave.go': 'Teď ne, jdu na Wi-Fi',
    'editor.scale.roomHas': 'Tahle místnost má',
    'editor.scale.wallHas': 'Tahle zeď měří',
    'editor.scale.objNote': 'Podle toho se dopočítá měřítko celého plánu (tvary zůstanou).',
    'editor.scale.banner': 'Měřítko z načteného souboru: byt ≈ {area}. Sedí?',
    'editor.scale.bannerOk': 'Sedí',
    'editor.scale.importT': 'Měřítko z načteného souboru',
    'editor.scale.importB': 'Podle něj má byt ≈ {area}. Sedí to?',
    'editor.scale.bannerEdit': 'Upravit',
    'editor.hint.scaleAsk': 'Víš, kolik má byt m²? Měřítko se z toho dopočítá.',
    'editor.hint.scaleAskBtn': 'Zadat plochu',
    'editor.hint.scaleImage': 'Nejdřív měřítko: označ v obrázku známou vzdálenost, nebo obkresli místnosti a zadej plochu bytu.',
    'editor.hint.scaleImageBtn': 'Označit vzdálenost',
    'editor.hint.scaleBlank': 'Kresli ve skutečných metrech, délky vidíš u kurzoru. Až nakreslíš místnosti, zadáš plochu bytu a měřítko se dopočítá.',
    'editor.undo.scaleOk': 'Potvrzení měřítka',
    'editor.check.setScale': 'Nastavit měřítko',
    'editor.tour.scale.t': 'Měřítko',
    'editor.tour.scale.b': 'Tady vidíš, kolik m² má byt podle plánku. Když to nesedí, zadej skutečnou plochu nebo jednu známou vzdálenost a všechno se přepočítá.',
    'editor.issue.onFloor': '(patro {floor})',
    'editor.issue.scale.unverified.t': 'Měřítko není ověřené',
    'editor.issue.scale.unverified.b': 'Plochy a vzdálenosti můžou být úplně mimo. Zadej plochu bytu nebo jednu vzdálenost, kterou znáš.',
    'editor.issue.scale.areaSmall.t': 'Byt je podezřele malý',
    'editor.issue.scale.areaSmall.b': 'Podle plánku má byt jen {area} (méně než {limit}). Asi nesedí měřítko.',
    'editor.issue.scale.areaLarge.t': 'Byt je podezřele velký',
    'editor.issue.scale.areaLarge.b': 'Podle plánku má byt {area} (víc než {limit}). Asi nesedí měřítko.',
    'editor.issue.scale.roomSmall.t': 'Hodně malá místnost',
    'editor.issue.scale.roomSmall.b': '„{name}“ má jen {area} (méně než {limit}). Je opravdu tak malá, nebo nesedí měřítko?',
    'editor.issue.scale.roomLarge.t': 'Hodně velká místnost',
    'editor.issue.scale.roomLarge.b': '„{name}“ má {area} (víc než {limit}). Je opravdu tak velká, nebo nesedí měřítko?',
    'editor.issue.scale.doorNarrow.t': 'Moc úzké dveře',
    'editor.issue.scale.doorNarrow.b': '„{name}“ jsou široké jen {w} (běžné dveře mají aspoň {limit}). Možná nesedí měřítko.',
    'editor.issue.scale.doorWide.t': 'Moc široké dveře',
    'editor.issue.scale.doorWide.b': '„{name}“ jsou široké {w} (běžné dveře mají nejvýš {limit}). Možná nesedí měřítko, nebo je to široký průchod.',

    'help.scaleVerify.t': 'Ověřené měřítko',
    'help.scaleVerify.b': 'Plánek sám neví, jak velký je byt. Stačí jedna skutečná míra (plocha bytu, délka stěny nebo šířka dveří) a všechny vzdálenosti se dopočítají. Bez ní může model počítat třeba se 100 m² místo 58 m² a signál odhadne úplně špatně.',
    'help.scaleVerify.more': 'Do plochy bytu se počítají všechny místnosti kromě těch, které k bytu nepatří (balkon, terasa; vybereš je v režimu Wi-Fi v Pokročilých). Tvary místností zůstanou, změní se jen jejich skutečná velikost.',
  });

  WH.i18n.add('en', {
    'editor.card.scale': 'Scale',
    'editor.scale.verified': 'Verified',
    'editor.scale.unverified': 'Not verified',
    'editor.scale.totalFlat': 'floor area of the home on the plan',
    'editor.scale.totalHouse': 'floor area of all floors on the plan',
    'editor.scale.biggest': 'Biggest: {name} {area}',
    'editor.scale.smallest': 'smallest: {name} {area}',
    'editor.scale.without': 'Not counted in the area: {names}.',
    'editor.scale.empty': 'I will work out the floor area once you draw the rooms. Lengths show next to the cursor while you draw.',
    'editor.scale.emptyImage': 'Mark a distance you know in the picture (a door width, say), or trace the rooms and then enter the floor area.',
    'editor.scale.notYet': 'Nobody has verified the scale yet.',
    'editor.scale.okPlain': 'The scale is verified.',
    'editor.scale.warn': 'The scale is not verified, so the areas may be way off (100 m² instead of 58 m², say). One measurement you know is enough:',
    'editor.scale.by.area': 'From the floor area of {area}.',
    'editor.scale.by.areaPlain': 'From the floor area.',
    'editor.scale.by.room': 'From the room {name} ({area}).',
    'editor.scale.by.points': 'From a distance of {m} on the plan.',
    'editor.scale.by.pointsPlain': 'From a distance on the plan.',
    'editor.scale.by.width': 'From the plan width of {m}.',
    'editor.scale.by.import': 'From the loaded file, confirmed.',
    'editor.scale.change': 'Change the scale',
    'editor.scale.methods': 'How to set the scale',
    'editor.scale.m.area': 'Floor area',
    'editor.scale.m.points': 'Two points',
    'editor.scale.m.width': 'Width',
    'editor.scale.areaLabel': 'Floor area of the home',
    'editor.scale.areaPh': 'e.g. 58',
    'editor.scale.apply': 'Apply',
    'editor.scale.preview': 'The rooms will then have: {rooms}',
    'editor.scale.pointsText': 'Click two points whose real distance you know: the length of a wall, a door width (usually 80 cm) or a dimension written on the plan.',
    'editor.scale.pointsBtn': 'Measure on the plan',
    'editor.scale.widthHelp': 'From the left edge of the leftmost room to the right edge of the rightmost one.',
    'editor.scale.badArea': 'Enter an area from {min} to {max} m².',
    'editor.scale.badRoom': 'Enter an area from {min} to {max} m².',
    'editor.scale.badLen': 'Enter a length from {min} to {max} m.',
    'editor.scale.badWidth': 'Enter a width from {min} to {max} m.',
    'editor.scale.applied': 'The home now has {total} · {rooms}',
    'editor.scale.clamped': 'That is out of range, so I used the closest possible scale.',
    'editor.scale.suspicious': 'That looks suspicious – check the number you typed, or press Undo.',
    'editor.scale.confirmed': 'Thanks, the scale is verified.',
    'editor.scale.ask.t': 'Do you know the floor area in m²?',
    'editor.scale.ask.b': 'Type it in and the scale follows (it is in the lease or the listing).',
    'editor.scale.ask.points': 'I would rather measure two points',
    'editor.scale.ask.later': 'Not now',
    'editor.scale.leave.go': 'Not now, go to Wi-Fi',
    'editor.scale.roomHas': 'This room has',
    'editor.scale.wallHas': 'This wall is',
    'editor.scale.objNote': 'The scale of the whole plan follows from it (the shapes stay).',
    'editor.scale.banner': 'Scale from the loaded file: the home is ≈ {area}. Is that right?',
    'editor.scale.bannerOk': 'Yes',
    'editor.scale.importT': 'Scale from the loaded file',
    'editor.scale.importB': 'With it the home has ≈ {area}. Is that right?',
    'editor.scale.bannerEdit': 'Adjust',
    'editor.hint.scaleAsk': 'Know the floor area in m²? The scale follows from it.',
    'editor.hint.scaleAskBtn': 'Enter the area',
    'editor.hint.scaleImage': 'Scale first: mark a distance you know in the picture, or trace the rooms and enter the floor area.',
    'editor.hint.scaleImageBtn': 'Mark a distance',
    'editor.hint.scaleBlank': 'Draw in real metres, the lengths show next to the cursor. Once the rooms are drawn, enter the floor area and the scale follows.',
    'editor.undo.scaleOk': 'Confirm the scale',
    'editor.check.setScale': 'Set the scale',
    'editor.tour.scale.t': 'Scale',
    'editor.tour.scale.b': 'This shows how many m² the home has on the plan. If that is wrong, enter the real floor area or one distance you know and everything follows.',
    'editor.issue.onFloor': '({floor})',
    'editor.issue.scale.unverified.t': 'The scale is not verified',
    'editor.issue.scale.unverified.b': 'Areas and distances may be way off. Enter the floor area or one distance you know.',
    'editor.issue.scale.areaSmall.t': 'The home looks too small',
    'editor.issue.scale.areaSmall.b': 'On the plan the home has only {area} (less than {limit}). The scale is probably wrong.',
    'editor.issue.scale.areaLarge.t': 'The home looks too big',
    'editor.issue.scale.areaLarge.b': 'On the plan the home has {area} (more than {limit}). The scale is probably wrong.',
    'editor.issue.scale.roomSmall.t': 'A very small room',
    'editor.issue.scale.roomSmall.b': '“{name}” has only {area} (less than {limit}). Is it really that small, or is the scale wrong?',
    'editor.issue.scale.roomLarge.t': 'A very big room',
    'editor.issue.scale.roomLarge.b': '“{name}” has {area} (more than {limit}). Is it really that big, or is the scale wrong?',
    'editor.issue.scale.doorNarrow.t': 'A very narrow door',
    'editor.issue.scale.doorNarrow.b': '“{name}” is only {w} wide (ordinary doors are at least {limit}). The scale may be wrong.',
    'editor.issue.scale.doorWide.t': 'A very wide door',
    'editor.issue.scale.doorWide.b': '“{name}” is {w} wide (ordinary doors are at most {limit}). The scale may be wrong, or it is a wide opening.',

    'help.scaleVerify.t': 'Verified scale',
    'help.scaleVerify.b': 'The drawing itself does not know how big the home is. One real measurement (the floor area, a wall length or a door width) is enough and every distance follows from it. Without it the model may assume 100 m² instead of 58 m² and get the signal completely wrong.',
    'help.scaleVerify.more': 'The floor area counts every room except the ones that are not part of the home (a balcony or terrace; you pick them in Wi-Fi mode under Advanced). The room shapes stay; only their real size changes.',
  });
})();
