/* Floor-plan editor strings (cs + en). Only WH.i18n.add() calls here (build.mjs evaluates this file with a stub). */
(function () {
  'use strict';
  const WH = globalThis.WH;

  WH.i18n.add('cs', {
    'editor.aria.rail': 'Nástroje pro kreslení půdorysu',
    'editor.aria.stage': 'Kreslicí plocha půdorysu',
    'editor.aria.inspector': 'Vlastnosti půdorysu',
    'editor.aria.zoom': 'Přiblížení plánu',

    'editor.tool.select': 'Vybrat a posunout',
    'editor.tool.rect': 'Obdélníková místnost',
    'editor.tool.poly': 'Místnost po bodech',
    'editor.tool.wall': 'Zeď',
    'editor.tool.door': 'Dveře nebo průchod',
    'editor.tool.furniture': 'Nábytek',
    'editor.tool.scale': 'Nastavit měřítko',
    'editor.btn.undo': 'Zpět',
    'editor.btn.redo': 'Znovu',
    'editor.btn.zoomIn': 'Přiblížit',
    'editor.btn.zoomOut': 'Oddálit',
    'editor.btn.fit': 'Zobrazit celý plán',
    'editor.done': 'Hotovo',
    'editor.done.tip': 'Hotovo, přepnout na mapu Wi-Fi',

    'editor.empty.t': 'Začni první místností',
    'editor.empty.b': 'Klikni na dva protější rohy místnosti. Nebo nahraj obrázek půdorysu (třeba z inzerátu) a obkresli ho.',

    'editor.hint.kbd': '(Enter vloží tvar doprostřed.)',
    'editor.hint.rect1': 'Klikni na první roh místnosti (nebo táhni myší).',
    'editor.hint.rect2': '…a teď klikni na protější roh.',
    'editor.hint.furn1': 'Klikni na první roh: {name} (útlum {db}). Druh nábytku vybereš dole.',
    'editor.hint.poly1': 'Klikni na první bod obrysu místnosti.',
    'editor.hint.poly2': 'Klikej na další rohy. Backspace vrátí poslední bod.',
    'editor.hint.poly3': 'Dokonči kliknutím na první bod, dvojklikem nebo Enterem.',
    'editor.hint.wall1': 'Klikni na začátek zdi.',
    'editor.hint.wall2': 'Klikni na konec zdi. Další zeď naváže, Esc kreslení ukončí.',
    'editor.hint.door': 'Klikni na zeď, kam patří dveře (široké {w}).',
    'editor.hint.doorNoWalls': 'Dveře se vkládají do zdí. Nejdřív nakresli zeď (W) nebo obtáhni místnosti zdmi.',
    'editor.hint.scale1': 'Klikni na začátek úseku, jehož délku znáš: stěna, dveře (obvykle 80 cm) nebo kóta na plánku. Body se přichytí k rohům, koncům zdí a dveřím.',
    'editor.hint.scale2': '…a teď na jeho konec. Délku podle současného měřítka vidíš u kurzoru.',
    'editor.hint.scale3': 'Napiš skutečnou délku v metrech.',
    'editor.hint.selPoly': 'Táhni bílé body. Dvojklik na hranu přidá bod, Alt+klik bod odebere.',
    'editor.hint.selWall': 'Táhni konce zdi. Celou zeď posuneš tažením nebo šipkami.',
    'editor.hint.selDoor': 'Táhni konce dveří po zdi, nebo posuň dveře celé.',
    'editor.hint.empty': 'Prázdný plán: vlevo vyber nástroj, třeba Obdélníkovou místnost (R).',
    'editor.hint.select': 'Klikni na místnost, zeď, dveře nebo nábytek. Tažením prázdného místa posuneš plán.',
    'editor.hint.trace': 'Obkresli místnosti obdélníkem (R) nebo po bodech (P).',

    'editor.opt.autoWalls': 'Zdi kolem nové místnosti',
    'editor.opt.material': 'Materiál nových zdí',
    'editor.opt.width': 'Šířka',
    'editor.opt.preset': 'Druh nábytku',
    'editor.preset.bed': 'Postel',
    'editor.preset.sofa': 'Sedačka',
    'editor.preset.wardrobe': 'Skříň',
    'editor.preset.books': 'Knihovna',
    'editor.preset.appliance': 'Lednice / pračka',
    'editor.preset.table': 'Stůl',
    'editor.preset.metal': 'Kovová skříň',
    'editor.preset.custom': 'Vlastní',

    'editor.mat.default': 'Podle modelu',
    'editor.mat.drywall': 'Sádrokarton',
    'editor.mat.brick': 'Cihla',
    'editor.mat.concrete': 'Beton',
    'editor.mat.reinforced_concrete': 'Železobeton',
    'editor.mat.glass': 'Sklo',
    'editor.mat.wood': 'Dřevo',
    'editor.mat.metal': 'Kov',
    'editor.mat.masonry': 'Zdivo',
    'editor.mat.solid_guess': 'Masivní zeď (odhad)',
    'editor.mat.custom': 'Vlastní hodnota',
    'editor.kind.custom': 'Vlastní útlum',
    'editor.kind.bed': 'Postel / sedačka',
    'editor.kind.wood': 'Dřevěný nábytek',
    'editor.kind.books': 'Knihovna s knihami',
    'editor.kind.appliance': 'Lednice / pračka',
    'editor.kind.metal': 'Kovová skříň',
    'editor.door.open': 'Otevřený průchod (0 dB)',
    'editor.door.closed': 'Zavřené dveře (~3 dB)',
    'editor.door.openShort': 'Průchod',
    'editor.door.closedShort': 'Dveře',

    'editor.card.plan': 'Půdorys',
    'editor.card.check': 'Kontrola půdorysu',
    'editor.card.objects': 'Seznam objektů',
    'editor.count.rooms.one': 'místnost',
    'editor.count.rooms.few': 'místnosti',
    'editor.count.rooms.other': 'místností',
    'editor.count.walls.one': 'zeď',
    'editor.count.walls.few': 'zdi',
    'editor.count.walls.other': 'zdí',
    'editor.count.doors.one': 'dveře',
    'editor.count.doors.few': 'dveře',
    'editor.count.doors.other': 'dveří',
    'editor.count.furniture.one': 'kus nábytku',
    'editor.count.furniture.few': 'kusy nábytku',
    'editor.count.furniture.other': 'kusů nábytku',
    'editor.sec.walls': 'Zdi',
    'editor.sec.bg': 'Podklad k obkreslení',
    'editor.scale.line': '1 m ≈ {px} px na plánku',
    'editor.scale.width': 'Šířka celého půdorysu',
    'editor.scale.ask': 'Kolik je to metrů?',
    'editor.scale.ok': 'Nastavit',
    'editor.scale.bad': 'Zadej délku od 0,1 do 100 m.',
    'editor.scale.note': 'Podle toho se přepočítá velikost celého plánu, tvary zůstanou.',
    'editor.scale.done': 'Měřítko nastaveno: 1 m ≈ {px} px.',
    'editor.autoWalls': 'Obtáhnout zdi kolem místností',
    'editor.autoWalls.done.one': 'Přidal jsem {n} zeď.',
    'editor.autoWalls.done.few': 'Přidal jsem {n} zdi.',
    'editor.autoWalls.done.other': 'Přidal jsem {n} zdí.',
    'editor.autoWalls.none': 'Všechny hrany místností už zeď mají.',
    'editor.autoWalls.noRooms': 'Nejdřív nakresli místnosti.',
    'editor.bg.upload': 'Nahrát podklad k obkreslení',
    'editor.bg.show': 'Zobrazit podklad',
    'editor.bg.opacity': 'Průhlednost podkladu',
    'editor.bg.replace': 'Vyměnit',
    'editor.bg.remove': 'Odebrat',
    'editor.snap': 'Přichytávat k mřížce',
    'editor.colors': 'Rozlišit místnosti barvami',
    'editor.markersNote': 'Router, dnešní polohu routeru a přípojku internetu přesuneš v režimu Wi-Fi.',
    'editor.demo': 'Ukázkový byt',
    'editor.new': 'Nový prázdný plán',

    'editor.type.room': 'Místnost',
    'editor.type.wall': 'Zeď',
    'editor.type.door': 'Dveře',
    'editor.type.furniture': 'Nábytek',
    'editor.f.name': 'Název',
    'editor.f.color': 'Barva',
    'editor.f.area': 'Plocha',
    'editor.f.material': 'Materiál',
    'editor.f.loss5': 'Útlum při 5 GHz',
    'editor.f.bands': 'Útlum při 2,4 / 5 / 6 GHz',
    'editor.f.length': 'Délka',
    'editor.f.doorType': 'Typ otvoru',
    'editor.f.width': 'Šířka',
    'editor.f.onWall': 'Ve zdi',
    'editor.f.kind': 'Druh',
    'editor.f.blocks': 'Blokuje signál',
    'editor.color.n': 'Barva {n}',
    'editor.color.current': 'Současná barva',
    'editor.addDoor': 'Přidat dveře doprostřed',
    'editor.selectWall': 'Vybrat zeď',
    'editor.duplicate': 'Duplikovat',
    'editor.delete': 'Smazat',
    'editor.deselect': 'Zrušit výběr',
    'editor.newRoom': 'Místnost {n}',
    'editor.newWall': 'Zeď {n}',
    'editor.newDoor': 'Dveře {n}',
    'editor.copyName': '{name} (kopie)',

    'editor.search': 'Hledat podle názvu',
    'editor.group.rooms': 'Místnosti',
    'editor.group.walls': 'Zdi',
    'editor.group.doors': 'Dveře',
    'editor.group.furniture': 'Nábytek',
    'editor.list.empty': 'Plán je zatím prázdný.',
    'editor.list.noMatch': 'Nic takového jsem nenašel.',

    'editor.check.empty': 'Až nakreslíš místnosti a zdi, zkontroluju tady, jestli na sebe správně navazují.',
    'editor.check.ok': 'Vypadá to dobře: žádné mezery ve zdech ani jiné chyby.',
    'editor.check.show': 'Ukázat',
    'editor.check.fix': 'Opravit',
    'editor.check.join': 'Spojit',
    'editor.check.ignore': 'Ignorovat',
    'editor.check.fixed': 'Opraveno.',
    'editor.check.shifted': 'Hotovo: zeď „{name}“ je posunutá o {d} cm, aby rovně navazovala.',
    'editor.check.keepOpen': 'Nechat otevřené',
    'editor.check.addWalls': 'Doplnit zdi',
    'editor.check.cantFix': 'Tohle se nedá opravit automaticky. Uprav to prosím ručně.',
    'editor.issue.gap.t': 'Mezera ve zdi',
    'editor.issue.gap.b': '„{a}“ a „{b}“ se skoro potkávají, ale zůstává mezi nimi {d} cm. Tudy by signál „protékal“.',
    'editor.issue.door.t': 'Dveře mimo zeď',
    'editor.issue.door.b': '„{a}“ neleží na své zdi, takže v modelu nefungují.',
    'editor.issue.edges.t': 'Hrany bez zdí',
    'editor.issue.edges.b.one': '{n} úsek hrany místnosti nemá zeď. Je to průchod bez dveří? Pokud ne, doplň zeď.',
    'editor.issue.edges.b.few': '{n} úseky hran místností nemají zeď. Jsou to průchody bez dveří? Pokud ne, doplň zdi.',
    'editor.issue.edges.b.other': '{n} úseků hran místností nemá zeď. Jsou to průchody bez dveří? Pokud ne, doplň zdi.',
    'editor.issue.overlap.t': 'Místnosti se překrývají',
    'editor.issue.overlap.b': '„{a}“ a „{b}“ se překrývají (asi {m} m²). Uprav body jedné z nich.',
    'editor.issue.outside.t': 'Nábytek mimo místnosti',
    'editor.issue.outside.b': '„{a}“ neleží v žádné místnosti.',

    'editor.msg.limit': 'Plán může mít nejvýš 250 objektů každého druhu.',
    'editor.msg.invalid': 'Takhle by se obrys křížil sám se sebou. Zkus body rozmístit jinak.',
    'editor.msg.small': 'To je moc malé, zkus to větší.',
    'editor.msg.min3': 'Místnost potřebuje aspoň 3 body.',
    'editor.msg.maxPoints': 'Jedna místnost může mít nejvýš 200 bodů.',
    'editor.msg.deleted': 'Smazáno: {name}',
    'editor.msg.noDupDoor': 'Dveře se neduplikují. Klikni nástrojem Dveře (D) na zeď.',
    'editor.msg.markers': 'Router a ostatní značky se přesouvají v režimu Wi-Fi (klávesa 2).',
    'editor.msg.scaleShort': 'Body jsou moc blízko u sebe. Vyber delší úsek.',
    'editor.msg.needWall': 'Tady není zeď. Klikni přímo na čáru zdi.',
    'editor.msg.selectWall': 'Vyber zeď (kliknutím nebo v seznamu objektů) a stiskni Enter.',
    'editor.msg.snapOn': 'Přichytávání k mřížce je zapnuté.',
    'editor.msg.snapOff': 'Přichytávání k mřížce je vypnuté.',
    'editor.msg.noBg': 'Plán nemá žádný podklad k obkreslení.',
    'editor.msg.bgOn': 'Podklad je vidět.',
    'editor.msg.bgOff': 'Podklad je skrytý.',

    'editor.undo.addRoom': 'Přidání místnosti',
    'editor.undo.addWall': 'Přidání zdi',
    'editor.undo.addDoor': 'Přidání dveří',
    'editor.undo.addFurniture': 'Přidání nábytku',
    'editor.undo.move': 'Posunutí',
    'editor.undo.reshape': 'Změna tvaru',
    'editor.undo.vertex': 'Úprava bodů',
    'editor.undo.nudge': 'Posunutí šipkami',
    'editor.undo.delete': 'Smazání',
    'editor.undo.duplicate': 'Duplikování',
    'editor.undo.edit': 'Úprava vlastností',
    'editor.undo.scale': 'Změna měřítka',
    'editor.undo.autoWalls': 'Obtažení zdí',
    'editor.undo.colors': 'Obarvení místností',
    'editor.undo.fix': 'Oprava půdorysu',
    'editor.undo.bgRemove': 'Odebrání podkladu',

    'editor.keys.select': 'Nástroj Vybrat a posunout',
    'editor.keys.rect': 'Nástroj Obdélníková místnost',
    'editor.keys.poly': 'Nástroj Místnost po bodech',
    'editor.keys.wall': 'Nástroj Zeď',
    'editor.keys.door': 'Nástroj Dveře',
    'editor.keys.furniture': 'Nástroj Nábytek',
    'editor.keys.scale': 'Nástroj Měřítko',
    'editor.keys.snap': 'Zapnout / vypnout přichytávání k mřížce',
    'editor.keys.trace': 'Skrýt / zobrazit podklad',
    'editor.keys.enter': 'Dokončit místnost po bodech, nebo vložit tvar doprostřed',
    'editor.keys.delete': 'Smazat vybraný objekt (při kreslení po bodech vrátí bod)',
    'editor.keys.duplicate': 'Duplikovat vybraný objekt',
    'editor.keys.nudge': 'Posunout vybraný objekt o 5 cm (se Shiftem o 20 cm)',
    'editor.keys.esc': 'Zrušit kreslení, nástroj nebo výběr',

    'editor.tour.tools.t': 'Nástroje',
    'editor.tour.tools.b': 'Vyber, co chceš kreslit: místnosti, zdi, dveře nebo nábytek. Písmeno v rohu tlačítka je klávesová zkratka.',
    'editor.tour.hint.t': 'Co teď?',
    'editor.tour.hint.b': 'Tenhle řádek vždycky napíše, co udělá další kliknutí.',
    'editor.tour.inspector.t': 'Vlastnosti',
    'editor.tour.inspector.b': 'Tady upravíš vybraný objekt (materiál zdi, dveře, útlum nábytku) nebo celý plán: měřítko, podklad a přichytávání.',
    'editor.tour.check.t': 'Kontrola půdorysu',
    'editor.tour.check.b': 'Najde mezery ve zdech a další chyby, které by zkreslily mapu signálu. Většinu z nich opraví jedním kliknutím.',
    'editor.tour.done.t': 'Hotovo',
    'editor.tour.done.b': 'Plán se ukládá sám. Tímhle tlačítkem (nebo klávesou 2) přejdeš na mapu Wi-Fi.',

    'help.editorCheck.t': 'Kontrola půdorysu',
    'help.editorCheck.b': 'Hlídá chyby, které kazí odhad signálu: mezery mezi zdmi, kudy by signál „protékal“, dveře mimo zeď, hrany místností bez zdí, překryté místnosti a nábytek mimo byt.',
    'help.editorCheck.more': '„Ukázat“ chybu najde na plánku, „Opravit“ ji spraví. Každá oprava jde vrátit přes Ctrl+Z.',
    'help.bandLoss.t': 'Tři čísla útlumu',
    'help.bandLoss.b': 'Zeď tlumí každé pásmo jinak: 2,4 GHz projde nejlíp, 6 GHz nejhůř. Proto má každý materiál tři čísla pro 2,4 / 5 / 6 GHz, třeba cihla 7 / 11 / 13 dB. Každé 3 dB navíc zhruba půlí sílu signálu.',
    'help.bandLoss.more': 'Vlastní číslo zadáváš pro 5 GHz; pro 2,4 GHz se počítá asi 0,65× a pro 6 GHz 1,15× (podle měření NIST a dalších).',
  });

  WH.i18n.add('en', {
    'editor.aria.rail': 'Floor plan drawing tools',
    'editor.aria.stage': 'Floor plan drawing area',
    'editor.aria.inspector': 'Floor plan properties',
    'editor.aria.zoom': 'Plan zoom',

    'editor.tool.select': 'Select and move',
    'editor.tool.rect': 'Rectangular room',
    'editor.tool.poly': 'Room point by point',
    'editor.tool.wall': 'Wall',
    'editor.tool.door': 'Door or opening',
    'editor.tool.furniture': 'Furniture',
    'editor.tool.scale': 'Set the scale',
    'editor.btn.undo': 'Undo',
    'editor.btn.redo': 'Redo',
    'editor.btn.zoomIn': 'Zoom in',
    'editor.btn.zoomOut': 'Zoom out',
    'editor.btn.fit': 'Show the whole plan',
    'editor.done': 'Done',
    'editor.done.tip': 'Done, switch to the Wi-Fi map',

    'editor.empty.t': 'Start with your first room',
    'editor.empty.b': 'Click two opposite corners of a room. Or upload a picture of your floor plan (from a listing, say) and trace it.',

    'editor.hint.kbd': '(Enter inserts a shape in the middle.)',
    'editor.hint.rect1': 'Click the first corner of the room (or drag).',
    'editor.hint.rect2': '…and now click the opposite corner.',
    'editor.hint.furn1': 'Click the first corner: {name} (loss {db}). Pick the type of furniture below.',
    'editor.hint.poly1': 'Click the first point of the room outline.',
    'editor.hint.poly2': 'Click the next corners. Backspace removes the last point.',
    'editor.hint.poly3': 'Finish by clicking the first point, double-clicking or pressing Enter.',
    'editor.hint.wall1': 'Click where the wall starts.',
    'editor.hint.wall2': 'Click where the wall ends. The next wall continues from there; Esc stops.',
    'editor.hint.door': 'Click the wall where the door goes ({w} wide).',
    'editor.hint.doorNoWalls': 'Doors go into walls. Draw a wall first (W) or outline the rooms with walls.',
    'editor.hint.scale1': 'Click the start of a stretch whose length you know: a wall, a door (usually 80 cm) or a dimension on the plan. Points snap to corners, wall ends and doors.',
    'editor.hint.scale2': '…and now its end. The length at the current scale shows next to the cursor.',
    'editor.hint.scale3': 'Type the real length in metres.',
    'editor.hint.selPoly': 'Drag the white dots. Double-click an edge to add a point, Alt+click a point to remove it.',
    'editor.hint.selWall': 'Drag the wall ends. Drag the wall or use the arrow keys to move it.',
    'editor.hint.selDoor': 'Drag the door ends along the wall, or move the whole door.',
    'editor.hint.empty': 'Empty plan: pick a tool on the left, for example Rectangular room (R).',
    'editor.hint.select': 'Click a room, wall, door or furniture. Drag empty space to move the plan.',
    'editor.hint.trace': 'Trace the rooms with rectangles (R) or point by point (P).',

    'editor.opt.autoWalls': 'Walls around new rooms',
    'editor.opt.material': 'Material of new walls',
    'editor.opt.width': 'Width',
    'editor.opt.preset': 'Type of furniture',
    'editor.preset.bed': 'Bed',
    'editor.preset.sofa': 'Sofa',
    'editor.preset.wardrobe': 'Wardrobe',
    'editor.preset.books': 'Bookcase',
    'editor.preset.appliance': 'Fridge / washer',
    'editor.preset.table': 'Table',
    'editor.preset.metal': 'Metal cabinet',
    'editor.preset.custom': 'Custom',

    'editor.mat.default': 'As in the model',
    'editor.mat.drywall': 'Plasterboard',
    'editor.mat.brick': 'Brick',
    'editor.mat.concrete': 'Concrete',
    'editor.mat.reinforced_concrete': 'Reinforced concrete',
    'editor.mat.glass': 'Glass',
    'editor.mat.wood': 'Wood',
    'editor.mat.metal': 'Metal',
    'editor.mat.masonry': 'Masonry',
    'editor.mat.solid_guess': 'Solid wall (guess)',
    'editor.mat.custom': 'Custom value',
    'editor.kind.custom': 'Custom loss',
    'editor.kind.bed': 'Bed / sofa',
    'editor.kind.wood': 'Wooden furniture',
    'editor.kind.books': 'Bookcase with books',
    'editor.kind.appliance': 'Fridge / washer',
    'editor.kind.metal': 'Metal cabinet',
    'editor.door.open': 'Open doorway (0 dB)',
    'editor.door.closed': 'Closed door (~3 dB)',
    'editor.door.openShort': 'Opening',
    'editor.door.closedShort': 'Door',

    'editor.card.plan': 'Floor plan',
    'editor.card.check': 'Plan check',
    'editor.card.objects': 'Object list',
    'editor.count.rooms.one': 'room',
    'editor.count.rooms.other': 'rooms',
    'editor.count.walls.one': 'wall',
    'editor.count.walls.other': 'walls',
    'editor.count.doors.one': 'door',
    'editor.count.doors.other': 'doors',
    'editor.count.furniture.one': 'piece of furniture',
    'editor.count.furniture.other': 'pieces of furniture',
    'editor.sec.walls': 'Walls',
    'editor.sec.bg': 'Tracing background',
    'editor.scale.line': '1 m ≈ {px} px on the plan',
    'editor.scale.width': 'Width of the whole plan',
    'editor.scale.ask': 'How many metres is it?',
    'editor.scale.ok': 'Set',
    'editor.scale.bad': 'Enter a length from 0.1 to 100 m.',
    'editor.scale.note': 'The size of the whole plan follows from it; the shapes stay as they are.',
    'editor.scale.done': 'Scale set: 1 m ≈ {px} px.',
    'editor.autoWalls': 'Outline the rooms with walls',
    'editor.autoWalls.done.one': 'Added {n} wall.',
    'editor.autoWalls.done.other': 'Added {n} walls.',
    'editor.autoWalls.none': 'Every room edge already has a wall.',
    'editor.autoWalls.noRooms': 'Draw some rooms first.',
    'editor.bg.upload': 'Upload an image to trace',
    'editor.bg.show': 'Show the background',
    'editor.bg.opacity': 'Background opacity',
    'editor.bg.replace': 'Replace',
    'editor.bg.remove': 'Remove',
    'editor.snap': 'Snap to the grid',
    'editor.colors': 'Give the rooms different colours',
    'editor.markersNote': 'The router, its position today and the internet inlet are moved in Wi-Fi mode.',
    'editor.demo': 'Demo flat',
    'editor.new': 'New empty plan',

    'editor.type.room': 'Room',
    'editor.type.wall': 'Wall',
    'editor.type.door': 'Door',
    'editor.type.furniture': 'Furniture',
    'editor.f.name': 'Name',
    'editor.f.color': 'Colour',
    'editor.f.area': 'Area',
    'editor.f.material': 'Material',
    'editor.f.loss5': 'Loss at 5 GHz',
    'editor.f.bands': 'Loss at 2.4 / 5 / 6 GHz',
    'editor.f.length': 'Length',
    'editor.f.doorType': 'Type of opening',
    'editor.f.width': 'Width',
    'editor.f.onWall': 'In wall',
    'editor.f.kind': 'Type',
    'editor.f.blocks': 'Blocks signal',
    'editor.color.n': 'Colour {n}',
    'editor.color.current': 'Current colour',
    'editor.addDoor': 'Add a door in the middle',
    'editor.selectWall': 'Select the wall',
    'editor.duplicate': 'Duplicate',
    'editor.delete': 'Delete',
    'editor.deselect': 'Deselect',
    'editor.newRoom': 'Room {n}',
    'editor.newWall': 'Wall {n}',
    'editor.newDoor': 'Door {n}',
    'editor.copyName': '{name} (copy)',

    'editor.search': 'Search by name',
    'editor.group.rooms': 'Rooms',
    'editor.group.walls': 'Walls',
    'editor.group.doors': 'Doors',
    'editor.group.furniture': 'Furniture',
    'editor.list.empty': 'The plan is still empty.',
    'editor.list.noMatch': 'Nothing matches.',

    'editor.check.empty': 'Once you draw rooms and walls, I will check here that they join up properly.',
    'editor.check.ok': 'Looks good: no gaps in the walls and no other problems.',
    'editor.check.show': 'Show',
    'editor.check.fix': 'Fix',
    'editor.check.join': 'Join',
    'editor.check.ignore': 'Ignore',
    'editor.check.fixed': 'Fixed.',
    'editor.check.shifted': 'Done: wall “{name}” moved by {d} cm so it lines up straight.',
    'editor.check.keepOpen': 'Leave open',
    'editor.check.addWalls': 'Add walls',
    'editor.check.cantFix': 'This cannot be fixed automatically. Please adjust it by hand.',
    'editor.issue.gap.t': 'Gap in a wall',
    'editor.issue.gap.b': '“{a}” and “{b}” almost meet but leave a gap of {d} cm that the signal would leak through.',
    'editor.issue.door.t': 'Door off its wall',
    'editor.issue.door.b': '“{a}” does not lie on its wall, so the model ignores it.',
    'editor.issue.edges.t': 'Edges without walls',
    'editor.issue.edges.b.one': '{n} piece of a room edge has no wall. Is it an opening without a door? If not, add a wall.',
    'editor.issue.edges.b.other': '{n} pieces of room edges have no wall. Are they openings without doors? If not, add walls.',
    'editor.issue.overlap.t': 'Rooms overlap',
    'editor.issue.overlap.b': '“{a}” and “{b}” overlap (about {m} m²). Adjust the points of one of them.',
    'editor.issue.outside.t': 'Furniture outside the rooms',
    'editor.issue.outside.b': '“{a}” is not inside any room.',

    'editor.msg.limit': 'A plan can hold at most 250 objects of each kind.',
    'editor.msg.invalid': 'That would make the outline cross itself. Try placing the points differently.',
    'editor.msg.small': 'That is too small, try a bigger one.',
    'editor.msg.min3': 'A room needs at least 3 points.',
    'editor.msg.maxPoints': 'A room can have at most 200 points.',
    'editor.msg.deleted': 'Deleted: {name}',
    'editor.msg.noDupDoor': 'Doors are not duplicated. Click a wall with the Door tool (D).',
    'editor.msg.markers': 'The router and the other markers are moved in Wi-Fi mode (key 2).',
    'editor.msg.scaleShort': 'The points are too close together. Pick a longer stretch.',
    'editor.msg.needWall': 'There is no wall here. Click right on a wall line.',
    'editor.msg.selectWall': 'Select a wall (click it or use the object list) and press Enter.',
    'editor.msg.snapOn': 'Snapping to the grid is on.',
    'editor.msg.snapOff': 'Snapping to the grid is off.',
    'editor.msg.noBg': 'This plan has no tracing background.',
    'editor.msg.bgOn': 'Background shown.',
    'editor.msg.bgOff': 'Background hidden.',

    'editor.undo.addRoom': 'Add room',
    'editor.undo.addWall': 'Add wall',
    'editor.undo.addDoor': 'Add door',
    'editor.undo.addFurniture': 'Add furniture',
    'editor.undo.move': 'Move',
    'editor.undo.reshape': 'Reshape',
    'editor.undo.vertex': 'Edit points',
    'editor.undo.nudge': 'Move with arrow keys',
    'editor.undo.delete': 'Delete',
    'editor.undo.duplicate': 'Duplicate',
    'editor.undo.edit': 'Edit properties',
    'editor.undo.scale': 'Scale change',
    'editor.undo.autoWalls': 'Outline walls',
    'editor.undo.colors': 'Colour rooms',
    'editor.undo.fix': 'Plan fix',
    'editor.undo.bgRemove': 'Remove background',

    'editor.keys.select': 'Select and move tool',
    'editor.keys.rect': 'Rectangular room tool',
    'editor.keys.poly': 'Room point by point tool',
    'editor.keys.wall': 'Wall tool',
    'editor.keys.door': 'Door tool',
    'editor.keys.furniture': 'Furniture tool',
    'editor.keys.scale': 'Scale tool',
    'editor.keys.snap': 'Snap to the grid on / off',
    'editor.keys.trace': 'Hide / show the background',
    'editor.keys.enter': 'Finish a point-by-point room, or insert a shape in the middle',
    'editor.keys.delete': 'Delete the selected object (removes a point while drawing a room)',
    'editor.keys.duplicate': 'Duplicate the selected object',
    'editor.keys.nudge': 'Move the selected object by 5 cm (20 cm with Shift)',
    'editor.keys.esc': 'Cancel drawing, the tool or the selection',

    'editor.tour.tools.t': 'Tools',
    'editor.tour.tools.b': 'Pick what to draw: rooms, walls, doors or furniture. The letter in the corner of each button is its keyboard shortcut.',
    'editor.tour.hint.t': 'What now?',
    'editor.tour.hint.b': 'This line always tells you what your next click will do.',
    'editor.tour.inspector.t': 'Properties',
    'editor.tour.inspector.b': 'Edit the selected object here (wall material, doors, furniture loss) or the whole plan: scale, background and snapping.',
    'editor.tour.check.t': 'Plan check',
    'editor.tour.check.b': 'Finds gaps in walls and other mistakes that would skew the signal map, and fixes most of them in one click.',
    'editor.tour.done.t': 'Done',
    'editor.tour.done.b': 'The plan saves itself. This button (or the 2 key) takes you to the Wi-Fi map.',

    'help.editorCheck.t': 'Plan check',
    'help.editorCheck.b': 'Watches for mistakes that spoil the signal estimate: gaps between walls the signal would leak through, doors off their wall, room edges without walls, overlapping rooms and furniture outside the home.',
    'help.editorCheck.more': '“Show” finds the problem on the plan, “Fix” repairs it. Every fix can be undone with Ctrl+Z.',
    'help.bandLoss.t': 'Three loss numbers',
    'help.bandLoss.b': 'A wall weakens each band differently: 2.4 GHz gets through best, 6 GHz worst. That is why every material has three numbers for 2.4 / 5 / 6 GHz, brick for example 7 / 11 / 13 dB. Every extra 3 dB roughly halves the signal power.',
    'help.bandLoss.more': 'A custom number is entered for 5 GHz; 2.4 GHz uses about 0.65× and 6 GHz 1.15× of it (based on NIST and other measurements).',
  });
})();
